CREATE OR REPLACE TABLE `crp-pro-dominio-negfin.mus_pro_prevfrau_wrk_tbls.STG_BFS_CONTACT_KEYS`
CLUSTER BY K_TYPE, K_VAL, CTA_CVE AS
WITH MAP_PUENTE_SOLICITUDES AS (
  -- Deduplicación estricta: 1 cuenta más reciente por solicitud válida
  SELECT
    BR_SOLIC_CVE_NUM AS BR_SOLIC_CVE,
    CTA_CVE
  FROM (
    SELECT
      SAFE_CAST(BR_SOLIC_CVE AS NUMERIC) AS BR_SOLIC_CVE_NUM,
      CTA_CVE,
      FCH_CARGA,
      ROW_NUMBER() OVER (
        PARTITION BY SAFE_CAST(BR_SOLIC_CVE AS NUMERIC) 
        ORDER BY FCH_CARGA DESC, CTA_CVE ASC
      ) AS RN
    FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA`
    WHERE NULLIF(SAFE_CAST(BR_SOLIC_CVE AS NUMERIC), 0) IS NOT NULL
      AND CTA_CVE > 0
  )
  WHERE RN = 1
),
APIA_RESUELTO AS (
  SELECT
    SAFE_CAST(A.BR_SOLIC_CVE AS NUMERIC) AS BR_SOLIC_CVE,
    COALESCE(
      M.CTA_CVE,
      -SAFE_CAST(A.BR_SOLIC_CVE AS NUMERIC)
    ) AS CTA_CVE_ENTIDAD,
    A.BR_NOM, A.BR_APE_PAT, A.BR_APE_MAT, A.BR_CDP,
    A.BR_MAIL, A.BR_LADA, A.BR_TEL, A.BR_CEL,
    A.BR_TEL_REF1, A.BR_TEL_REF2, A.BR_CEL_REF1, A.BR_CEL_REF2
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_APIA` AS A
  LEFT JOIN MAP_PUENTE_SOLICITUDES AS M
    ON SAFE_CAST(A.BR_SOLIC_CVE AS NUMERIC) = M.BR_SOLIC_CVE
  WHERE NULLIF(SAFE_CAST(A.BR_SOLIC_CVE AS NUMERIC), 0) IS NOT NULL
),
RAW_KEYS AS (
  -- Contactos CLIE_FTES
  SELECT 'CLIE_FTES' AS SRC, CTA_CVE, 'EMAIL' AS K_TYPE, 'EMAIL_TITULAR' AS K_FIELD,
         NULLIF(TRIM(LOWER(CTE_EMA)), '') AS K_VAL,
         CONCAT(TRIM(COALESCE(CTE_NOM, '')), ' ', TRIM(COALESCE(CTE_APE_PAT, '')), ' ', TRIM(COALESCE(CTE_APE_MAT, ''))) AS NOMBRE,
         TRIM(COALESCE(CTE_APE_PAT, '')) AS APE_PAT, COALESCE(CAST(CDP_CVE AS STRING), '') AS CDP_CVE
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL`
  WHERE CTA_CVE > 0 AND NULLIF(TRIM(LOWER(CTE_EMA)), '') IS NOT NULL

  UNION ALL
  SELECT 'CLIE_FTES', CTA_CVE, 'PHONE', 'TEL_TITULAR',
         CASE WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL AS STRING), ''), r'\D', '')) IS NULL THEN NULL ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL AS STRING), ''), r'\D', '')), -10) END,
         CONCAT(TRIM(COALESCE(CTE_NOM, '')), ' ', TRIM(COALESCE(CTE_APE_PAT, '')), ' ', TRIM(COALESCE(CTE_APE_MAT, ''))),
         TRIM(COALESCE(CTE_APE_PAT, '')), COALESCE(CAST(CDP_CVE AS STRING), '')
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL`
  WHERE CTA_CVE > 0 AND CASE WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL AS STRING), ''), r'\D', '')) IS NULL THEN NULL ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL AS STRING), ''), r'\D', '')), -10) END IS NOT NULL

  UNION ALL
  SELECT 'CLIE_FTES', CTA_CVE, 'PHONE', 'CEL_TITULAR',
         CASE WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_CEL AS STRING), ''), r'\D', '')) IS NULL THEN NULL ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_CEL AS STRING), ''), r'\D', '')), -10) END,
         CONCAT(TRIM(COALESCE(CTE_NOM, '')), ' ', TRIM(COALESCE(CTE_APE_PAT, '')), ' ', TRIM(COALESCE(CTE_APE_MAT, ''))),
         TRIM(COALESCE(CTE_APE_PAT, '')), COALESCE(CAST(CDP_CVE AS STRING), '')
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL`
  WHERE CTA_CVE > 0 AND CASE WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_CEL AS STRING), ''), r'\D', '')) IS NULL THEN NULL ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_CEL AS STRING), ''), r'\D', '')), -10) END IS NOT NULL

  UNION ALL
  SELECT 'CLIE_FTES', CTA_CVE, 'PHONE', 'TEL_REF1',
         CASE
           WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_REFERENCIA1 AS STRING), ''), r'\D', '')) IS NULL THEN NULL
           WHEN SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_REFERENCIA1 AS STRING), ''), r'\D', '')), -10) IN ('5555555555','5500000000','45','9510000000','5000000000','3300000000','6180000000','4490000000','3510000000','8100000000','550000000','3110000000','6120000000','4430000000','2299000000','4770000000','8440000000','1111111111','300000000') THEN NULL
           ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_REFERENCIA1 AS STRING), ''), r'\D', '')), -10)
         END,
         CONCAT(TRIM(COALESCE(CTE_NOM, '')), ' ', TRIM(COALESCE(CTE_APE_PAT, '')), ' ', TRIM(COALESCE(CTE_APE_MAT, ''))),
         TRIM(COALESCE(CTE_APE_PAT, '')), COALESCE(CAST(CDP_CVE AS STRING), '')
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL`
  WHERE CTA_CVE > 0 AND ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_REFERENCIA1 AS STRING), ''), r'\D', '')) IS NOT NULL

  UNION ALL
  SELECT 'CLIE_FTES', CTA_CVE, 'PHONE', 'TEL_REF2',
         CASE
           WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_REFERENCIA2 AS STRING), ''), r'\D', '')) IS NULL THEN NULL
           WHEN SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_REFERENCIA2 AS STRING), ''), r'\D', '')), -10) IN ('5555555555','5500000000','45','9510000000','5000000000','3300000000','6180000000','4490000000','3510000000','8100000000','550000000','3110000000','6120000000','4430000000','2299000000','4770000000','8440000000','1111111111','300000000') THEN NULL
           ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_REFERENCIA2 AS STRING), ''), r'\D', '')), -10)
         END,
         CONCAT(TRIM(COALESCE(CTE_NOM, '')), ' ', TRIM(COALESCE(CTE_APE_PAT, '')), ' ', TRIM(COALESCE(CTE_APE_MAT, ''))),
         TRIM(COALESCE(CTE_APE_PAT, '')), COALESCE(CAST(CDP_CVE AS STRING), '')
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL`
  WHERE CTA_CVE > 0 AND ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_REFERENCIA2 AS STRING), ''), r'\D', '')) IS NOT NULL

  -- Contactos APIA
  UNION ALL
  SELECT 'APIA', CTA_CVE_ENTIDAD AS CTA_CVE, 'EMAIL' AS K_TYPE, 'EMAIL_ORIGEN',
         NULLIF(TRIM(LOWER(BR_MAIL)), '') AS K_VAL,
         CONCAT(TRIM(COALESCE(BR_NOM, '')), ' ', TRIM(COALESCE(BR_APE_PAT, '')), ' ', TRIM(COALESCE(BR_APE_MAT, ''))),
         TRIM(COALESCE(BR_APE_PAT, '')), COALESCE(CAST(BR_CDP AS STRING), '')
  FROM APIA_RESUELTO
  WHERE CTA_CVE_ENTIDAD IS NOT NULL AND CTA_CVE_ENTIDAD != 0 AND NULLIF(TRIM(LOWER(BR_MAIL)), '') IS NOT NULL

  UNION ALL
  SELECT 'APIA', CTA_CVE_ENTIDAD AS CTA_CVE, 'PHONE', 'TEL_ORIGEN',
         CASE WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CONCAT(COALESCE(ZEROS_TO_NULL(CAST(BR_LADA AS STRING)), ''), COALESCE(ZEROS_TO_NULL(CAST(BR_TEL AS STRING)), '')), ''), r'\D', '')) IS NULL THEN NULL ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CONCAT(COALESCE(ZEROS_TO_NULL(CAST(BR_LADA AS STRING)), ''), COALESCE(ZEROS_TO_NULL(CAST(BR_TEL AS STRING)), '')), ''), r'\D', '')), -10) END,
         CONCAT(TRIM(COALESCE(BR_NOM, '')), ' ', TRIM(COALESCE(BR_APE_PAT, '')), ' ', TRIM(COALESCE(BR_APE_MAT, ''))),
         TRIM(COALESCE(BR_APE_PAT, '')), COALESCE(CAST(BR_CDP AS STRING), '')
  FROM APIA_RESUELTO
  WHERE CTA_CVE_ENTIDAD IS NOT NULL AND CTA_CVE_ENTIDAD != 0 AND ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CONCAT(COALESCE(ZEROS_TO_NULL(CAST(BR_LADA AS STRING)), ''), COALESCE(ZEROS_TO_NULL(CAST(BR_TEL AS STRING)), '')), ''), r'\D', '')) IS NOT NULL

  UNION ALL
  SELECT 'APIA', CTA_CVE_ENTIDAD AS CTA_CVE, 'PHONE', 'CEL_ORIGEN',
         CASE WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL AS STRING), ''), r'\D', '')) IS NULL THEN NULL ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL AS STRING), ''), r'\D', '')), -10) END,
         CONCAT(TRIM(COALESCE(BR_NOM, '')), ' ', TRIM(COALESCE(BR_APE_PAT, '')), ' ', TRIM(COALESCE(BR_APE_MAT, ''))),
         TRIM(COALESCE(BR_APE_PAT, '')), COALESCE(CAST(BR_CDP AS STRING), '')
  FROM APIA_RESUELTO
  WHERE CTA_CVE_ENTIDAD IS NOT NULL AND CTA_CVE_ENTIDAD != 0 AND CASE WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL AS STRING), ''), r'\D', '')) IS NULL THEN NULL ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL AS STRING), ''), r'\D', '')), -10) END IS NOT NULL

  UNION ALL
  SELECT 'APIA', CTA_CVE_ENTIDAD AS CTA_CVE, 'PHONE', 'TEL_REF1_ORIGEN',
         CASE
           WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_TEL_REF1 AS STRING), ''), r'\D', '')) IS NULL THEN NULL
           WHEN SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_TEL_REF1 AS STRING), ''), r'\D', '')), -10) IN ('5555555555','5500000000','45','9510000000','5000000000','3300000000','6180000000','4490000000','3510000000','8100000000','550000000','3110000000','6120000000','4430000000','2299000000','4770000000','8440000000','1111111111','300000000') THEN NULL
           ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_TEL_REF1 AS STRING), ''), r'\D', '')), -10)
         END,
         CONCAT(TRIM(COALESCE(BR_NOM, '')), ' ', TRIM(COALESCE(BR_APE_PAT, '')), ' ', TRIM(COALESCE(BR_APE_MAT, ''))),
         TRIM(COALESCE(BR_APE_PAT, '')), COALESCE(CAST(BR_CDP AS STRING), '')
  FROM APIA_RESUELTO
  WHERE CTA_CVE_ENTIDAD IS NOT NULL AND CTA_CVE_ENTIDAD != 0 AND ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_TEL_REF1 AS STRING), ''), r'\D', '')) IS NOT NULL

  UNION ALL
  SELECT 'APIA', CTA_CVE_ENTIDAD AS CTA_CVE, 'PHONE', 'TEL_REF2_ORIGEN',
         CASE
           WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_TEL_REF2 AS STRING), ''), r'\D', '')) IS NULL THEN NULL
           WHEN SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_TEL_REF2 AS STRING), ''), r'\D', '')), -10) IN ('5555555555','5500000000','45','9510000000','5000000000','3300000000','6180000000','4490000000','3510000000','8100000000','550000000','3110000000','6120000000','4430000000','2299000000','4770000000','8440000000','1111111111','300000000') THEN NULL
           ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_TEL_REF2 AS STRING), ''), r'\D', '')), -10)
         END,
         CONCAT(TRIM(COALESCE(BR_NOM, '')), ' ', TRIM(COALESCE(BR_APE_PAT, '')), ' ', TRIM(COALESCE(BR_APE_MAT, ''))),
         TRIM(COALESCE(BR_APE_PAT, '')), COALESCE(CAST(BR_CDP AS STRING), '')
  FROM APIA_RESUELTO
  WHERE CTA_CVE_ENTIDAD IS NOT NULL AND CTA_CVE_ENTIDAD != 0 AND ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_TEL_REF2 AS STRING), ''), r'\D', '')) IS NOT NULL

  UNION ALL
  SELECT 'APIA', CTA_CVE_ENTIDAD AS CTA_CVE, 'PHONE', 'CEL_REF1_ORIGEN',
         CASE
           WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL_REF1 AS STRING), ''), r'\D', '')) IS NULL THEN NULL
           WHEN SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL_REF1 AS STRING), ''), r'\D', '')), -10) IN ('5555555555','5500000000','45','9510000000','5000000000','3300000000','6180000000','4490000000','3510000000','8100000000','550000000','3110000000','6120000000','4430000000','2299000000','4770000000','8440000000','1111111111','300000000') THEN NULL
           ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL_REF1 AS STRING), ''), r'\D', '')), -10)
         END,
         CONCAT(TRIM(COALESCE(BR_NOM, '')), ' ', TRIM(COALESCE(BR_APE_PAT, '')), ' ', TRIM(COALESCE(BR_APE_MAT, ''))),
         TRIM(COALESCE(BR_APE_PAT, '')), COALESCE(CAST(BR_CDP AS STRING), '')
  FROM APIA_RESUELTO
  WHERE CTA_CVE_ENTIDAD IS NOT NULL AND CTA_CVE_ENTIDAD != 0 AND ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL_REF1 AS STRING), ''), r'\D', '')) IS NOT NULL

  UNION ALL
  SELECT 'APIA', CTA_CVE_ENTIDAD AS CTA_CVE, 'PHONE', 'CEL_REF2_ORIGEN',
         CASE
           WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL_REF2 AS STRING), ''), r'\D', '')) IS NULL THEN NULL
           WHEN SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL_REF2 AS STRING), ''), r'\D', '')), -10) IN ('5555555555','5500000000','45','9510000000','5000000000','3300000000','6180000000','4490000000','3510000000','8100000000','550000000','3110000000','6120000000','4430000000','2299000000','4770000000','8440000000','1111111111','300000000') THEN NULL
           ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL_REF2 AS STRING), ''), r'\D', '')), -10)
         END,
         CONCAT(TRIM(COALESCE(BR_NOM, '')), ' ', TRIM(COALESCE(BR_APE_PAT, '')), ' ', TRIM(COALESCE(BR_APE_MAT, ''))),
         TRIM(COALESCE(BR_APE_PAT, '')), COALESCE(CAST(BR_CDP AS STRING), '')
  FROM APIA_RESUELTO
  WHERE CTA_CVE_ENTIDAD IS NOT NULL AND CTA_CVE_ENTIDAD != 0 AND ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(BR_CEL_REF2 AS STRING), ''), r'\D', '')) IS NOT NULL
),
KEY_DEGREE AS (
  SELECT K_TYPE, K_VAL, COUNT(DISTINCT CTA_CVE) AS DEGREE_CNT
  FROM RAW_KEYS
  GROUP BY K_TYPE, K_VAL
)
SELECT
  R.SRC,
  R.CTA_CVE,
  R.K_TYPE,
  R.K_FIELD,
  R.K_VAL,
  R.NOMBRE,
  R.APE_PAT,
  R.CDP_CVE,
  D.DEGREE_CNT,
  IF(D.DEGREE_CNT > 35, TRUE, FALSE) AS ES_SUPERNODO
FROM RAW_KEYS AS R
INNER JOIN KEY_DEGREE AS D
  ON R.K_TYPE = D.K_TYPE AND R.K_VAL = D.K_VAL;

CREATE SEARCH INDEX IF NOT EXISTS IDX_SEARCH_BFS_CONTACT_KEYS
ON `crp-pro-dominio-negfin.mus_pro_prevfrau_wrk_tbls.STG_BFS_CONTACT_KEYS`(K_VAL);
