CREATE TEMP FUNCTION ZEROS_TO_NULL(s STRING) AS (
  CASE
    WHEN s IS NULL THEN NULL
    WHEN TRIM(s) = "" THEN NULL
    WHEN REGEXP_CONTAINS(TRIM(s), r"^0+$") THEN NULL
    ELSE TRIM(s)
  END
);

CREATE TEMP FUNCTION NORM_KEY10(x STRING) AS (
  SUBSTR(UPPER(REGEXP_REPLACE(TRIM(IFNULL(x, "")), r'[^A-Z0-9]', "")), 1, 10)
);

CREATE TEMP FUNCTION NORM_CURP18(x STRING) AS (
  SUBSTR(UPPER(REGEXP_REPLACE(TRIM(IFNULL(x, "")), r'[^A-Z0-9]', "")), 1, 18)
);

CREATE TEMP FUNCTION IS_CURP18(x STRING) AS (
  REGEXP_CONTAINS(x, r'^[A-Z]{4}[0-9]{6}[A-Z0-9]{8}$')
);

CREATE TEMP FUNCTION IS_CURP10(x STRING) AS (
  REGEXP_CONTAINS(x, r'^[A-Z]{4}[0-9]{6}$')
);

CREATE TEMP FUNCTION NORM_EMAIL(s STRING) AS (
  NULLIF(TRIM(LOWER(s)), '')
);

CREATE TEMP FUNCTION NORM_PHONE(s STRING) AS (
  CASE
    WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(s, ''), r'\D', '')) IS NULL THEN NULL
    ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(s, ''), r'\D', '')), -10)
  END
);

CREATE TEMP FUNCTION NORM_REF_PHONE(s STRING) AS (
  CASE
    WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(s, ''), r'\D', '')) IS NULL THEN NULL
    WHEN SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(s, ''), r'\D', '')), -10) IN (
      '5555555555', '5500000000', '45', '9510000000', '5000000000',
      '3300000000', '6180000000', '4490000000', '3510000000', '8100000000',
      '550000000', '3110000000', '6120000000', '4430000000', '2299000000',
      '4770000000', '8440000000', '1111111111', '300000000'
    ) THEN NULL
    ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(s, ''), r'\D', '')), -10)
  END
);

CREATE OR REPLACE TABLE `crp-pro-dominio-negfin.mus_pro_prevfrau_wrk_tbls.STG_BFS_CUSTOMER_KEYS`
CLUSTER BY K_TYPE, K_VAL, ID_CUSTOMERS AS
SELECT CAST(ID_CUSTOMERS AS STRING) AS ID_CUSTOMERS, MED AS MON_DIG, FCH AS FCH_ALTA,
       CONCAT(TRIM(COALESCE(CTE_NOM, '')), ' ', TRIM(COALESCE(CTE_AP, '')), ' ', TRIM(COALESCE(CTE_AM, ''))) AS NOMBRE,
       TRIM(COALESCE(CTE_AP, '')) AS APE_PAT,
       'EMAIL' AS K_TYPE, 'EMAIL1' AS K_FIELD, NULLIF(TRIM(LOWER(USR)), '') AS K_VAL
FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_CUSTOMERS`
WHERE SAFE_CAST(ID_CUSTOMERS AS NUMERIC) > 0 AND NULLIF(TRIM(LOWER(USR)), '') IS NOT NULL

UNION ALL
SELECT CAST(ID_CUSTOMERS AS STRING), MED, FCH,
       CONCAT(TRIM(COALESCE(CTE_NOM, '')), ' ', TRIM(COALESCE(CTE_AP, '')), ' ', TRIM(COALESCE(CTE_AM, ''))),
       TRIM(COALESCE(CTE_AP, '')), 'EMAIL', 'EMAIL2', NULLIF(TRIM(LOWER(EMAIL)), '')
FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_CUSTOMERS`
WHERE SAFE_CAST(ID_CUSTOMERS AS NUMERIC) > 0 AND NULLIF(TRIM(LOWER(EMAIL)), '') IS NOT NULL

UNION ALL
SELECT CAST(ID_CUSTOMERS AS STRING), MED, FCH,
       CONCAT(TRIM(COALESCE(CTE_NOM, '')), ' ', TRIM(COALESCE(CTE_AP, '')), ' ', TRIM(COALESCE(CTE_AM, ''))),
       TRIM(COALESCE(CTE_AP, '')), 'EMAIL', 'EMAIL_AUTH0', NULLIF(TRIM(LOWER(EMAIL_AUTH0)), '')
FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_CUSTOMERS`
WHERE SAFE_CAST(ID_CUSTOMERS AS NUMERIC) > 0 AND NULLIF(TRIM(LOWER(EMAIL_AUTH0)), '') IS NOT NULL

UNION ALL
SELECT CAST(ID_CUSTOMERS AS STRING), MED, FCH,
       CONCAT(TRIM(COALESCE(CTE_NOM, '')), ' ', TRIM(COALESCE(CTE_AP, '')), ' ', TRIM(COALESCE(CTE_AM, ''))),
       TRIM(COALESCE(CTE_AP, '')), 'PHONE', 'CEL_AUTH0',
       CASE WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_AUTH0 AS STRING), ''), r'\D', '')) IS NULL THEN NULL ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_AUTH0 AS STRING), ''), r'\D', '')), -10) END
FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_CUSTOMERS`
WHERE SAFE_CAST(ID_CUSTOMERS AS NUMERIC) > 0 AND CASE WHEN ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_AUTH0 AS STRING), ''), r'\D', '')) IS NULL THEN NULL ELSE SUBSTR(ZEROS_TO_NULL(REGEXP_REPLACE(COALESCE(CAST(CTE_TEL_AUTH0 AS STRING), ''), r'\D', '')), -10) END IS NOT NULL;

CREATE SEARCH INDEX IF NOT EXISTS IDX_SEARCH_BFS_CUSTOMER_KEYS
ON `crp-pro-dominio-negfin.mus_pro_prevfrau_wrk_tbls.STG_BFS_CUSTOMER_KEYS`(K_VAL);

