DECLARE FE_INI DATE DEFAULT DATE(2026,8,4);
DECLARE FE_FIN DATE DEFAULT DATE_SUB(CURRENT_DATE("America/Mexico_City"), INTERVAL 1 DAY);
DECLARE FE_REP DATE DEFAULT DATE(2026,8,4);

DECLARE CUR_ANIO INT64 DEFAULT EXTRACT(YEAR FROM FE_FIN);
DECLARE CUR_MES  INT64 DEFAULT EXTRACT(MONTH FROM FE_FIN);

DECLARE MAX_SAME_DAY_MIN INT64 DEFAULT 60;
DECLARE HR_OPEN INT64 DEFAULT 10;
DECLARE HR_CLOSE INT64 DEFAULT 23;

DECLARE UNICO STRING DEFAULT "ŠžŸÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖÙÚÛÜÝĀĂĄĆĈĊČĎĐĒĔĖĘĚĜĞĠĢĤĦĨĪĬĮİıĲĴĶĸĹĻĽĿŁŃŅŇŉŊŌŎŐŒŔŖŘŚŜŞŢŤŦŨŪŬŮŰŲŴŶŹŻſƒǺǼǾÆØÞ.!#$%&/()=?¡|'¿,:;@[]{}<>+*_-–—­^~´¨¸°ºª·•…‚„«»¬¢£€¥©®™§¶□�"; 
DECLARE ASCI STRING DEFAULT  "SSYAAAAAACEEEEIIIIDNOOOOOUUUUYAAACCCCDDEEEEEGGGGHHIIIIIIJJKKLLLLLNNNNNOOOERRRSSSTTTUUUUUUWYZZFFAOOOOP";

-- ============================================================
-- HELPERS
-- ============================================================
CREATE TEMP FUNCTION ZEROS_TO_NULL(s STRING) AS (
  CASE
    WHEN s IS NULL THEN NULL
    WHEN TRIM(s) = "" THEN NULL
    WHEN REGEXP_CONTAINS(TRIM(s), r"^0+$") THEN NULL
    ELSE TRIM(s)
  END
);
CREATE TEMP FUNCTION NORM_KEY10(x STRING) AS (
  SUBSTR(UPPER(REGEXP_REPLACE(TRIM(IFNULL(x, "")), r'[^A-Z0-9]', "")), 1, 10)
);
CREATE TEMP FUNCTION NORM_CURP18(x STRING) AS (
  SUBSTR(UPPER(REGEXP_REPLACE(TRIM(IFNULL(x, "")), r'[^A-Z0-9]', "")), 1, 18)
);
CREATE TEMP FUNCTION IS_CURP18(x STRING) AS (
  REGEXP_CONTAINS(x, r'^[A-Z]{4}[0-9]{6}[A-Z0-9]{8}$')
);
CREATE TEMP FUNCTION IS_CURP10(x STRING) AS (
  REGEXP_CONTAINS(x, r'^[A-Z]{4}[0-9]{6}$')
);
CREATE TEMP FUNCTION NORM_TDA_NUM(x STRING) AS (
  SAFE_CAST(REGEXP_EXTRACT(CAST(x AS STRING), r'\d+') AS INT64)
);

-- ============================================================
-- INPUT TABLES
-- ============================================================

CREATE TEMP TABLE UNIV_INI AS (
  WITH 
  UNIV_INI_AUX AS (
    SELECT
      B.TIP_INF AS TIP_INF, A.CTE_CVE_UNICO, A.CTE_CVE, A.CTA_CVE, A.TRJ_NUM,
      A.IND_TIT, A.NUM_CONSECUTIVO_TRJ AS TRJ_SEQ, 
      A.TRJ_EDO_CVE, A.BLQ_TRJ_CVE, A.RAZON_BLQ_TRJ_CVE,
      IF(A.FCH_ALTA_TRJ IN (DATE(9999,12,31), DATE(1900,01,01)), NULL, A.FCH_ALTA_TRJ) AS FCH_ALTA_TRJ, 
      IF(A.FCH_EMB_TRJ IN (DATE(9999,12,31), DATE(1900,01,01)), NULL, A.FCH_EMB_TRJ) AS FCH_EMB_TRJ,
      IF(A.FCH_BLQ_TRJ IN (DATE(9999,12,31), DATE(1900,01,01)), NULL, A.FCH_BLQ_TRJ) AS FCH_BLQ_TRJ, 
    FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ` AS A
    LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA` AS B
      ON (A.CTA_CVE = B.CTA_CVE)
    WHERE TRUE
      AND TRUNC(TRJ_NUM / 10000000000) NOT IN (479438, 421017)
      AND SAFE_CAST(IND_TIT AS NUMERIC) = 0
      AND 
      (
        (FCH_ALTA_TRJ BETWEEN FE_INI AND FE_FIN)
        OR (FCH_EMB_TRJ BETWEEN FE_INI AND FE_FIN)
        OR (FCH_BLQ_TRJ BETWEEN FE_INI AND FE_FIN)
      )
  ),
  EMBOZADAS AS (
    SELECT DISTINCT  
      SAFE_CAST(TRJ AS NUMERIC) AS TRJ, 
      SAFE_CAST(CTA_CVE AS NUMERIC) AS CTA_CVE,
      TIP_INF,
      USR AS USR_VPL_R05, 
      FCH_MOV AS FCH_MOV_R05,  
      HRA_MOV AS HRA_MOV_R05
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_EMBOSSER_MD_R05`
    WHERE TRUE
      AND FCH_MOV <= FE_FIN
      AND UPPER(TRIM(COD_DESC)) IN ('* NEW RECORD ADDED *','USER 5','USER 8','TEMP EMBOSSING NBR','ISSUE FLAG','EMBOSSER NAME 1','EMBOSSED NAME 1')
    QUALIFY ROW_NUMBER() OVER( PARTITION BY SAFE_CAST(TRJ AS NUMERIC) ORDER BY FCH_MOV, HRA_MOV) = 1
    ORDER BY FCH_MOV_R05 ,HRA_MOV_R05 NULLS LAST
  ),
  CREACIONES_TRJ AS (
    SELECT DISTINCT 
      IF(LENGTH(TRIM(CTE_CVE)) = 16, CTE_CVE, CONCAT(SAFE_CAST(CTE_CVE AS NUMERIC), LPAD(CONCAT(SAFE_CAST(FLG1 AS NUMERIC)),2, '0'))) AS TRJ, 
      CTE_CVE AS CTE_CVE_R09, FLG1, USR AS USR_VPL_CREA,
      FCH AS FCH_MOV_R09, HRA AS HRA_MOV_R09,
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_R09`
    WHERE TRUE
      AND FCH <= FE_FIN 
      AND UPPER(TRIM(DES)) IN ('* NEW RECORD ADDED *')
      AND SAFE_CAST(FLG1 AS NUMERIC) IS NOT NULL
      QUALIFY ROW_NUMBER() OVER( PARTITION BY IF(LENGTH(TRIM(CTE_CVE)) = 16,CTE_CVE,CONCAT(SAFE_CAST(CTE_CVE AS NUMERIC), LPAD(CONCAT(SAFE_CAST(FLG1 AS NUMERIC)), 2, '0'))) ORDER BY FCH,HRA NULLS LAST) = 1
  ),
  PREVIO AS (
    SELECT 
      A.TIP_INF AS TIP_INF_R, A.CTE_CVE_UNICO, A.CTA_CVE, A.TRJ_NUM, A.TRJ_EDO_CVE, A.BLQ_TRJ_CVE, A.RAZON_BLQ_TRJ_CVE,
      C.FCH_MOV_R05,C.HRA_MOV_R05,
      B.FCH_MOV_R09,B.HRA_MOV_R09,
      A.FCH_EMB_TRJ, A.FCH_ALTA_TRJ, A.FCH_BLQ_TRJ,
      CASE 
        WHEN A.FCH_EMB_TRJ IS NOT NULL THEN FCH_EMB_TRJ
        WHEN A.FCH_EMB_TRJ IS NULL AND A.TIP_INF = 110 AND A.TRJ_SEQ = 1 THEN FCH_ALTA_TRJ
        WHEN A.FCH_EMB_TRJ IS NULL AND A.TIP_INF = 110 AND A.TRJ_SEQ <> 1 THEN FCH_BLQ_TRJ
        WHEN A.FCH_EMB_TRJ IS NULL AND A.TIP_INF <> 110 AND A.CTA_CVE = A.TRJ_NUM THEN FCH_ALTA_TRJ
        WHEN A.FCH_EMB_TRJ IS NULL AND A.TIP_INF <> 110 AND A.CTA_CVE <> A.TRJ_NUM THEN FCH_BLQ_TRJ
      END FCH_TRJ_MOD,
      C.USR_VPL_R05,B.USR_VPL_CREA
    FROM UNIV_INI_AUX AS A
    LEFT JOIN CREACIONES_TRJ AS B
      ON (A.TRJ_NUM=SAFE_CAST(B.TRJ AS NUMERIC))
    LEFT JOIN EMBOZADAS C
      ON (A.TRJ_NUM=SAFE_CAST(C.TRJ AS NUMERIC))
  ),
  BASE AS (
    SELECT 
      *,
      COALESCE(FCH_MOV_R05,FCH_MOV_R09,FCH_EMB_TRJ,FCH_TRJ_MOD) FCH_REP,
      COALESCE(HRA_MOV_R05,HRA_MOV_R09,NULL) HRA_REP,
      CASE WHEN FCH_MOV_R05 IS NOT NULL OR FCH_EMB_TRJ IS NOT NULL THEN 1 ELSE 0 END FLG_EMBO
    FROM PREVIO
    WHERE COALESCE(HRA_MOV_R05,HRA_MOV_R09,NULL) IS NOT NULL
  )
  SELECT *
  FROM BASE
  WHERE TRUE 
    AND FCH_REP >= FE_INI
  QUALIFY ROW_NUMBER() OVER( PARTITION BY CTA_CVE, FCH_REP ORDER BY FCH_REP,FLG_EMBO DESC,HRA_REP DESC)=1
);
CREATE TEMP TABLE UNIV AS (
  WITH
  UNIV_PRTNCIA AS (
    SELECT 
      A.CODIGO_ACCION, A.NUMERO_CUENTA AS CTA_CVE,
      COALESCE(B.TRJ_NUM, A.NUMERO_TARJETA) AS TRJ_NUM, A.TIENDA_AUTENTICACION AS TDA_ATENCION, A.ID AS ID_ATENCION,
      A.FECHA, A.HORA, TRIM(UPPER(CORREO_ELECTRONICO)) AS EMAIL, CAST(SUBSTR(CAST(NUMERO_CELULAR AS STRING), -10) AS NUMERIC) AS CEL
    FROM `MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_PRTNCIA_DATOS` AS A
    INNER JOIN (SELECT DISTINCT CTA_CVE, TRJ_NUM, FCH_REP FROM UNIV_INI) AS B
      ON
        A.NUMERO_CUENTA = B.CTA_CVE 
        AND (A.FECHA = B.FCH_REP)
    WHERE TRUE
      AND TRIM(A.CODIGO_ACCION) IN ("EMBO", "TPRO", "VALE", "REPO") 
    QUALIFY ROW_NUMBER() OVER (PARTITION BY FECHA, TRJ_NUM ORDER BY FECHA DESC, HORA DESC) = 1 
  ),
  UNIV_PRTNCIA_AGG_TRJ AS (
    SELECT
      CTA_CVE, TRJ_NUM,
      COUNT(1) AS CNT_PRTNCIA,
      STRING_AGG(
        FORMAT(
          '%s %s | ACC=%s | CTA=%s | TDA=%s\nID=%s | EMAIL=%s | CEL=%s',
          FORMAT_DATE('%F', FECHA),
          COALESCE(CAST(HORA AS STRING), ''),
          COALESCE(CODIGO_ACCION, ''),
          COALESCE(CAST(CTA_CVE AS STRING), ''),
          COALESCE(CAST(TDA_ATENCION AS STRING), ''),
          COALESCE(CAST(ID_ATENCION AS STRING), ''),
          COALESCE(EMAIL, ''),
          COALESCE(CAST(CEL AS STRING), '')
        ),
        '\n'
        ORDER BY FECHA DESC, HORA DESC
      ) AS LOG_PRTNCIA
    FROM UNIV_PRTNCIA
    GROUP BY CTA_CVE, TRJ_NUM
  ),
  UNIV_PRTNCIA_AGG_CTA AS (
    SELECT
      CTA_CVE,
      COUNT(1) AS CNT_PRTNCIA,
      STRING_AGG(
        FORMAT(
          'TRJ_NUM=%s | %s %s | ACC=%s | CTA=%s | TDA=%s\nID=%s | EMAIL=%s | CEL=%s',
          COALESCE(CAST(TRJ_NUM AS STRING), ''),
          FORMAT_DATE('%F', FECHA),
          COALESCE(CAST(HORA AS STRING), ''),
          COALESCE(CODIGO_ACCION, ''),
          COALESCE(CAST(CTA_CVE AS STRING), ''),
          COALESCE(CAST(TDA_ATENCION AS STRING), ''),
          COALESCE(CAST(ID_ATENCION AS STRING), ''),
          COALESCE(EMAIL, ''),
          COALESCE(CAST(CEL AS STRING), '')
        ),
        '\n'
        ORDER BY FECHA DESC, HORA DESC
      ) AS LOG_PRTNCIA
    FROM UNIV_PRTNCIA
    GROUP BY CTA_CVE
  ),
  UNIV_VPL AS (
    SELECT DISTINCT
      A.CTA_CVE,
      CONCAT(
        TRIM(COALESCE(CTE_NOM, "")), " ",
        TRIM(COALESCE(CTE_APE_PAT, "")), " ",
        TRIM(COALESCE(CTE_APE_MAT, ""))
      ) AS NOMBRE,
      IF(REGEXP_CONTAINS(TRIM(CTE_CVE_RFC), r"^0+"), NULL, SUBSTR(TRIM(CTE_CVE_RFC), 1, 13)) AS CTE_CVE_RFC,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL AS STRING)), -10) AS NUMERIC) AS TEL,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_CEL AS STRING)), -10) AS NUMERIC) AS CEL,
      UPPER(TRIM(CTE_EMA)) AS EMAIL,
      CONCAT(
        TRIM(COALESCE(CTE_DES_DIR_UNO, "")), ", ",
        TRIM(COALESCE(CTE_DES_DIR_DOS, "")), ", ",
        COALESCE(CAST(CDP_CVE AS STRING), ""), ", ",
        TRIM(COALESCE(CTE_DES_CIU, ""))
      ) AS DIRECCION,
      SAFE_CAST(CDP_CVE AS STRING) AS CDP_CVE,
      SEX_CVE AS SEXO,
      CTE_FCH_NAC AS FCH_NAC,
      CTE_FCH_ALT AS FCH_APERTURA,
      TRIM(CTE_EMPR) AS EMPLEO,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL_OFI AS STRING)), -10) AS NUMERIC) AS TEL_OFI,
      TRIM(CTE_CONYUGE) AS NOM_CONYUGE,
      TRIM(CTE_NOM_REFERENCIA1) AS NOM_REF1,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL_REFERENCIA1 AS STRING)), -10) AS NUMERIC) AS TEL_REF1,
      TRIM(CTE_NOM_REFERENCIA2) AS NOM_REF2,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL_REFERENCIA2 AS STRING)), -10) AS NUMERIC) AS TEL_REF2
    FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL` AS A
    INNER JOIN (
      SELECT DISTINCT CTA_CVE FROM UNIV_INI
    ) AS U
      ON A.CTA_CVE = U.CTA_CVE
  ),
  UNIV_SDO AS (
    SELECT
      CTA_CVE, BR_SOLIC_CVE, CTA_FCH_SOL, CTA_EDO_CVE, CTA_NIV_MOR, CTA_IMP_LIM_CRD, CTA_SDO_ACT, CTA_HIST_PAGOS, TDA_APE,
      CONCAT(CCR_CVE_BLQ_UNO, RAZON_BLQ_UNO_CVE) AS BLOQ1,
      CONCAT(CCR_CVE_BLQ_DOS, RAZON_BLQ_DOS_CVE) AS BLOQ2,
      CTA_DEV, CTA_PAG, CTA_IMP, BR_TIPO_3, TIP_INF
      
      FROM (
        SELECT
          A.CTA_CVE, NULLIF(A.BR_SOLIC_CVE, 0) AS BR_SOLIC_CVE, CTA_FCH_SOL, CTA_EDO_CVE, CTA_NIV_MOR,
          CCR_CVE_BLQ_UNO, RAZON_BLQ_UNO_CVE, CCR_CVE_BLQ_DOS, RAZON_BLQ_DOS_CVE,
          CTA_IMP_LIM_CRD, CTA_SDO_ACT, CTA_HIST_PAGOS, 
          SAFE_CAST(CTA_TDA_APE AS INT64) AS TDA_APE,
          CTA_IMP_DEV_LTD AS CTA_DEV, CTA_IMP_PAG_LTD AS CTA_PAG, CTA_IMP_MCMP_LTD AS CTA_IMP,
          SUBSTR(SAFE_CAST(BR_TIPO AS STRING), 1, 3) AS BR_TIPO_3,
          TIP_INF
        FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_SDO_CTA_MES` AS A
        INNER JOIN (
          SELECT DISTINCT CTA_CVE FROM UNIV_INI
        ) AS U
          ON A.CTA_CVE = U.CTA_CVE
        WHERE TRUE
          AND ANIO = CUR_ANIO
          AND MES = CUR_MES
      )
  ), 
  UNIV_FICO AS (
    SELECT 
      NULLIF(SAFE_CAST(A.BR_SOLIC_CVE AS NUMERIC), 0) AS BR_SOLIC_CVE, FCH_SOL, HRA_SOL,
      BRAND, CL,
      STT_FICO, STT_SIMP_FICO, TRIM(BR_RFC) AS FICO_RFC
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_REP_SOL_FICO` AS A
    INNER JOIN (SELECT DISTINCT BR_SOLIC_CVE FROM UNIV_SDO) AS U
      ON NULLIF(SAFE_CAST(A.BR_SOLIC_CVE AS NUMERIC), 0) = U.BR_SOLIC_CVE
  ),
  APIA_F AS (
    SELECT DISTINCT
      A.BR_SOLIC_CVE,
      TRIM(A.BR_CURP) AS APIA_CURP,
      TRIM(A.BR_RFC) AS APIA_RFC,
      SUBSTR(SAFE_CAST(A.BR_TIPO AS STRING), 1, 3) AS BR_TIPO_3,
      A.BR_ORG AS TIP_INF
    FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_APIA` AS A
    INNER JOIN (
      SELECT DISTINCT
        BR_SOLIC_CVE, BR_TIPO_3, TIP_INF
      FROM UNIV_SDO
      WHERE BR_SOLIC_CVE IS NOT NULL
    ) AS K
      ON A.BR_SOLIC_CVE = K.BR_SOLIC_CVE
      AND SUBSTR(SAFE_CAST(A.BR_TIPO AS STRING), 1, 3) = K.BR_TIPO_3
      AND SAFE_CAST(A.BR_ORG AS STRING) = SAFE_CAST(K.TIP_INF AS STRING)
  )
  SELECT 
    C.BR_SOLIC_CVE,
    A.*,
    B.* EXCEPT(CTA_CVE),
    C.* EXCEPT(CTA_CVE,BR_SOLIC_CVE, BR_TIPO_3, TIP_INF),
    D.* EXCEPT(BR_SOLIC_CVE),
    E.* EXCEPT(BR_SOLIC_CVE),
    IF(IFNULL(P.CNT_PRTNCIA, 0) > 0, 1, IF(IFNULL(PC.CNT_PRTNCIA, 0) > 0, 1, 0)) AS FLG_PRTNCIA_MATCH,
    COALESCE(P.LOG_PRTNCIA, PC.LOG_PRTNCIA) AS PRTNCIA_LOG
  FROM UNIV_INI AS A
  LEFT JOIN UNIV_PRTNCIA_AGG_TRJ AS P
    ON A.TRJ_NUM = P.TRJ_NUM
  LEFT JOIN UNIV_PRTNCIA_AGG_CTA AS PC
    ON A.CTA_CVE = PC.CTA_CVE
  LEFT JOIN UNIV_VPL AS B
    ON A.CTA_CVE = B.CTA_CVE
  LEFT JOIN UNIV_SDO AS C
    ON A.CTA_CVE = C.CTA_CVE
  LEFT JOIN UNIV_FICO AS D
    ON C.BR_SOLIC_CVE = D.BR_SOLIC_CVE
  LEFT JOIN APIA_F AS E
    ON C.BR_SOLIC_CVE = E.BR_SOLIC_CVE
);
CREATE TEMP TABLE BIO_KEYS AS (
  WITH CTA_SRC AS (
    SELECT DISTINCT
      CTA_CVE, NOMBRE, CTE_CVE_RFC, APIA_CURP, APIA_RFC, FICO_RFC
    FROM UNIV
  ),
  PRE AS (
    SELECT
      CTA_CVE,
      NORM_CURP18(CTE_CVE_RFC) AS K_CURP18_VPL,
      NORM_KEY10(CTE_CVE_RFC) AS K_KEY10_VPL,
      NORM_CURP18(APIA_CURP) AS K_CURP18_APIA,
      NORM_KEY10(APIA_RFC) AS K_KEY10_APIA,
      NORM_KEY10(FICO_RFC) AS K_KEY10_FICO,
      UPPER(TRANSLATE(TRIM(IFNULL(NOMBRE, "")), UNICO, ASCI)) AS K_NOM_N,
      CASE
        WHEN IS_CURP18(NORM_CURP18(CTE_CVE_RFC)) THEN SUBSTR(NORM_CURP18(CTE_CVE_RFC), 5, 6)
        WHEN IS_CURP18(NORM_CURP18(APIA_CURP)) THEN SUBSTR(NORM_CURP18(APIA_CURP), 5, 6)
        WHEN IS_CURP10(NORM_KEY10(CTE_CVE_RFC)) THEN SUBSTR(NORM_KEY10(CTE_CVE_RFC), 5, 6)
        ELSE NULL
      END AS DOB6
    FROM CTA_SRC
  )
  SELECT CTA_CVE, 'CURP' AS TYPE, 'VPL_CURP18' AS SRC, K_CURP18_VPL AS KEY_VAL, DOB6
  FROM PRE
  WHERE K_CURP18_VPL IS NOT NULL
    AND IS_CURP18(K_CURP18_VPL)

  UNION DISTINCT
  SELECT CTA_CVE, 'CURP' AS TYPE, 'APIA_CURP18' AS SRC, K_CURP18_APIA AS KEY_VAL, DOB6
  FROM PRE
  WHERE K_CURP18_APIA IS NOT NULL
    AND IS_CURP18(K_CURP18_APIA)

  UNION DISTINCT
  SELECT CTA_CVE, 'KEY10' AS TYPE, 'VPL_RFC10' AS SRC, K_KEY10_VPL AS KEY_VAL, DOB6
  FROM PRE
  WHERE K_KEY10_VPL IS NOT NULL

  UNION DISTINCT
  SELECT CTA_CVE, 'KEY10' AS TYPE, 'APIA_RFC10' AS SRC, K_KEY10_APIA AS KEY_VAL, DOB6
  FROM PRE
  WHERE K_KEY10_APIA IS NOT NULL

  UNION DISTINCT
  SELECT CTA_CVE, 'KEY10' AS TYPE, 'FICO_RFC10' AS SRC, K_KEY10_FICO AS KEY_VAL, DOB6
  FROM PRE
  WHERE K_KEY10_FICO IS NOT NULL

  UNION DISTINCT
  SELECT CTA_CVE, 'NAME_DOB' AS TYPE, 'VPL_NAME_DOB' AS SRC, K_NOM_N AS KEY_VAL, DOB6
  FROM PRE
  WHERE K_NOM_N IS NOT NULL
    AND DOB6 IS NOT NULL
);

CREATE TEMP TABLE BIO_ERN_KEYS AS (
  WITH KEY_CURP AS (
    SELECT DISTINCT
      KEY_VAL AS CURP18
    FROM BIO_KEYS
    WHERE TYPE = 'CURP'
  ),
  KEY_KEY10 AS (
    SELECT DISTINCT
      KEY_VAL AS KEY10
    FROM BIO_KEYS
    WHERE TYPE = 'KEY10'
  ),
  KEY_NAME_DOB AS (
    SELECT DISTINCT
      KEY_VAL AS NOM_N, DOB6
    FROM BIO_KEYS
    WHERE TYPE = 'NAME_DOB'
  ),
  PRE AS (
    SELECT DISTINCT
      DATETIME(E.FCH_ENR, E.HRA_ENR) AS TS_ENR,
      NORM_KEY10(E.CTE_CVE) AS KEY10,
      NORM_CURP18(E.CTE_CVE) AS CURP18,
      UPPER(TRANSLATE(
        TRIM(CONCAT(
          TRIM(IFNULL(E.CTE_NOM, "")), " ",
          TRIM(IFNULL(E.CTE_APE_PAT, "")), " ",
          TRIM(IFNULL(E.CTE_APE_MAT, ""))
        )),
        UNICO, ASCI
      )) AS NOM_N,
      IF(IS_CURP18(NORM_CURP18(E.CTE_CVE)), SUBSTR(NORM_CURP18(E.CTE_CVE), 5, 6), NULL) AS DOB6,
      IF(TRIM(E.ENR_FLG) = "", NULL, TRIM(E.ENR_FLG)) AS ENR_FLG,
      IF(TRIM(E.CURP_FLG) = "", NULL, TRIM(E.CURP_FLG)) AS CURP_FLG,
      IF(TRIM(E.INE_FLG) = "", NULL, TRIM(E.INE_FLG)) AS INE_FLG,
      E.IUB,
      E.INE_CVE_ELE,
      E.PASAPORTE_NUM
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_ENR_BIO_CTE` AS E
    WHERE E.FCH_ENR BETWEEN FE_INI AND FE_FIN
  ),
  FIL AS (
    SELECT
      TS_ENR, KEY10, CURP18, NOM_N, DOB6,
      ENR_FLG, CURP_FLG, INE_FLG, IUB,
      CASE 
          WHEN ((UPPER(INE_FLG) LIKE '%VERIFICACION EXITOSA%' OR UPPER(INE_FLG) LIKE '%PENDIENTE%' OR UPPER(INE_FLG) LIKE '%INESPERADO%') AND ENR_FLG LIKE '%SRV000%') THEN 'EXITOSO'
          WHEN (UPPER(INE_FLG) LIKE '%VERIFICACION EXITOSA%' AND ENR_FLG NOT LIKE '%SRV000%') THEN 'FALLIDO - SIN RIESGO'
          WHEN UPPER(INE_FLG) LIKE '%HUELLA NO HIT%' THEN 'FALLIDO'
          WHEN UPPER(INE_FLG) LIKE 'NO COINCIDEN DATOS DE LA CREDENCIAL - [La identificacion no esta vigente]' THEN 'FALLIDO - SIN RIESGO'
          WHEN UPPER(INE_FLG) LIKE '%MINUCIA%' THEN 'FALLIDO - MINUCIAS'
          WHEN UPPER(INE_FLG) LIKE '%[La identificacion no esta vigente] [Nombre no coincide][Apellido Paterno no coincide][Apellido Materno no coincide]%' THEN 'FALLIDO'
          WHEN UPPER(INE_FLG) NOT LIKE '%HUELLA NO HIT%' AND INE_FLG IS NOT NULL THEN 'FALLIDO - RIESGO'
          WHEN (UPPER(CURP_FLG) LIKE '%EXITOSO%' AND ENR_FLG LIKE '%SRV000%' AND INE_FLG IS NULL) THEN 'EXITOSO'
        ELSE 'REV'
      END AS FLG_EXI_TIP,
      CASE 
          WHEN ((UPPER(INE_FLG) LIKE '%VERIFICACION EXITOSA%' OR UPPER(INE_FLG) LIKE'%PENDIENTE%' OR UPPER(INE_FLG) LIKE "%INESPERADO%") AND ENR_FLG LIKE '%SRV000%') THEN 'EXITOSO'
          WHEN (UPPER(INE_FLG) LIKE '%VERIFICACION EXITOSA%' AND ENR_FLG NOT LIKE '%SRV000%') THEN 'EXITOSO'
          WHEN UPPER(INE_FLG) LIKE '%HUELLA NO HIT%' THEN 'FALLIDO'
          WHEN UPPER(INE_FLG) LIKE 'NO COINCIDEN DATOS DE LA CREDENCIAL - [La identificacion no esta vigente]' THEN 'EXITOSO' 
          WHEN UPPER(INE_FLG) LIKE '%MINUCIA%' THEN 'FALLIDO'
          WHEN UPPER(INE_FLG) LIKE '%[La identificacion no esta vigente] [Nombre no coincide][Apellido Paterno no coincide][Apellido Materno no coincide]%' THEN 'FALLIDO'
          WHEN UPPER(INE_FLG) NOT LIKE '%HUELLA NO HIT%' AND INE_FLG IS NOT NULL THEN 'EXITOSO'
          WHEN (UPPER (CURP_FLG) LIKE '%EXITOSO%' AND ENR_FLG LIKE '%SRV000%' AND INE_FLG IS NULL) THEN 'EXITOSO'
        ELSE 'REV' 
      END AS FLG_EXI
    FROM PRE
    WHERE CURP18 IN (SELECT CURP18 FROM KEY_CURP)
       OR KEY10 IN (SELECT KEY10 FROM KEY_KEY10)
       OR STRUCT(NOM_N, DOB6) IN (SELECT AS STRUCT NOM_N, DOB6 FROM KEY_NAME_DOB)
  )
  SELECT
    TS_ENR, FLG_EXI, FLG_EXI_TIP, ENR_FLG, CURP_FLG, INE_FLG, IUB,
    CURP18 AS ENR_CURP18,
    'CURP' AS TYPE, CURP18 AS KEY_VAL, '' AS KEY_DOB6
  FROM FIL
  WHERE CURP18 IS NOT NULL

  UNION ALL
  SELECT
    TS_ENR, FLG_EXI, FLG_EXI_TIP, ENR_FLG, CURP_FLG, INE_FLG, IUB,
    CURP18 AS ENR_CURP18,
    'KEY10' AS TYPE, KEY10 AS KEY_VAL, '' AS KEY_DOB6
  FROM FIL
  WHERE KEY10 IS NOT NULL

  UNION ALL
  SELECT
    TS_ENR, FLG_EXI, FLG_EXI_TIP, ENR_FLG, CURP_FLG, INE_FLG, IUB,
    CURP18 AS ENR_CURP18,
    'NAME_DOB' AS TYPE, NOM_N AS KEY_VAL, DOB6 AS KEY_DOB6
  FROM FIL
  WHERE NOM_N IS NOT NULL
    AND DOB6 IS NOT NULL
);
CREATE TEMP TABLE BIO_AUT_KEYS AS (
  WITH KEY_CURP AS (
    SELECT DISTINCT
      KEY_VAL AS CURP18
    FROM BIO_KEYS
    WHERE TYPE = 'CURP'
  ),
  KEY_KEY10 AS (
    SELECT DISTINCT
      KEY_VAL AS KEY10
    FROM BIO_KEYS
    WHERE TYPE = 'KEY10'
  ),
  KEY_NAME_DOB AS (
    SELECT DISTINCT
      KEY_VAL AS NOM_N, DOB6
    FROM BIO_KEYS
    WHERE TYPE = 'NAME_DOB'
  ),
  PRE AS (
    SELECT DISTINCT
      DATETIME(A.FCH_AUT, A.HRA_AUT) AS TS_AUT,
      NORM_KEY10(A.CTE_CVE) AS KEY10,
      NORM_CURP18(A.CTE_CVE) AS CURP18,
      UPPER(TRANSLATE(
        TRIM(CONCAT(
          TRIM(IFNULL(A.CTE_NOM, "")), " ",
          TRIM(IFNULL(A.CTE_APE_PAT, "")), " ",
          TRIM(IFNULL(A.CTE_APE_MAT, ""))
        )),
        UNICO, ASCI
      )) AS NOM_N,
      IF(IS_CURP18(NORM_CURP18(A.CTE_CVE)), SUBSTR(NORM_CURP18(A.CTE_CVE), 5, 6), NULL) AS DOB6,
      A.RESP_AUT
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_AUT_BIO_CTE` AS A
    WHERE A.FCH_AUT BETWEEN FE_INI AND FE_FIN
  ),
  FIL AS (
    SELECT
      TS_AUT, KEY10, CURP18, NOM_N, DOB6, RESP_AUT
    FROM PRE
    WHERE CURP18 IN (SELECT CURP18 FROM KEY_CURP)
       OR KEY10 IN (SELECT KEY10 FROM KEY_KEY10)
       OR STRUCT(NOM_N, DOB6) IN (SELECT AS STRUCT NOM_N, DOB6 FROM KEY_NAME_DOB)
  )
  SELECT
    TS_AUT, RESP_AUT,
    'CURP' AS TYPE, CURP18 AS KEY_VAL, '' AS KEY_DOB6
  FROM FIL
  WHERE CURP18 IS NOT NULL

  UNION ALL
  SELECT
    TS_AUT, RESP_AUT,
    'KEY10' AS TYPE, KEY10 AS KEY_VAL, '' AS KEY_DOB6
  FROM FIL
  WHERE KEY10 IS NOT NULL

  UNION ALL
  SELECT
    TS_AUT, RESP_AUT,
    'NAME_DOB' AS TYPE, NOM_N AS KEY_VAL, DOB6 AS KEY_DOB6
  FROM FIL
  WHERE NOM_N IS NOT NULL
    AND DOB6 IS NOT NULL
);

CREATE TEMP TABLE BIO_ERN_KEYS_HIST AS (
  WITH KEY_CURP AS (
    SELECT DISTINCT KEY_VAL AS CURP18
    FROM BIO_KEYS
    WHERE TYPE = 'CURP'
  ),
  KEY_KEY10 AS (
    SELECT DISTINCT KEY_VAL AS KEY10
    FROM BIO_KEYS
    WHERE TYPE = 'KEY10'
  ),
  KEY_NAME_DOB AS (
    SELECT DISTINCT KEY_VAL AS NOM_N, DOB6
    FROM BIO_KEYS
    WHERE TYPE = 'NAME_DOB'
  ),
  PRE AS (
    SELECT DISTINCT
      DATETIME(E.FCH_ENR, E.HRA_ENR) AS TS_ENR,
      NORM_KEY10(E.CTE_CVE) AS KEY10,
      NORM_CURP18(E.CTE_CVE) AS CURP18,
      UPPER(TRANSLATE(
        TRIM(CONCAT(
          TRIM(IFNULL(E.CTE_NOM, "")), " ",
          TRIM(IFNULL(E.CTE_APE_PAT, "")), " ",
          TRIM(IFNULL(E.CTE_APE_MAT, ""))
        )),
        UNICO, ASCI
      )) AS NOM_N,
      IF(IS_CURP18(NORM_CURP18(E.CTE_CVE)), SUBSTR(NORM_CURP18(E.CTE_CVE), 5, 6), NULL) AS DOB6
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_ENR_BIO_CTE` AS E
  ),
  FIL AS (
    SELECT
      TS_ENR, KEY10, CURP18, NOM_N, DOB6
    FROM PRE
    WHERE CURP18 IN (SELECT CURP18 FROM KEY_CURP)
       OR KEY10 IN (SELECT KEY10 FROM KEY_KEY10)
       OR STRUCT(NOM_N, DOB6) IN (SELECT AS STRUCT NOM_N, DOB6 FROM KEY_NAME_DOB)
  )
  SELECT
    TS_ENR,
    CURP18 AS ENR_CURP18,
    'CURP' AS TYPE, CURP18 AS KEY_VAL, '' AS KEY_DOB6
  FROM FIL
  WHERE CURP18 IS NOT NULL

  UNION ALL

  SELECT
    TS_ENR,
    CURP18 AS ENR_CURP18,
    'KEY10' AS TYPE, KEY10 AS KEY_VAL, '' AS KEY_DOB6
  FROM FIL
  WHERE KEY10 IS NOT NULL

  UNION ALL

  SELECT
    TS_ENR,
    CURP18 AS ENR_CURP18,
    'NAME_DOB' AS TYPE, NOM_N AS KEY_VAL, DOB6 AS KEY_DOB6
  FROM FIL
  WHERE NOM_N IS NOT NULL
    AND DOB6 IS NOT NULL
);

CREATE TEMP TABLE BIO_TRJ AS (
  WITH KEY_STATS AS (
    SELECT
      CTA_CVE, COUNT(1) AS CNT_KEYS
    FROM BIO_KEYS
    GROUP BY CTA_CVE
  ),
  BIO_OP AS (
    SELECT
      CONCAT(CAST(U.CTA_CVE AS STRING), '|', CAST(U.TRJ_NUM AS STRING)) AS ID_ROW,
      U.CTA_CVE,
      U.BLOQ2,
      IFNULL(S.CNT_KEYS, 0) AS CNT_KEYS,
      U.FCH_REP AS REF_FECHA,
      U.HRA_REP AS REF_HORA,
      'EXACTO_UNIV' AS REF_MODO,
      IF(EXTRACT(HOUR FROM U.HRA_REP) BETWEEN HR_OPEN AND HR_CLOSE, 1, 0) AS HAS_REF_IN_WINDOW,
      DATETIME(U.FCH_REP, U.HRA_REP) AS TS_REF,
      GREATEST(
        DATETIME(U.FCH_REP, TIME(HR_OPEN, 0, 0)),
        DATETIME_SUB(DATETIME(U.FCH_REP, U.HRA_REP), INTERVAL MAX_SAME_DAY_MIN MINUTE)
      ) AS TS_LOW,
      LEAST(
        DATETIME(U.FCH_REP, TIME(HR_CLOSE, 59, 59)),
        DATETIME_ADD(DATETIME(U.FCH_REP, U.HRA_REP), INTERVAL MAX_SAME_DAY_MIN MINUTE)
      ) AS TS_HIGH
    FROM (
      SELECT DISTINCT
        CTA_CVE, TRJ_NUM, FCH_REP, HRA_REP, BLOQ2
      FROM UNIV
      WHERE FCH_REP IS NOT NULL
        AND HRA_REP IS NOT NULL
    ) AS U
    LEFT JOIN KEY_STATS AS S
      ON U.CTA_CVE = S.CTA_CVE
  ),
  ROW_KEYS AS (
    SELECT
      O.ID_ROW, O.CTA_CVE, O.BLOQ2, O.CNT_KEYS,
      O.REF_FECHA, O.REF_HORA, O.REF_MODO,
      O.TS_REF, O.TS_LOW, O.TS_HIGH, O.HAS_REF_IN_WINDOW,
      K.TYPE, K.SRC, K.KEY_VAL, K.DOB6
    FROM BIO_OP AS O
    LEFT JOIN BIO_KEYS AS K
      ON O.CTA_CVE = K.CTA_CVE
  ),
  ENR_MET AS (
    SELECT
      B.ID_ROW, B.TYPE, B.SRC, B.KEY_VAL, B.DOB6,

      ARRAY_AGG(
        IF(
          E.TS_ENR BETWEEN B.TS_LOW AND B.TS_REF
          AND DATE(E.TS_ENR) = B.REF_FECHA,
          STRUCT(
            E.TS_ENR AS TS_ENR,
            E.FLG_EXI AS FLG_EXI,
            E.FLG_EXI_TIP AS FLG_EXI_TIP,
            E.INE_FLG AS INE_FLG,
            E.CURP_FLG AS CURP_FLG,
            E.ENR_FLG AS ENR_FLG,
            DATETIME_DIFF(B.TS_REF, E.TS_ENR, MINUTE) AS DIFF_MIN
          ),
          NULL
        )
        IGNORE NULLS
        ORDER BY E.TS_ENR DESC
        LIMIT 1
      )[SAFE_OFFSET(0)] AS ENR_BEFORE,

      ARRAY_AGG(
        IF(
          E.TS_ENR BETWEEN B.TS_LOW AND B.TS_REF
          AND DATE(E.TS_ENR) = B.REF_FECHA
          AND E.FLG_EXI = 'EXITOSO',
          STRUCT(
            E.TS_ENR AS TS_ENR,
            E.FLG_EXI AS FLG_EXI,
            E.FLG_EXI_TIP AS FLG_EXI_TIP,
            E.INE_FLG AS INE_FLG,
            E.CURP_FLG AS CURP_FLG,
            E.ENR_FLG AS ENR_FLG,
            DATETIME_DIFF(B.TS_REF, E.TS_ENR, MINUTE) AS DIFF_MIN
          ),
          NULL
        )
        IGNORE NULLS
        ORDER BY E.TS_ENR DESC
        LIMIT 1
      )[SAFE_OFFSET(0)] AS ENR_BEFORE_OK,

      ARRAY_AGG(
        IF(
          B.HAS_REF_IN_WINDOW = 1
          AND E.TS_ENR > B.TS_REF
          AND E.TS_ENR <= B.TS_HIGH
          AND DATE(E.TS_ENR) = B.REF_FECHA,
          STRUCT(
            E.TS_ENR AS TS_ENR,
            E.FLG_EXI AS FLG_EXI,
            E.FLG_EXI_TIP AS FLG_EXI_TIP,
            E.INE_FLG AS INE_FLG,
            E.CURP_FLG AS CURP_FLG,
            E.ENR_FLG AS ENR_FLG,
            DATETIME_DIFF(E.TS_ENR, B.TS_REF, MINUTE) AS DIFF_MIN
          ),
          NULL
        )
        IGNORE NULLS
        ORDER BY E.TS_ENR ASC
        LIMIT 1
      )[SAFE_OFFSET(0)] AS ENR_AFTER,

       ARRAY_AGG(
        IF(
          B.HAS_REF_IN_WINDOW = 1
          AND E.TS_ENR > B.TS_REF
          AND E.TS_ENR <= B.TS_HIGH
          AND DATE(E.TS_ENR) = B.REF_FECHA
          AND E.FLG_EXI = 'EXITOSO',
          STRUCT(
            E.TS_ENR AS TS_ENR,
            E.FLG_EXI AS FLG_EXI,
            E.FLG_EXI_TIP AS FLG_EXI_TIP,
            E.INE_FLG AS INE_FLG,
            E.CURP_FLG AS CURP_FLG,
            E.ENR_FLG AS ENR_FLG,
            DATETIME_DIFF(E.TS_ENR, B.TS_REF, MINUTE) AS DIFF_MIN
          ),
          NULL
        )
        IGNORE NULLS
        ORDER BY E.TS_ENR ASC
        LIMIT 1
      )[SAFE_OFFSET(0)] AS ENR_AFTER_OK,

     STRING_AGG(
        IF(
          E.TS_ENR BETWEEN B.TS_LOW AND B.TS_REF
          AND DATE(E.TS_ENR) = B.REF_FECHA,
          FORMAT(
            '%s %s [%s]',
            FORMAT_DATETIME('%H:%M', E.TS_ENR),
            E.FLG_EXI,
            E.FLG_EXI_TIP
          ),
          NULL
        ),
        ' > '
        ORDER BY E.TS_ENR ASC
        LIMIT 5
      ) AS ENR_BEFORE_PATH,

      STRING_AGG(
        IF(
          B.HAS_REF_IN_WINDOW = 1
          AND E.TS_ENR > B.TS_REF
          AND E.TS_ENR <= B.TS_HIGH
          AND DATE(E.TS_ENR) = B.REF_FECHA,
          FORMAT(
            '%s %s [%s]',
            FORMAT_DATETIME('%H:%M', E.TS_ENR),
            E.FLG_EXI,
            E.FLG_EXI_TIP
          ),
          NULL
        ),
        ' > '
        ORDER BY E.TS_ENR ASC
        LIMIT 5
      ) AS ENR_AFTER_PATH,

    COUNTIF(
      E.TS_ENR BETWEEN B.TS_LOW AND B.TS_REF
      AND DATE(E.TS_ENR) = B.REF_FECHA
    ) AS ENR_BEFORE_CNT,

    COUNTIF(
      E.TS_ENR BETWEEN B.TS_LOW AND B.TS_REF
      AND DATE(E.TS_ENR) = B.REF_FECHA
      AND E.FLG_EXI = 'EXITOSO'
    ) AS ENR_BEFORE_OK_CNT,

    COUNTIF(
      B.HAS_REF_IN_WINDOW = 1
      AND E.TS_ENR > B.TS_REF
      AND E.TS_ENR <= B.TS_HIGH
      AND DATE(E.TS_ENR) = B.REF_FECHA
    ) AS ENR_AFTER_CNT,

    COUNTIF(
      B.HAS_REF_IN_WINDOW = 1
      AND E.TS_ENR > B.TS_REF
      AND E.TS_ENR <= B.TS_HIGH
      AND DATE(E.TS_ENR) = B.REF_FECHA
      AND E.FLG_EXI = 'EXITOSO'
    ) AS ENR_AFTER_OK_CNT,

    FROM ROW_KEYS AS B
    LEFT JOIN BIO_ERN_KEYS AS E
      ON B.TYPE = E.TYPE
      AND B.KEY_VAL = E.KEY_VAL
      AND IF(B.TYPE = 'NAME_DOB', B.DOB6, '') = E.KEY_DOB6
    GROUP BY B.ID_ROW, B.TYPE, B.SRC, B.KEY_VAL, B.DOB6
  ),
  ENR_HIST_MET AS (
    SELECT
      B.ID_ROW, B.TYPE, B.SRC, B.KEY_VAL, B.DOB6,
      LOGICAL_OR(E.TS_ENR <= B.TS_REF) AS HAS_ENR_HIST_ANY,

      ARRAY_AGG(
        IF(
          E.TS_ENR <= B.TS_REF,
          STRUCT(
            E.TS_ENR AS TS_ENR,
            DATETIME_DIFF(B.TS_REF, E.TS_ENR, MINUTE) AS DIFF_MIN,
            DATETIME_DIFF(B.TS_REF, E.TS_ENR, DAY) AS DIFF_DAY
          ),
          NULL
        )
        IGNORE NULLS
        ORDER BY E.TS_ENR DESC
        LIMIT 1
      )[SAFE_OFFSET(0)] AS ENR_HIST_LAST_ANY
    FROM ROW_KEYS AS B
    LEFT JOIN BIO_ERN_KEYS_HIST AS E
      ON B.TYPE = E.TYPE
      AND B.KEY_VAL = E.KEY_VAL
      AND IF(B.TYPE = 'NAME_DOB', B.DOB6, '') = E.KEY_DOB6
    GROUP BY B.ID_ROW, B.TYPE, B.SRC, B.KEY_VAL, B.DOB6
  ),
  AUT_MET AS (
    SELECT
      B.ID_ROW, B.TYPE, B.SRC, B.KEY_VAL, B.DOB6,

      ARRAY_AGG(
        IF(
          A.TS_AUT BETWEEN B.TS_LOW AND B.TS_REF
          AND DATE(A.TS_AUT) = B.REF_FECHA,
          STRUCT(
            A.TS_AUT AS TS_AUT,
            A.RESP_AUT AS RESP_AUT,
            DATETIME_DIFF(B.TS_REF, A.TS_AUT, MINUTE) AS DIFF_MIN
          ),
          NULL
        )
        IGNORE NULLS
        ORDER BY A.TS_AUT DESC
        LIMIT 1
      )[SAFE_OFFSET(0)] AS AUT_BEFORE,

      ARRAY_AGG(
        IF(
          A.TS_AUT BETWEEN B.TS_LOW AND B.TS_REF
          AND DATE(A.TS_AUT) = B.REF_FECHA
          AND A.RESP_AUT = 'AUTENTICACION EXITOSA',
          STRUCT(
            A.TS_AUT AS TS_AUT,
            A.RESP_AUT AS RESP_AUT,
            DATETIME_DIFF(B.TS_REF, A.TS_AUT, MINUTE) AS DIFF_MIN
          ),
          NULL
        )
        IGNORE NULLS
        ORDER BY A.TS_AUT DESC
        LIMIT 1
      )[SAFE_OFFSET(0)] AS AUT_BEFORE_OK,

      ARRAY_AGG(
        IF(
          B.HAS_REF_IN_WINDOW = 1
          AND A.TS_AUT > B.TS_REF
          AND A.TS_AUT <= B.TS_HIGH
          AND DATE(A.TS_AUT) = B.REF_FECHA,
          STRUCT(
            A.TS_AUT AS TS_AUT,
            A.RESP_AUT AS RESP_AUT,
            DATETIME_DIFF(A.TS_AUT, B.TS_REF, MINUTE) AS DIFF_MIN
          ),
          NULL
        )
        IGNORE NULLS
        ORDER BY A.TS_AUT ASC
        LIMIT 1
      )[SAFE_OFFSET(0)] AS AUT_AFTER,

      ARRAY_AGG(
        IF(
          B.HAS_REF_IN_WINDOW = 1
          AND A.TS_AUT > B.TS_REF
          AND A.TS_AUT <= B.TS_HIGH
          AND DATE(A.TS_AUT) = B.REF_FECHA
          AND A.RESP_AUT = 'AUTENTICACION EXITOSA',
          STRUCT(
            A.TS_AUT AS TS_AUT,
            A.RESP_AUT AS RESP_AUT,
            DATETIME_DIFF(A.TS_AUT, B.TS_REF, MINUTE) AS DIFF_MIN
          ),
          NULL
        )
        IGNORE NULLS
        ORDER BY A.TS_AUT ASC
        LIMIT 1
      )[SAFE_OFFSET(0)] AS AUT_AFTER_OK,

      STRING_AGG(
        IF(
          A.TS_AUT BETWEEN B.TS_LOW AND B.TS_REF
          AND DATE(A.TS_AUT) = B.REF_FECHA,
          FORMAT(
            '%s %s',
            FORMAT_DATETIME('%H:%M', A.TS_AUT),
            A.RESP_AUT
          ),
          NULL
        ),
        ' > '
        ORDER BY A.TS_AUT ASC
        LIMIT 5
      ) AS AUT_BEFORE_PATH,

      STRING_AGG(
        IF(
          B.HAS_REF_IN_WINDOW = 1
          AND A.TS_AUT > B.TS_REF
          AND A.TS_AUT <= B.TS_HIGH
          AND DATE(A.TS_AUT) = B.REF_FECHA,
          FORMAT(
            '%s %s',
            FORMAT_DATETIME('%H:%M', A.TS_AUT),
            A.RESP_AUT
          ),
          NULL
        ),
        ' > '
        ORDER BY A.TS_AUT ASC
        LIMIT 5
      ) AS AUT_AFTER_PATH,

      COUNTIF(
        A.TS_AUT BETWEEN B.TS_LOW AND B.TS_REF
        AND DATE(A.TS_AUT) = B.REF_FECHA
      ) AS AUT_BEFORE_CNT,

      COUNTIF(
        A.TS_AUT BETWEEN B.TS_LOW AND B.TS_REF
        AND DATE(A.TS_AUT) = B.REF_FECHA
        AND A.RESP_AUT = 'AUTENTICACION EXITOSA'
      ) AS AUT_BEFORE_OK_CNT,

      COUNTIF(
        B.HAS_REF_IN_WINDOW = 1
        AND A.TS_AUT > B.TS_REF
        AND A.TS_AUT <= B.TS_HIGH
        AND DATE(A.TS_AUT) = B.REF_FECHA
      ) AS AUT_AFTER_CNT,

      COUNTIF(
        B.HAS_REF_IN_WINDOW = 1
        AND A.TS_AUT > B.TS_REF
        AND A.TS_AUT <= B.TS_HIGH
        AND DATE(A.TS_AUT) = B.REF_FECHA
        AND A.RESP_AUT = 'AUTENTICACION EXITOSA'
      ) AS AUT_AFTER_OK_CNT

    FROM ROW_KEYS AS B
    LEFT JOIN BIO_AUT_KEYS AS A
      ON B.TYPE = A.TYPE
      AND B.KEY_VAL = A.KEY_VAL
      AND IF(B.TYPE = 'NAME_DOB', B.DOB6, '') = A.KEY_DOB6
    GROUP BY B.ID_ROW, B.TYPE, B.SRC, B.KEY_VAL, B.DOB6
  ),
  KEY_STATUS_BASE AS (
    SELECT
      E.ID_ROW, E.TYPE, E.SRC, E.KEY_VAL, E.DOB6,
      O.BLOQ2,
      H.HAS_ENR_HIST_ANY,
      H.ENR_HIST_LAST_ANY,
      E.ENR_BEFORE, E.ENR_AFTER,

      E.ENR_BEFORE_CNT, E.ENR_BEFORE_OK_CNT,
      E.ENR_AFTER_CNT, E.ENR_AFTER_OK_CNT,
      E.ENR_BEFORE_PATH, E.ENR_AFTER_PATH,
      E.ENR_BEFORE_OK, E.ENR_AFTER_OK,

      A.AUT_BEFORE, A.AUT_AFTER,
      A.AUT_BEFORE_OK, A.AUT_AFTER_OK,
      A.AUT_BEFORE_CNT, A.AUT_BEFORE_OK_CNT,
      A.AUT_AFTER_CNT, A.AUT_AFTER_OK_CNT,
      A.AUT_BEFORE_PATH, A.AUT_AFTER_PATH,
      IF(
        E.ENR_BEFORE.TS_ENR IS NOT NULL
        OR E.ENR_AFTER.TS_ENR IS NOT NULL
        OR A.AUT_BEFORE.TS_AUT IS NOT NULL
        OR A.AUT_AFTER.TS_AUT IS NOT NULL,
        1,
        0
      ) AS FLG_BIO_REALIZADO
    FROM ENR_MET AS E
    LEFT JOIN ENR_HIST_MET AS H
      ON E.ID_ROW = H.ID_ROW
      AND E.TYPE = H.TYPE
      AND E.SRC = H.SRC
      AND E.KEY_VAL = H.KEY_VAL
      AND SAFE_CAST(E.DOB6 AS STRING) = SAFE_CAST(H.DOB6 AS STRING)
    LEFT JOIN AUT_MET AS A
      ON E.ID_ROW = A.ID_ROW
      AND E.TYPE = A.TYPE
      AND E.SRC = A.SRC
      AND E.KEY_VAL = A.KEY_VAL
      AND SAFE_CAST(E.DOB6 AS STRING) = SAFE_CAST(A.DOB6 AS STRING)
    LEFT JOIN (
      SELECT DISTINCT ID_ROW, BLOQ2
      FROM BIO_OP
    ) AS O
      ON E.ID_ROW = O.ID_ROW
  ),  
  KEY_STATUS AS (
    SELECT
      *,
      CASE
        WHEN FLG_BIO_REALIZADO = 0
          AND IFNULL(HAS_ENR_HIST_ANY, FALSE)
        THEN 'NO AUTENTICARON HUELLA (TENIA ENROLAMIENTO)'

        WHEN FLG_BIO_REALIZADO = 0
        THEN 'SIN REGISTRO'

        WHEN ENR_BEFORE_OK.TS_ENR IS NOT NULL
        THEN 'BIOMETRICO OK'

        WHEN AUT_BEFORE_OK.TS_AUT IS NOT NULL
        THEN 'BIOMETRICO OK'

        WHEN AUT_AFTER_OK.TS_AUT IS NOT NULL
          AND ENR_AFTER_OK.TS_ENR IS NOT NULL
          AND ENR_AFTER_OK.TS_ENR > AUT_AFTER_OK.TS_AUT
          AND NOT REGEXP_CONTAINS(IFNULL(BLOQ2, ''), r'F#')
        THEN 'REENROLA (EXITOSO)'

        WHEN AUT_AFTER_OK.TS_AUT IS NOT NULL
          AND ENR_AFTER_OK.TS_ENR IS NOT NULL
          AND ENR_AFTER_OK.TS_ENR > AUT_AFTER_OK.TS_AUT
          AND REGEXP_CONTAINS(IFNULL(BLOQ2, ''), r'F#')
        THEN 'REENROLA (NO EXITOSO)'

        WHEN AUT_AFTER_OK.TS_AUT IS NOT NULL
        THEN 'AUTENTICA DESPUES DEL EVENTO (EXITOSO)'

        WHEN ENR_AFTER_OK.TS_ENR IS NOT NULL
        THEN 'ENROLA DESPUES DEL EVENTO (EXITOSO)'

        WHEN ENR_BEFORE.TS_ENR IS NOT NULL
        THEN 'REGISTRO FALLIDO'

        WHEN AUT_BEFORE.TS_AUT IS NOT NULL
        THEN 'AUTENTICACION FALLIDA'

        WHEN AUT_AFTER.TS_AUT IS NOT NULL
          AND ENR_AFTER.TS_ENR IS NOT NULL
          AND ENR_AFTER.TS_ENR > AUT_AFTER.TS_AUT
          AND REGEXP_CONTAINS(IFNULL(BLOQ2, ''), r'F#')
        THEN 'REENROLA (NO EXITOSO)'

        WHEN AUT_AFTER.TS_AUT IS NOT NULL
        THEN 'AUTENTICA DESPUES DEL EVENTO (FALLIDO)'

        WHEN ENR_AFTER.TS_ENR IS NOT NULL
        THEN 'ENROLA DESPUES DEL EVENTO (FALLIDO)'

        ELSE 'SIN REGISTRO'
      END AS MATCH_BIO_STT,

      CASE
        WHEN FLG_BIO_REALIZADO = 0
          AND IFNULL(HAS_ENR_HIST_ANY, FALSE)
        THEN 10

        WHEN FLG_BIO_REALIZADO = 0
        THEN 11

        WHEN ENR_BEFORE_OK.TS_ENR IS NOT NULL
        THEN 1

        WHEN AUT_BEFORE_OK.TS_AUT IS NOT NULL
        THEN 1

        WHEN AUT_AFTER_OK.TS_AUT IS NOT NULL
          AND ENR_AFTER_OK.TS_ENR IS NOT NULL
          AND ENR_AFTER_OK.TS_ENR > AUT_AFTER_OK.TS_AUT
          AND NOT REGEXP_CONTAINS(IFNULL(BLOQ2, ''), r'F#')
        THEN 2

        WHEN AUT_AFTER_OK.TS_AUT IS NOT NULL
        THEN 3

        WHEN ENR_AFTER_OK.TS_ENR IS NOT NULL
        THEN 4

        WHEN ENR_BEFORE.TS_ENR IS NOT NULL
        THEN 5

        WHEN AUT_BEFORE.TS_AUT IS NOT NULL
        THEN 6

        WHEN AUT_AFTER.TS_AUT IS NOT NULL
          AND ENR_AFTER_OK.TS_ENR IS NOT NULL
          AND ENR_AFTER_OK.TS_ENR > AUT_AFTER.TS_AUT
          AND REGEXP_CONTAINS(IFNULL(BLOQ2, ''), r'F#')
        THEN 7

        WHEN AUT_AFTER.TS_AUT IS NOT NULL
        THEN 8

        WHEN ENR_AFTER.TS_ENR IS NOT NULL
        THEN 9

        ELSE 99
      END AS STT_ORD
    FROM KEY_STATUS_BASE
  ),
  BEST_PER_ROW AS (
    SELECT
      ID_ROW, FLG_BIO_REALIZADO, MATCH_BIO_STT, STT_ORD,
      TYPE, SRC, KEY_VAL, BLOQ2,

      ENR_BEFORE, AUT_BEFORE, ENR_BEFORE_OK, AUT_BEFORE_OK,
      ENR_AFTER_OK, AUT_AFTER_OK, AUT_AFTER, ENR_AFTER,

      ENR_BEFORE_CNT, ENR_BEFORE_OK_CNT,
      ENR_AFTER_CNT, ENR_AFTER_OK_CNT,
      ENR_BEFORE_PATH, ENR_AFTER_PATH,

      AUT_BEFORE_CNT, AUT_BEFORE_OK_CNT,
      AUT_AFTER_CNT, AUT_AFTER_OK_CNT,
      AUT_BEFORE_PATH, AUT_AFTER_PATH,

      HAS_ENR_HIST_ANY, ENR_HIST_LAST_ANY
    FROM KEY_STATUS
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY ID_ROW
      ORDER BY
        STT_ORD,
        CASE SRC
          WHEN 'FICO_RFC10' THEN 1
          WHEN 'APIA_RFC10' THEN 2
          WHEN 'VPL_RFC10' THEN 3
          WHEN 'VPL_CURP18' THEN 4
          WHEN 'APIA_CURP18' THEN 5
          ELSE 9
        END
    ) = 1
  )
  SELECT
    O.ID_ROW,

    IFNULL(B.FLG_BIO_REALIZADO, 0) AS FLG_BIO_REALIZADO,

    CASE
      WHEN IFNULL(B.FLG_BIO_REALIZADO, 0) = 1 THEN
        FORMAT(
          'FLG=1 | REF=%s %s | WND=[%s .. %s]',
          FORMAT_DATE('%F', O.REF_FECHA),
          CAST(O.REF_HORA AS STRING),
          COALESCE(FORMAT_DATETIME('%F %T', O.TS_LOW), ''),
          COALESCE(FORMAT_DATETIME('%F %T', O.TS_HIGH), '')
        )
      ELSE
        FORMAT(
          'FLG=0 | REF=%s %s | WND=[%s .. %s] | SIN_BIO_EN_VENTANA | REF_IN_HORARIO=%s | CNT_KEYS=%s | ENR_HIST_ANY=%s | ULT_ENR_HIST=%s | MIN_DESDE_ULT_ENR=%s | DIAS_DESDE_ULT_ENR=%s',
          FORMAT_DATE('%F', O.REF_FECHA),
          CAST(O.REF_HORA AS STRING),
          COALESCE(FORMAT_DATETIME('%F %T', O.TS_LOW), ''),
          COALESCE(FORMAT_DATETIME('%F %T', O.TS_HIGH), ''),
          CAST(O.HAS_REF_IN_WINDOW AS STRING),
          CAST(O.CNT_KEYS AS STRING),
          CAST(IFNULL(B.HAS_ENR_HIST_ANY, FALSE) AS STRING),
          COALESCE(FORMAT_DATETIME('%F %T', B.ENR_HIST_LAST_ANY.TS_ENR), ''),
          COALESCE(CAST(B.ENR_HIST_LAST_ANY.DIFF_MIN AS STRING), ''),
          COALESCE(CAST(B.ENR_HIST_LAST_ANY.DIFF_DAY AS STRING), '')
        )
    END AS TRJ_BIO_REALIZADO_LOG,

    IF(
      COALESCE(B.MATCH_BIO_STT, '') IN (
        'BIOMETRICO OK',
        'REENROLA (EXITOSO)',
        'AUTENTICA DESPUES DEL EVENTO (EXITOSO)',
        'ENROLA DESPUES DEL EVENTO (EXITOSO)'
      ),
      1,
      0
    ) AS TRJ_BIO_EXITOSO,

    B.MATCH_BIO_STT,

    IF(
      (
        B.AUT_BEFORE.TS_AUT IS NOT NULL
        AND DATE(B.AUT_BEFORE.TS_AUT) = O.REF_FECHA
        AND (
          EXTRACT(HOUR FROM B.AUT_BEFORE.TS_AUT) < HR_OPEN
          OR EXTRACT(HOUR FROM B.AUT_BEFORE.TS_AUT) > HR_CLOSE
        )
      )
      OR
      (
        B.AUT_AFTER.TS_AUT IS NOT NULL
        AND DATE(B.AUT_AFTER.TS_AUT) = O.REF_FECHA
        AND (
          EXTRACT(HOUR FROM B.AUT_AFTER.TS_AUT) < HR_OPEN
          OR EXTRACT(HOUR FROM B.AUT_AFTER.TS_AUT) > HR_CLOSE
        )
      ),
      1,
      NULL
    ) AS TRJ_BIO_AUT_FUERA_HORARIO,

    IF(
      (
        B.ENR_BEFORE.TS_ENR IS NOT NULL
        AND DATE(B.ENR_BEFORE.TS_ENR) = O.REF_FECHA
        AND (
          EXTRACT(HOUR FROM B.ENR_BEFORE.TS_ENR) < HR_OPEN
          OR EXTRACT(HOUR FROM B.ENR_BEFORE.TS_ENR) > HR_CLOSE
        )
      )
      OR
      (
        B.ENR_AFTER.TS_ENR IS NOT NULL
        AND DATE(B.ENR_AFTER.TS_ENR) = O.REF_FECHA
        AND (
          EXTRACT(HOUR FROM B.ENR_AFTER.TS_ENR) < HR_OPEN
          OR EXTRACT(HOUR FROM B.ENR_AFTER.TS_ENR) > HR_CLOSE
        )
      ),
      1,
      NULL
    ) AS TRJ_BIO_ENR_FUERA_HORARIO,

    ARRAY_TO_STRING(
      ARRAY(
        SELECT X
        FROM UNNEST([
          FORMAT(
            'STT=%s | DECISION=%s | REF=%s %s | WND=[%s .. %s] | KEY=%s/%s=%s | BLOQ2=%s | ENR_HIST_ANY=%s',
            COALESCE(B.MATCH_BIO_STT, ''),
            CASE
              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'BIOMETRICO OK'
                AND IFNULL(B.ENR_BEFORE_OK_CNT, 0) > 0
                AND COALESCE(B.ENR_BEFORE.FLG_EXI, '') != 'EXITOSO'
              THEN 'OK_POR_EXISTENCIA_DE_ENR_EXITOSO_EN_VENTANA_ANTES'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'ENROLA DESPUES DEL EVENTO (EXITOSO)'
                AND IFNULL(B.ENR_AFTER_OK_CNT, 0) > 0
                AND COALESCE(B.ENR_AFTER.FLG_EXI, '') != 'EXITOSO'
              THEN 'OK_POR_EXISTENCIA_DE_ENR_EXITOSO_EN_VENTANA_DESPUES'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'REENROLA (EXITOSO)'
                AND IFNULL(B.ENR_AFTER_OK_CNT, 0) > 0
                AND COALESCE(B.ENR_AFTER.FLG_EXI, '') != 'EXITOSO'
              THEN 'REENROLA_OK_POR_EXISTENCIA_DE_ENR_EXITOSO_POSTERIOR'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'AUTENTICA DESPUES DEL EVENTO (EXITOSO)'
              THEN 'AUT_POSTERIOR_EXITOSA'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'BIOMETRICO OK'
                AND IFNULL(B.AUT_BEFORE_OK_CNT, 0) > 0
                AND COALESCE(B.AUT_BEFORE.RESP_AUT, '') != 'AUTENTICACION EXITOSA'
              THEN 'OK_POR_EXISTENCIA_DE_AUT_EXITOSA_EN_VENTANA_ANTES'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'AUTENTICA DESPUES DEL EVENTO (EXITOSO)'
                AND IFNULL(B.AUT_AFTER_OK_CNT, 0) > 0
                AND COALESCE(B.AUT_AFTER.RESP_AUT, '') != 'AUTENTICACION EXITOSA'
              THEN 'OK_POR_EXISTENCIA_DE_AUT_EXITOSA_EN_VENTANA_DESPUES'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'REGISTRO FALLIDO'
                AND IFNULL(B.ENR_BEFORE_CNT, 0) > 0
                AND IFNULL(B.ENR_BEFORE_OK_CNT, 0) = 0
              THEN 'FALLIDO_SIN_ENR_EXITOSO_EN_VENTANA_ANTES'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'ENROLA DESPUES DEL EVENTO (FALLIDO)'
                AND IFNULL(B.ENR_AFTER_CNT, 0) > 0
                AND IFNULL(B.ENR_AFTER_OK_CNT, 0) = 0
              THEN 'FALLIDO_SIN_ENR_EXITOSO_EN_VENTANA_DESPUES'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'AUTENTICACION FALLIDA'
              THEN 'FALLIDO_POR_AUTENTICACION'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'AUTENTICA DESPUES DEL EVENTO (FALLIDO)'
              THEN 'AUT_POSTERIOR_FALLIDA'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'NO AUTENTICARON HUELLA (TENIA ENROLAMIENTO)'
              THEN 'SIN_BIO_EN_VENTANA_PERO_CON_ENROLAMIENTO_HISTORICO'

              WHEN COALESCE(B.MATCH_BIO_STT, '') = 'SIN REGISTRO'
              THEN 'SIN_BIO_Y_SIN_ENROLAMIENTO_EN_VENTANA'

              ELSE 'NORMAL'
            END,
            FORMAT_DATE('%F', O.REF_FECHA),
            CAST(O.REF_HORA AS STRING),
            COALESCE(FORMAT_DATETIME('%F %T', O.TS_LOW), ''),
            COALESCE(FORMAT_DATETIME('%F %T', O.TS_HIGH), ''),
            COALESCE(B.TYPE, ''),
            COALESCE(B.SRC, ''),
            COALESCE(B.KEY_VAL, ''),
            COALESCE(O.BLOQ2, ''),
            CAST(IFNULL(B.HAS_ENR_HIST_ANY, FALSE) AS STRING)
          ),

          IF(
            IFNULL(B.ENR_BEFORE_CNT, 0) > 0
            OR B.ENR_BEFORE_OK.TS_ENR IS NOT NULL
            OR COALESCE(B.ENR_BEFORE_PATH, '') != '',
            FORMAT(
              'ENR_BEF_CNT=%s | ENR_BEF_OK_CNT=%s%s%s%s',
              COALESCE(CAST(B.ENR_BEFORE_CNT AS STRING), '0'),
              COALESCE(CAST(B.ENR_BEFORE_OK_CNT AS STRING), '0'),

              IF(
                B.ENR_BEFORE.TS_ENR IS NOT NULL,
                FORMAT(
                  ' | ENR_BEF_NEAR=%s (%s)',
                  COALESCE(FORMAT_DATETIME('%F %T', B.ENR_BEFORE.TS_ENR), ''),
                  CASE
                    WHEN COALESCE(B.MATCH_BIO_STT, '') = 'REGISTRO FALLIDO' THEN
                      FORMAT(
                        '%s | %s | %s min | INE_FLG=%s | CURP_FLG=%s | ENR_FLG=%s',
                        COALESCE(B.ENR_BEFORE.FLG_EXI, ''),
                        COALESCE(B.ENR_BEFORE.FLG_EXI_TIP, ''),
                        COALESCE(CAST(B.ENR_BEFORE.DIFF_MIN AS STRING), ''),
                        COALESCE(B.ENR_BEFORE.INE_FLG, ''),
                        COALESCE(B.ENR_BEFORE.CURP_FLG, ''),
                        COALESCE(B.ENR_BEFORE.ENR_FLG, '')
                      )
                    ELSE
                      FORMAT(
                        '%s | %s | %s min',
                        COALESCE(B.ENR_BEFORE.FLG_EXI, ''),
                        COALESCE(B.ENR_BEFORE.FLG_EXI_TIP, ''),
                        COALESCE(CAST(B.ENR_BEFORE.DIFF_MIN AS STRING), '')
                      )
                  END
                ),
                ''
              ),

              IF(
                B.ENR_BEFORE_OK.TS_ENR IS NOT NULL,
                FORMAT(
                  ' | ENR_BEF_OK_REF=%s (%s)',
                  COALESCE(FORMAT_DATETIME('%F %T', B.ENR_BEFORE_OK.TS_ENR), ''),
                  FORMAT(
                    '%s | %s | %s min',
                    COALESCE(B.ENR_BEFORE_OK.FLG_EXI, ''),
                    COALESCE(B.ENR_BEFORE_OK.FLG_EXI_TIP, ''),
                    COALESCE(CAST(B.ENR_BEFORE_OK.DIFF_MIN AS STRING), '')
                  )
                ),
                ''
              ),

              IF(
                COALESCE(B.ENR_BEFORE_PATH, '') != '',
                FORMAT(' | ENR_BEF_PATH=[%s]', B.ENR_BEFORE_PATH),
                ''
              )
            ),
            NULL
          ),

          IF(
            IFNULL(B.AUT_BEFORE_CNT, 0) > 0
            OR B.AUT_BEFORE_OK.TS_AUT IS NOT NULL
            OR COALESCE(B.AUT_BEFORE_PATH, '') != '',
            FORMAT(
              'AUT_BEF_CNT=%s | AUT_BEF_OK_CNT=%s%s%s%s',
              COALESCE(CAST(B.AUT_BEFORE_CNT AS STRING), '0'),
              COALESCE(CAST(B.AUT_BEFORE_OK_CNT AS STRING), '0'),

              IF(
                B.AUT_BEFORE.TS_AUT IS NOT NULL,
                FORMAT(
                  ' | AUT_BEF_NEAR=%s (%s,%s)',
                  COALESCE(FORMAT_DATETIME('%F %T', B.AUT_BEFORE.TS_AUT), ''),
                  COALESCE(B.AUT_BEFORE.RESP_AUT, ''),
                  COALESCE(CAST(B.AUT_BEFORE.DIFF_MIN AS STRING), '')
                ),
                ''
              ),

              IF(
                B.AUT_BEFORE_OK.TS_AUT IS NOT NULL,
                FORMAT(
                  ' | AUT_BEF_OK_REF=%s (%s,%s)',
                  COALESCE(FORMAT_DATETIME('%F %T', B.AUT_BEFORE_OK.TS_AUT), ''),
                  COALESCE(B.AUT_BEFORE_OK.RESP_AUT, ''),
                  COALESCE(CAST(B.AUT_BEFORE_OK.DIFF_MIN AS STRING), '')
                ),
                ''
              ),

              IF(
                COALESCE(B.AUT_BEFORE_PATH, '') != '',
                FORMAT(' | AUT_BEF_PATH=[%s]', B.AUT_BEFORE_PATH),
                ''
              )
            ),
            NULL
          ),

          IF(
            IFNULL(B.AUT_AFTER_CNT, 0) > 0
            OR B.AUT_AFTER_OK.TS_AUT IS NOT NULL
            OR COALESCE(B.AUT_AFTER_PATH, '') != '',
            FORMAT(
              'AUT_AFT_CNT=%s | AUT_AFT_OK_CNT=%s%s%s%s',
              COALESCE(CAST(B.AUT_AFTER_CNT AS STRING), '0'),
              COALESCE(CAST(B.AUT_AFTER_OK_CNT AS STRING), '0'),

              IF(
                B.AUT_AFTER.TS_AUT IS NOT NULL,
                FORMAT(
                  ' | AUT_AFT_NEAR=%s (%s,%s)',
                  COALESCE(FORMAT_DATETIME('%F %T', B.AUT_AFTER.TS_AUT), ''),
                  COALESCE(B.AUT_AFTER.RESP_AUT, ''),
                  COALESCE(CAST(B.AUT_AFTER.DIFF_MIN AS STRING), '')
                ),
                ''
              ),

              IF(
                B.AUT_AFTER_OK.TS_AUT IS NOT NULL,
                FORMAT(
                  ' | AUT_AFT_OK_REF=%s (%s,%s)',
                  COALESCE(FORMAT_DATETIME('%F %T', B.AUT_AFTER_OK.TS_AUT), ''),
                  COALESCE(B.AUT_AFTER_OK.RESP_AUT, ''),
                  COALESCE(CAST(B.AUT_AFTER_OK.DIFF_MIN AS STRING), '')
                ),
                ''
              ),

              IF(
                COALESCE(B.AUT_AFTER_PATH, '') != '',
                FORMAT(' | AUT_AFT_PATH=[%s]', B.AUT_AFTER_PATH),
                ''
              )
            ),
            NULL
          ),

          IF(
            IFNULL(B.ENR_AFTER_CNT, 0) > 0
            OR B.ENR_AFTER_OK.TS_ENR IS NOT NULL
            OR COALESCE(B.ENR_AFTER_PATH, '') != '',
            FORMAT(
              'ENR_AFT_CNT=%s | ENR_AFT_OK_CNT=%s%s%s%s',
              COALESCE(CAST(B.ENR_AFTER_CNT AS STRING), '0'),
              COALESCE(CAST(B.ENR_AFTER_OK_CNT AS STRING), '0'),

              IF(
                B.ENR_AFTER.TS_ENR IS NOT NULL,
                FORMAT(
                  ' | ENR_AFT_NEAR=%s (%s | %s | %s min)',
                  COALESCE(FORMAT_DATETIME('%F %T', B.ENR_AFTER.TS_ENR), ''),
                  COALESCE(B.ENR_AFTER.FLG_EXI, ''),
                  COALESCE(B.ENR_AFTER.FLG_EXI_TIP, ''),
                  COALESCE(CAST(B.ENR_AFTER.DIFF_MIN AS STRING), '')
                ),
                ''
              ),

              IF(
                B.ENR_AFTER_OK.TS_ENR IS NOT NULL,
                FORMAT(
                  ' | ENR_AFT_OK_REF=%s (%s | %s | %s min)',
                  COALESCE(FORMAT_DATETIME('%F %T', B.ENR_AFTER_OK.TS_ENR), ''),
                  COALESCE(B.ENR_AFTER_OK.FLG_EXI, ''),
                  COALESCE(B.ENR_AFTER_OK.FLG_EXI_TIP, ''),
                  COALESCE(CAST(B.ENR_AFTER_OK.DIFF_MIN AS STRING), '')
                ),
                ''
              ),

              IF(
                COALESCE(B.ENR_AFTER_PATH, '') != '',
                FORMAT(' | ENR_AFT_PATH=[%s]', B.ENR_AFTER_PATH),
                ''
              )
            ),
            NULL
          )
        ]) AS X
        WHERE X IS NOT NULL AND X != ''
      ),
      '\n'
    ) AS TRJ_BIO_LOG
  FROM BIO_OP AS O
  LEFT JOIN BEST_PER_ROW AS B
    ON O.ID_ROW = B.ID_ROW
);

CREATE TEMP TABLE BIO_CTA AS (
  WITH CTA_LIST AS (
    SELECT DISTINCT CTA_CVE
    FROM UNIV
  ),
  KEY_STATS AS (
    SELECT
      CTA_CVE, COUNT(1) AS CNT_KEYS
    FROM BIO_KEYS
    GROUP BY CTA_CVE
  ),
  CTA_META AS (
    SELECT
      CTA_CVE, ANY_VALUE(CTE_CVE_UNICO) AS CTE_CVE_UNICO
    FROM UNIV
    GROUP BY CTA_CVE
  ),
  ENR_MATCH_HIST AS (
    SELECT
      K.CTA_CVE,
      K.TYPE AS MATCH_TYPE,
      K.SRC AS MATCH_SRC,
      K.KEY_VAL AS MATCH_KEY,
      K.DOB6,
      E.TS_ENR,
      E.ENR_CURP18
    FROM BIO_KEYS AS K
    LEFT JOIN BIO_ERN_KEYS_HIST AS E
      ON K.TYPE = E.TYPE
      AND K.KEY_VAL = E.KEY_VAL
      AND IF(K.TYPE = 'NAME_DOB', K.DOB6, '') = E.KEY_DOB6
  ),
  CTA_SUMMARY AS (
    SELECT
      CTA_CVE,
      COUNTIF(TS_ENR IS NOT NULL) AS CNT_ENR_MATCH
    FROM ENR_MATCH_HIST
    GROUP BY CTA_CVE
  ),
  CTA_BEST AS (
    SELECT
      CTA_CVE,
      TS_ENR,
      ENR_CURP18,
      MATCH_TYPE,
      MATCH_SRC,
      MATCH_KEY
    FROM ENR_MATCH_HIST
    WHERE TS_ENR IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY CTA_CVE
      ORDER BY TS_ENR DESC
    ) = 1
  )
  SELECT
    M.CTE_CVE_UNICO,
    L.CTA_CVE,
    B.ENR_CURP18 AS CTA_ENR_CURP18,
    IF(IFNULL(SU.CNT_ENR_MATCH, 0) > 0, 'SI', 'NO') AS CTA_ENR_EXISTE,
    CASE
      WHEN IFNULL(KS.CNT_KEYS, 0) = 0 THEN
        'NO KEYS'
      WHEN IFNULL(SU.CNT_ENR_MATCH, 0) = 0 THEN
        'SIN ENROLAMIENTO HISTORICO'
      ELSE
        FORMAT(
          'ULTIMO=%s | MATCH=%s/%s | KEY=%s',
          FORMAT_DATETIME('%F %T', B.TS_ENR),
          COALESCE(B.MATCH_TYPE, ''),
          COALESCE(B.MATCH_SRC, ''),
          COALESCE(B.MATCH_KEY, '')
        )
    END AS CTA_ENR_LOG
  FROM CTA_LIST AS L
  LEFT JOIN KEY_STATS AS KS
    ON L.CTA_CVE = KS.CTA_CVE
  LEFT JOIN CTA_SUMMARY AS SU
    ON L.CTA_CVE = SU.CTA_CVE
  LEFT JOIN CTA_BEST AS B
    ON L.CTA_CVE = B.CTA_CVE
  LEFT JOIN CTA_META AS M
    ON L.CTA_CVE = M.CTA_CVE
);

-- ============================================================
-- RESULT + MATCH_INV
-- ============================================================
CREATE TEMP TABLE RESULT_FINAL AS (
  WITH 
  CURP_ENR_U AS (
    SELECT DISTINCT
      CTA_ENR_CURP18 AS CURP18
    FROM BIO_CTA
    WHERE CTA_ENR_CURP18 IS NOT NULL
      AND IS_CURP18(CTA_ENR_CURP18)

    UNION DISTINCT

    SELECT DISTINCT
      APIA_CURP AS CURP18
    FROM UNIV
    WHERE APIA_CURP IS NOT NULL
      AND IS_CURP18(APIA_CURP)
  ),
  APIA_CURP AS (
    SELECT DISTINCT
      NORM_CURP18(A.BR_CURP) AS CURP18,
      NULLIF(SAFE_CAST(A.BR_SOLIC_CVE AS NUMERIC), 0) AS BR_SOLIC_CVE,
      SUBSTR(SAFE_CAST(A.BR_TIPO AS STRING), 1, 3) AS BR_TIPO_3,
      SAFE_CAST(A.BR_ORG AS STRING) AS TIP_INF,
      TRIM(A.BR_RFC) AS RFC_APIA
    FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_APIA` AS A
    INNER JOIN CURP_ENR_U AS U
      ON NORM_CURP18(A.BR_CURP) = U.CURP18
    WHERE TRUE
      AND NORM_CURP18(A.BR_CURP) IS NOT NULL
  ),
  APIA_SDO AS (
    SELECT
      A.CURP18,
      S.CTA_CVE, S.CTA_SDO_ACT, S.CTA_IMP_LIM_CRD, 
      SAFE_DIVIDE(S.CTA_SDO_ACT, NULLIF(S.CTA_IMP_LIM_CRD, 0)) AS PCT_USO,
      A.BR_SOLIC_CVE,
      A.BR_TIPO_3, A.TIP_INF,
      A.RFC_APIA
    FROM APIA_CURP AS A
    INNER JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_SDO_CTA_MES` AS S
      ON A.BR_SOLIC_CVE = S.BR_SOLIC_CVE
      AND A.BR_TIPO_3 = SUBSTR(SAFE_CAST(S.BR_TIPO AS STRING), 1, 3)
      AND A.TIP_INF = SAFE_CAST(S.TIP_INF AS STRING) 
    WHERE TRUE
      AND S.ANIO = CUR_ANIO
      AND S.MES = CUR_MES
  ),
  FICO_INV AS (
    SELECT DISTINCT
      NULLIF(SAFE_CAST(A.BR_SOLIC_CVE AS NUMERIC), 0) AS BR_SOLIC_CVE,
      TRIM(A.BR_RFC) AS FICO_RFC
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_REP_SOL_FICO` AS A
    INNER JOIN (
      SELECT DISTINCT BR_SOLIC_CVE
      FROM APIA_SDO
      WHERE BR_SOLIC_CVE IS NOT NULL
    ) AS U
      ON NULLIF(SAFE_CAST(A.BR_SOLIC_CVE AS NUMERIC), 0) = U.BR_SOLIC_CVE
  ),
  CLIE_FTES_CLEAN AS (
    SELECT DISTINCT
      A.CTA_CVE,

      CONCAT(
        TRIM(COALESCE(CTE_NOM, "")), " ",
        TRIM(COALESCE(CTE_APE_PAT, "")), " ",
        TRIM(COALESCE(CTE_APE_MAT, ""))
      ) AS NOMBRE,

      IF(REGEXP_CONTAINS(TRIM(CTE_CVE_RFC), r"^0+"), NULL, SUBSTR(TRIM(CTE_CVE_RFC), 1, 13)) AS CTE_CVE_RFC,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL AS STRING)), -10) AS NUMERIC) AS TEL,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_CEL AS STRING)), -10) AS NUMERIC) AS CEL,
      UPPER(TRIM(CTE_EMA)) AS EMAIL,
      SAFE_CAST(CDP_CVE AS STRING) AS CDP_CVE,
      SEX_CVE AS SEXO,
      CTE_FCH_NAC AS FCH_NAC,
      CTE_FCH_ALT AS FCH_APERTURA
    FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL` AS A
    INNER JOIN (SELECT DISTINCT CTA_CVE FROM APIA_SDO) AS K
      ON A.CTA_CVE = K.CTA_CVE
  ),
  MATCH_INV_RAW AS (
    SELECT
      A.CURP18, B.CTE_CVE_UNICO, A.BR_SOLIC_CVE, A.CTA_CVE, A.PCT_USO, A.CTA_SDO_ACT, A.CTA_IMP_LIM_CRD,
      F.NOMBRE, F.CTE_CVE_RFC, FI.FICO_RFC, A.RFC_APIA, F.EMAIL, F.CEL, F.CDP_CVE, F.SEXO,
      F.FCH_NAC, F.FCH_APERTURA
    FROM APIA_SDO AS A
    LEFT JOIN CLIE_FTES_CLEAN AS F
      ON F.CTA_CVE = A.CTA_CVE
    LEFT JOIN FICO_INV AS FI
      ON FI.BR_SOLIC_CVE = A.BR_SOLIC_CVE
    LEFT JOIN (SELECT DISTINCT CTE_CVE_UNICO, CTA_CVE FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ` INNER JOIN (SELECT DISTINCT CTA_CVE FROM UNIV) USING (CTA_CVE)) AS B
      ON A.CTA_CVE = B.CTA_CVE
  ),
  MATCH_INV_DEDUP AS (
    SELECT *
    FROM MATCH_INV_RAW
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY CURP18, CTA_CVE
      ORDER BY PCT_USO DESC, CTA_SDO_ACT DESC
    ) = 1
  ),
  BASE_CONTACTS AS (
    SELECT DISTINCT
      U.CTA_CVE,
      NULLIF(UPPER(TRIM(U.EMAIL)), '') AS EMAIL_CLEAN,
      U.CEL AS CEL_CLEAN
    FROM UNIV AS U
  ),
  MATCH_INV_CONTACTS AS (
    SELECT DISTINCT
      I.CTA_CVE,
      NULLIF(UPPER(TRIM(I.EMAIL)), '') AS EMAIL_CLEAN,
      I.CEL AS CEL_CLEAN
    FROM MATCH_INV_DEDUP AS I
  ),
  CONTACTS_EMAIL_TO_CHECK AS (
    SELECT DISTINCT EMAIL_CLEAN
    FROM (
      SELECT EMAIL_CLEAN FROM BASE_CONTACTS
      UNION DISTINCT
      SELECT EMAIL_CLEAN FROM MATCH_INV_CONTACTS
    )
    WHERE EMAIL_CLEAN IS NOT NULL
  ),
  CONTACTS_CEL_TO_CHECK AS (
    SELECT DISTINCT CEL_CLEAN
    FROM (
      SELECT CEL_CLEAN FROM BASE_CONTACTS
      UNION DISTINCT
      SELECT CEL_CLEAN FROM MATCH_INV_CONTACTS
    )
    WHERE CEL_CLEAN IS NOT NULL
  ),
  CLIE_FTES_EMAIL_RFC_GT1 AS (
    SELECT
      EMAIL_CLEAN,
      COUNT(DISTINCT CTE_CVE_RFC_CLEAN) AS CNT_RFC_DIST_X_EMAIL
    FROM (
      SELECT
        NULLIF(UPPER(TRIM(CTE_EMA)), '') AS EMAIL_CLEAN,
        NULLIF(
          UPPER(TRIM(
            IF(
              REGEXP_CONTAINS(TRIM(IFNULL(CTE_CVE_RFC, '')), r'^0+'),
              NULL,
              SUBSTR(TRIM(CTE_CVE_RFC), 1, 13)
            )
          )),
          ''
        ) AS CTE_CVE_RFC_CLEAN
      FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL`
      WHERE NULLIF(UPPER(TRIM(CTE_EMA)), '') IN (
        SELECT EMAIL_CLEAN FROM CONTACTS_EMAIL_TO_CHECK
      )
    )
    WHERE EMAIL_CLEAN IS NOT NULL
      AND CTE_CVE_RFC_CLEAN IS NOT NULL
    GROUP BY EMAIL_CLEAN
    HAVING COUNT(DISTINCT CTE_CVE_RFC_CLEAN) > 1
  ),
  CLIE_FTES_CEL_RFC_GT1 AS (
    SELECT
      CEL_CLEAN,
      COUNT(DISTINCT CTE_CVE_RFC_CLEAN) AS CNT_RFC_DIST_X_CEL
    FROM (
      SELECT
        SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_CEL AS STRING)), -10) AS NUMERIC) AS CEL_CLEAN,
        NULLIF(
          UPPER(TRIM(
            IF(
              REGEXP_CONTAINS(TRIM(IFNULL(CTE_CVE_RFC, '')), r'^0+'),
              NULL,
              SUBSTR(TRIM(CTE_CVE_RFC), 1, 13)
            )
          )),
          ''
        ) AS CTE_CVE_RFC_CLEAN
      FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL`
      WHERE SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_CEL AS STRING)), -10) AS NUMERIC) IN (
        SELECT CEL_CLEAN FROM CONTACTS_CEL_TO_CHECK
      )
    )
    WHERE CEL_CLEAN IS NOT NULL
      AND CTE_CVE_RFC_CLEAN IS NOT NULL
    GROUP BY CEL_CLEAN
    HAVING COUNT(DISTINCT CTE_CVE_RFC_CLEAN) > 1
  ),
  MATCH_INV_PER_BASE AS (
    SELECT DISTINCT
      COALESCE(C.CTA_CVE, B.CTA_CVE) AS BASE_CTA_CVE,
      COALESCE(C.CTA_ENR_CURP18, B.APIA_CURP) AS CURP18,

      NULLIF(COUNT(I.CTA_CVE), 0) AS CNT_CTA_INV,

      MAX(EI.CNT_RFC_DIST_X_EMAIL) AS MATCH_INV_CNT_RFC_DIST_X_EMAIL_GT1,
      MAX(CI.CNT_RFC_DIST_X_CEL) AS MATCH_INV_CNT_RFC_DIST_X_CEL_GT1,

      STRING_AGG(
        DISTINCT IF(
          I.CTA_CVE IS NULL,
          NULL,
          FORMAT(
            'CVE_UNI=%s | BR_SOL=%s | CTA=%s\nUSO=%.2f%% | SDO=%s | LIM=%s\nNOM=%s | RFC=%s\nEMAIL=%s | CEL=%s | CDP=%s',
            COALESCE(CAST(I.CTE_CVE_UNICO AS STRING), ''),
            COALESCE(CAST(I.BR_SOLIC_CVE AS STRING), ''),
            CAST(I.CTA_CVE AS STRING),
            100 * IFNULL(I.PCT_USO, 0),
            COALESCE(CAST(I.CTA_SDO_ACT AS STRING), ''),
            COALESCE(CAST(I.CTA_IMP_LIM_CRD AS STRING), ''),
            COALESCE(I.NOMBRE, ''),
            COALESCE(I.CTE_CVE_RFC, ''),
            COALESCE(I.EMAIL, ''),
            COALESCE(CAST(I.CEL AS STRING), ''),
            COALESCE(I.CDP_CVE, '')
          )
        ),
        '\n'
      ) AS MATCH_INV_LOG
    FROM (SELECT DISTINCT CTA_CVE, CTE_CVE_UNICO, APIA_CURP FROM UNIV) AS B
    LEFT JOIN (SELECT DISTINCT CTA_CVE, CTE_CVE_UNICO, CTA_ENR_CURP18 FROM BIO_CTA) AS C
      ON B.CTA_CVE = C.CTA_CVE
    LEFT JOIN MATCH_INV_DEDUP AS I
      ON I.CURP18 = COALESCE(C.CTA_ENR_CURP18, B.APIA_CURP)
      AND I.CTE_CVE_UNICO != COALESCE(C.CTE_CVE_UNICO, B.CTE_CVE_UNICO)

    LEFT JOIN CLIE_FTES_EMAIL_RFC_GT1 AS EI
      ON NULLIF(UPPER(TRIM(I.EMAIL)), '') = EI.EMAIL_CLEAN
    LEFT JOIN CLIE_FTES_CEL_RFC_GT1 AS CI
      ON I.CEL = CI.CEL_CLEAN

    WHERE TRUE
      AND COALESCE(C.CTA_ENR_CURP18, B.APIA_CURP) IS NOT NULL
      AND IS_CURP18(B.APIA_CURP)
      AND IS_CURP18(C.CTA_ENR_CURP18)
    GROUP BY BASE_CTA_CVE, CURP18
  )
  SELECT
    U.*,
    T.FLG_BIO_REALIZADO,
    T.TRJ_BIO_REALIZADO_LOG,

    T.TRJ_BIO_EXITOSO,
    T.MATCH_BIO_STT,

    T.TRJ_BIO_LOG,

    T.TRJ_BIO_AUT_FUERA_HORARIO AS AUT_OUT,
    T.TRJ_BIO_ENR_FUERA_HORARIO AS ENR_OUT,
    
    C.CTA_ENR_EXISTE,
    C.CTA_ENR_LOG,
    C.CTA_ENR_CURP18,

    M.CNT_CTA_INV,
    M.MATCH_INV_LOG,

    BE.CNT_RFC_DIST_X_EMAIL AS BASE_CNT_RFC_DIST_X_EMAIL_GT1,
    BC.CNT_RFC_DIST_X_CEL AS BASE_CNT_RFC_DIST_X_CEL_GT1,

    M.MATCH_INV_CNT_RFC_DIST_X_EMAIL_GT1,
    M.MATCH_INV_CNT_RFC_DIST_X_CEL_GT1
  FROM UNIV AS U
  LEFT JOIN BIO_TRJ AS T
    ON T.ID_ROW = CONCAT(CAST(U.CTA_CVE AS STRING), '|', CAST(U.TRJ_NUM AS STRING))
  LEFT JOIN BIO_CTA AS C
    ON C.CTA_CVE = U.CTA_CVE
  LEFT JOIN MATCH_INV_PER_BASE AS M
    ON M.CURP18 = C.CTA_ENR_CURP18
    AND M.BASE_CTA_CVE = U.CTA_CVE
  LEFT JOIN CLIE_FTES_EMAIL_RFC_GT1 AS BE
    ON NULLIF(UPPER(TRIM(U.EMAIL)), '') = BE.EMAIL_CLEAN
  LEFT JOIN CLIE_FTES_CEL_RFC_GT1 AS BC
    ON U.CEL = BC.CEL_CLEAN
);

-- ============================================================
-- DETALLE
-- ============================================================
SELECT *
FROM RESULT_FINAL
WHERE TRUE 
ORDER BY FCH_REP, CTA_CVE, TRJ_NUM
;

-- ============================================================
-- SCORECARD MENSUAL
-- TOTAL / LIVERPOOL / SUBURBIA
-- ============================================================
CREATE TEMP TABLE SCORECARD_EJECUTIVO AS (
  WITH BASE_SCORECARD_UNI AS (
    SELECT
      CASE
        WHEN REGEXP_CONTAINS(CAST(TIP_INF_R AS STRING), r'^1') THEN 'LIVERPOOL'
        WHEN REGEXP_CONTAINS(CAST(TIP_INF_R AS STRING), r'^2') THEN 'SUBURBIA'
        ELSE 'OTROS'
      END AS SEGMENTO_EMISOR,
      FCH_REP,
      IFNULL(FLG_EMBO, 0) AS FLG_EMBO,
      IFNULL(FLG_BIO_REALIZADO, 0) AS FLG_BIO_REALIZADO,
      IFNULL(TRJ_BIO_EXITOSO, 0) AS TRJ_BIO_EXITOSO,
      COALESCE(MATCH_BIO_STT, 'SIN MATCH_BIO_STT') AS MATCH_BIO_STT
    FROM RESULT_FINAL
    WHERE EXTRACT(YEAR FROM FCH_REP) = 2026
  ),
  BASE_SCORECARD AS (
    SELECT
      'EL PUERTO DE LIVERPOOL' AS REPORTE,
      *
    FROM BASE_SCORECARD_UNI

    UNION ALL

    SELECT
      'LIVERPOOL' AS REPORTE,
      *
    FROM BASE_SCORECARD_UNI
    WHERE SEGMENTO_EMISOR = 'LIVERPOOL'

    UNION ALL

    SELECT
      'SUBURBIA' AS REPORTE,
      *
    FROM BASE_SCORECARD_UNI
    WHERE SEGMENTO_EMISOR = 'SUBURBIA'
  ),
  PERIODIZED AS (
    SELECT REPORTE, 'ENE 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 1
    UNION ALL
    SELECT REPORTE, 'FEB 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 2
    UNION ALL
    SELECT REPORTE, 'MAR 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 3
    UNION ALL
    SELECT REPORTE, 'ABR 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 4
    UNION ALL
    SELECT REPORTE, 'MAY 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 5
    UNION ALL
    SELECT REPORTE, 'JUN 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 6
    UNION ALL
    SELECT REPORTE, 'JUL 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 7
    UNION ALL
    SELECT REPORTE, 'AGO 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 8
    UNION ALL
    SELECT REPORTE, 'SEP 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 9
    UNION ALL
    SELECT REPORTE, 'OCT 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 10
    UNION ALL
    SELECT REPORTE, 'NOV 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 11
    UNION ALL
    SELECT REPORTE, 'DIC 26' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD WHERE EXTRACT(MONTH FROM FCH_REP) = 12
    UNION ALL
    SELECT REPORTE, '2026' AS PERIODO, * EXCEPT(REPORTE) FROM BASE_SCORECARD
  ),
  TOT AS (
    SELECT
      REPORTE, PERIODO,
      COUNT(*) AS REGISTROS
    FROM PERIODIZED
    GROUP BY REPORTE, PERIODO
  ),
  EMBO AS (
    SELECT
      REPORTE, PERIODO,
      COUNT(*) AS REGISTROS
    FROM PERIODIZED
    WHERE FLG_EMBO = 1
    GROUP BY REPORTE, PERIODO
  ),
  BIO1 AS (
    SELECT
      REPORTE, PERIODO,
      COUNT(*) AS REGISTROS
    FROM PERIODIZED
    WHERE FLG_EMBO = 1
      AND FLG_BIO_REALIZADO = 1
    GROUP BY REPORTE, PERIODO
  ),
  BIO0 AS (
    SELECT
      REPORTE, PERIODO,
      COUNT(*) AS REGISTROS
    FROM PERIODIZED
    WHERE FLG_EMBO = 1
      AND FLG_BIO_REALIZADO = 0
    GROUP BY REPORTE, PERIODO
  ),
  BIO1_OK AS (
    SELECT
      REPORTE, PERIODO,
      COUNT(*) AS REGISTROS
    FROM PERIODIZED
    WHERE FLG_EMBO = 1
      AND FLG_BIO_REALIZADO = 1
      AND TRJ_BIO_EXITOSO = 1
    GROUP BY REPORTE, PERIODO
  ),
  BIO1_FAIL AS (
    SELECT
      REPORTE, PERIODO,
      COUNT(*) AS REGISTROS
    FROM PERIODIZED
    WHERE FLG_EMBO = 1
      AND FLG_BIO_REALIZADO = 1
      AND TRJ_BIO_EXITOSO = 0
    GROUP BY REPORTE, PERIODO
  ),
  STT_BIO1_FAIL AS (
    SELECT
      REPORTE, PERIODO, MATCH_BIO_STT,
      COUNT(*) AS REGISTROS
    FROM PERIODIZED
    WHERE FLG_EMBO = 1
      AND FLG_BIO_REALIZADO = 1
      AND TRJ_BIO_EXITOSO = 0
    GROUP BY REPORTE, PERIODO, MATCH_BIO_STT
  ),
  STT_BIO1_FAIL_ORD AS (
    SELECT
      REPORTE, MATCH_BIO_STT,
      ROW_NUMBER() OVER (
        PARTITION BY REPORTE
        ORDER BY COUNT(*) DESC, MATCH_BIO_STT
      ) AS ORD_STT
    FROM BASE_SCORECARD
    WHERE FLG_EMBO = 1
      AND FLG_BIO_REALIZADO = 1
      AND TRJ_BIO_EXITOSO = 0
    GROUP BY REPORTE, MATCH_BIO_STT
  ),
  ROWS_FIXED AS (
    SELECT
      T.REPORTE,
      10 AS ORDEN,
      'Emisiones Totales' AS FILA,
      'VAL' AS TIPO,
      T.PERIODO,
      T.REGISTROS AS NUMERADOR,
      NULL AS DENOMINADOR
    FROM TOT AS T

    UNION ALL

    SELECT
      T.REPORTE,
      11 AS ORDEN,
      '  % Embozada' AS FILA,
      'PCT' AS TIPO,
      T.PERIODO,
      E.REGISTROS AS NUMERADOR,
      T.REGISTROS AS DENOMINADOR
    FROM TOT AS T
    LEFT JOIN EMBO AS E
      USING (REPORTE, PERIODO)

    UNION ALL

    SELECT
      T.REPORTE,
      12 AS ORDEN,
      '  % No Embozada' AS FILA,
      'PCT' AS TIPO,
      T.PERIODO,
      T.REGISTROS - IFNULL(E.REGISTROS, 0) AS NUMERADOR,
      T.REGISTROS AS DENOMINADOR
    FROM TOT AS T
    LEFT JOIN EMBO AS E
      USING (REPORTE, PERIODO)

    UNION ALL

    SELECT
      E.REPORTE,
      20 AS ORDEN,
      'Embozadas' AS FILA,
      'VAL' AS TIPO,
      E.PERIODO,
      E.REGISTROS AS NUMERADOR,
      NULL AS DENOMINADOR
    FROM EMBO AS E

    UNION ALL

    SELECT
      E.REPORTE,
      21 AS ORDEN,
      '  % Biométrico Realizado' AS FILA,
      'PCT' AS TIPO,
      E.PERIODO,
      B1.REGISTROS AS NUMERADOR,
      E.REGISTROS AS DENOMINADOR
    FROM EMBO AS E
    LEFT JOIN BIO1 AS B1
      USING (REPORTE, PERIODO)

    UNION ALL

    SELECT
      E.REPORTE,
      22 AS ORDEN,
      '  % Biométrico No Realizado' AS FILA,
      'PCT' AS TIPO,
      E.PERIODO,
      B0.REGISTROS AS NUMERADOR,
      E.REGISTROS AS DENOMINADOR
    FROM EMBO AS E
    LEFT JOIN BIO0 AS B0
      USING (REPORTE, PERIODO)

    UNION ALL

    SELECT
      B1.REPORTE,
      30 AS ORDEN,
      'Biométrico Realizado' AS FILA,
      'VAL' AS TIPO,
      B1.PERIODO,
      B1.REGISTROS AS NUMERADOR,
      NULL AS DENOMINADOR
    FROM BIO1 AS B1

    UNION ALL

    SELECT
      B1.REPORTE,
      31 AS ORDEN,
      '  % Exitoso' AS FILA,
      'PCT' AS TIPO,
      B1.PERIODO,
      B1O.REGISTROS AS NUMERADOR,
      B1.REGISTROS AS DENOMINADOR
    FROM BIO1 AS B1
    LEFT JOIN BIO1_OK AS B1O
      USING (REPORTE, PERIODO)

    UNION ALL

    SELECT
      B1.REPORTE,
      32 AS ORDEN,
      '  % Fallido' AS FILA,
      'PCT' AS TIPO,
      B1.PERIODO,
      B1F.REGISTROS AS NUMERADOR,
      B1.REGISTROS AS DENOMINADOR
    FROM BIO1 AS B1
    LEFT JOIN BIO1_FAIL AS B1F
      USING (REPORTE, PERIODO)

    UNION ALL

    SELECT
      B1F.REPORTE,
      40 AS ORDEN,
      'Biométrico Fallido' AS FILA,
      'VAL' AS TIPO,
      B1F.PERIODO,
      B1F.REGISTROS AS NUMERADOR,
      NULL AS DENOMINADOR
    FROM BIO1_FAIL AS B1F
  ),
  ROWS_BIO1_FAIL_STT AS (
    SELECT
      S.REPORTE,
      40 + O.ORD_STT AS ORDEN,
      CASE S.MATCH_BIO_STT
        WHEN 'REGISTRO FALLIDO' THEN '  % Registro Fallido'
        WHEN 'AUTENTICACION FALLIDA' THEN '  % Autenticación Fallida'
        WHEN 'AUTENTICA DESPUES DEL EVENTO (FALLIDO)' THEN '  % Autentica Después Del Evento (Fallido)'
        WHEN 'ENROLA DESPUES DEL EVENTO (FALLIDO)' THEN '  % Enrola Después Del Evento (Fallido)'
        WHEN 'REENROLA (NO EXITOSO)' THEN '  % Reenrola (No Exitoso)'
        ELSE CONCAT('  % ', INITCAP(LOWER(S.MATCH_BIO_STT)))
      END AS FILA,
      'PCT' AS TIPO,
      S.PERIODO,
      S.REGISTROS AS NUMERADOR,
      B1F.REGISTROS AS DENOMINADOR
    FROM STT_BIO1_FAIL AS S
    INNER JOIN BIO1_FAIL AS B1F
      USING (REPORTE, PERIODO)
    INNER JOIN STT_BIO1_FAIL_ORD AS O
      ON S.REPORTE = O.REPORTE
      AND S.MATCH_BIO_STT = O.MATCH_BIO_STT
  ),
  ROWS_ALL AS (
    SELECT * FROM ROWS_FIXED
    UNION ALL
    SELECT * FROM ROWS_BIO1_FAIL_STT
  ),
  RENDERED AS (
    SELECT
      REPORTE,
      ORDEN,
      FILA,
      PERIODO,
      CASE
        WHEN TIPO = 'VAL' THEN
          CASE
            WHEN NUMERADOR IS NULL THEN ''
            ELSE CAST(CAST(NUMERADOR AS INT64) AS STRING)
          END
        WHEN TIPO = 'PCT' THEN
          CASE
            WHEN DENOMINADOR IS NULL OR DENOMINADOR = 0 OR NUMERADOR IS NULL THEN ''
            ELSE FORMAT('%.2f%%', 100 * SAFE_DIVIDE(NUMERADOR, DENOMINADOR))
          END
        ELSE ''
      END AS DISPLAY_VAL
    FROM ROWS_ALL
  )
  SELECT
    REPORTE,
    ORDEN,
    FILA,

    COALESCE(MAX(IF(PERIODO = 'ENE 26', DISPLAY_VAL, NULL)), '') AS `ENE 26`,
    COALESCE(MAX(IF(PERIODO = 'FEB 26', DISPLAY_VAL, NULL)), '') AS `FEB 26`,
    COALESCE(MAX(IF(PERIODO = 'MAR 26', DISPLAY_VAL, NULL)), '') AS `MAR 26`,
    COALESCE(MAX(IF(PERIODO = 'ABR 26', DISPLAY_VAL, NULL)), '') AS `ABR 26`,
    COALESCE(MAX(IF(PERIODO = 'MAY 26', DISPLAY_VAL, NULL)), '') AS `MAY 26`,
    COALESCE(MAX(IF(PERIODO = 'JUN 26', DISPLAY_VAL, NULL)), '') AS `JUN 26`,
    COALESCE(MAX(IF(PERIODO = 'JUL 26', DISPLAY_VAL, NULL)), '') AS `JUL 26`,
    COALESCE(MAX(IF(PERIODO = 'AGO 26', DISPLAY_VAL, NULL)), '') AS `AGO 26`,
    COALESCE(MAX(IF(PERIODO = 'SEP 26', DISPLAY_VAL, NULL)), '') AS `SEP 26`,
    COALESCE(MAX(IF(PERIODO = 'OCT 26', DISPLAY_VAL, NULL)), '') AS `OCT 26`,
    COALESCE(MAX(IF(PERIODO = 'NOV 26', DISPLAY_VAL, NULL)), '') AS `NOV 26`,
    COALESCE(MAX(IF(PERIODO = 'DIC 26', DISPLAY_VAL, NULL)), '') AS `DIC 26`,
    COALESCE(MAX(IF(PERIODO = '2026', DISPLAY_VAL, NULL)), '') AS `2026`
  FROM RENDERED
  GROUP BY REPORTE, ORDEN, FILA
);

-- ============================================================
-- PIVOT 1: TOTAL
-- ============================================================
SELECT
  FILA,
  `ENE 26`, `FEB 26`, `MAR 26`, `ABR 26`, `MAY 26`, `JUN 26`,
  `JUL 26`, `AGO 26`, `SEP 26`, `OCT 26`, `NOV 26`, `DIC 26`,
  `2026`
FROM SCORECARD_EJECUTIVO
WHERE REPORTE = 'EL PUERTO DE LIVERPOOL'
ORDER BY ORDEN, FILA
;

-- ============================================================
-- PIVOT 2: LIVERPOOL
-- ============================================================
SELECT
  FILA,
  `ENE 26`, `FEB 26`, `MAR 26`, `ABR 26`, `MAY 26`, `JUN 26`,
  `JUL 26`, `AGO 26`, `SEP 26`, `OCT 26`, `NOV 26`, `DIC 26`,
  `2026`
FROM SCORECARD_EJECUTIVO
WHERE REPORTE = 'LIVERPOOL'
ORDER BY ORDEN, FILA
;

-- ============================================================
-- PIVOT 3: SUBURBIA
-- ============================================================
SELECT
  FILA,
  `ENE 26`, `FEB 26`, `MAR 26`, `ABR 26`, `MAY 26`, `JUN 26`,
  `JUL 26`, `AGO 26`, `SEP 26`, `OCT 26`, `NOV 26`, `DIC 26`,
  `2026`
FROM SCORECARD_EJECUTIVO
WHERE REPORTE = 'SUBURBIA'
ORDER BY ORDEN, FILA
;

DROP TABLE IF EXISTS UNIV_INI;
DROP TABLE IF EXISTS UNIV;

DROP TABLE IF EXISTS BIO_KEYS;
DROP TABLE IF EXISTS BIO_ERN_KEYS;
DROP TABLE IF EXISTS BIO_AUT_KEYS;

DROP TABLE IF EXISTS BIO_TRJ;
DROP TABLE IF EXISTS BIO_CTA;

DROP TABLE IF EXISTS RESULT_FINAL;
DROP TABLE IF EXISTS BIO_ERN_KEYS_HIST;