-- ============================================================
-- INPUTS
-- ============================================================

DECLARE FE_INI DATE DEFAULT DATE(2025,1, 1);
DECLARE TXN_BON ARRAY<STRING> DEFAULT ['0405', '0429', '0409'];

CREATE TEMP TABLE CTAS AS (
  SELECT CAST(x AS NUMERIC) AS CTA_CVE
  FROM UNNEST([


  ]) AS x
);

-- ============================================================
-- HELPERS
-- ============================================================
CREATE TEMP FUNCTION ZEROS_TO_NULL(s STRING) AS (
  CASE
    WHEN s IS NULL THEN NULL
    WHEN TRIM(s) = "" THEN NULL
    WHEN REGEXP_CONTAINS(TRIM(s), r"^0+$") THEN NULL
    ELSE TRIM(s)
  END
);

CREATE TEMP FUNCTION NORM_NAME(s STRING) AS (
  NULLIF(TRIM(UPPER(s)), "")
);

CREATE TEMP FUNCTION NORM_EMAIL(s STRING) AS (
  NULLIF(TRIM(LOWER(s)), "")
);


-- ============================================================
-- RESUMEN
-- ============================================================
CREATE TEMP TABLE CTA_TRJ_BASE AS (
  SELECT DISTINCT
    SAFE_CAST(CTA_CVE AS NUMERIC) AS CTA_CVE,
    SAFE_CAST(TRJ_NUM AS NUMERIC) AS TRJ_NUM,
    SAFE_CAST(CTE_CVE_UNICO AS NUMERIC) AS CTE_CVE,
    TRJ_EDO_CVE,
    IND_TIT
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ`
  WHERE SAFE_CAST(CTA_CVE AS NUMERIC) IN (SELECT CTA_CVE FROM CTAS)
);

CREATE TEMP TABLE USR_VPL AS (
  SELECT
    EMP_NOM, CVE_EMP, USR, ID_USER AS ID_VPL, NOM_PERF, TDA, TDA_NOM, FCH_ALT, FCH_BAJ
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VDIM_PREVFRAU_USR_VPL_HIST`
);

CREATE TEMP TABLE VPL_INFO AS (
  WITH 
  SDO_AUX AS (
    SELECT
      A.CTA_CVE, 
      STRING_AGG(
        CONCAT(
          B.TRJ_NUM, 
          " | EDO: ",
          TRJ_EDO_CVE,
          " | TIT: ",
          IND_TIT)
        , "\n") AS TRJ_NUM,
      CTA_FCH_SOL, CTA_EDO_CVE, SAFE_CAST(BR_SOLIC_CVE AS NUMERIC) AS BR_SOLIC_CVE, CTA_NIV_MOR,
      CONCAT(CCR_CVE_BLQ_UNO, RAZON_BLQ_UNO_CVE) AS  BLQ1, CONCAT(CCR_CVE_BLQ_DOS, RAZON_BLQ_DOS_CVE) AS BLQ2,
      CTA_IMP_LIM_CRD, CTA_SDO_ACT, CTA_HIST_PAGOS
    FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_SDO_CTA_MES` AS A
    INNER JOIN CTA_TRJ_BASE AS B
      USING(CTA_CVE)
    WHERE ANIO = EXTRACT(YEAR FROM CURRENT_DATE()) AND MES = EXTRACT(MONTH FROM CURRENT_DATE())
    GROUP BY 
      CTA_CVE, CTA_FCH_SOL, CTA_EDO_CVE, BR_SOLIC_CVE, CTA_NIV_MOR,
      CCR_CVE_BLQ_UNO, RAZON_BLQ_UNO_CVE, CCR_CVE_BLQ_DOS, RAZON_BLQ_DOS_CVE,
      CTA_IMP_LIM_CRD, CTA_SDO_ACT, CTA_HIST_PAGOS
  ),
  CLIE_FTES AS (
    SELECT DISTINCT
      CTA_CUSTOMER AS CTE_UNI,
      CTA_CVE,
      CONCAT(
        TRIM(COALESCE(CTE_NOM, "")), " ",
        TRIM(COALESCE(CTE_APE_PAT, "")), " ",
        TRIM(COALESCE(CTE_APE_MAT, ""))
      ) AS NOMBRE,
      TRIM(CTE_CVE_RFC) AS RFC,
      TRIM(UPPER(CTE_EMA)) AS EMAIL,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL AS STRING)), -10) AS NUMERIC) AS TEL,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_CEL AS STRING)), -10) AS NUMERIC) AS CEL,
      CONCAT(
        TRIM(COALESCE(CTE_DES_DIR_UNO, "")), ", ",
        TRIM(COALESCE(CTE_DES_DIR_DOS, "")), ", ",
        COALESCE(CAST(CDP_CVE AS STRING), ""), ", ",
        TRIM(COALESCE(CTE_DES_CIU, ""))
      ) AS DIRECCION,
      SEX_CVE AS SEXO,
      CTE_FCH_NAC AS FCH_NAC,
      CTE_FCH_ALT AS FCH_APERTURA,
      TRIM(CTE_EMPR) AS EMPLEO,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL_OFI AS STRING)), -10) AS NUMERIC) AS TEL_OFI,
      TRIM(CTE_CONYUGE) AS NOM_CONYUGE,
      TRIM(CTE_NOM_REFERENCIA1) AS NOM_REF1,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL_REFERENCIA1 AS STRING)), -10) AS NUMERIC) AS TEL_REF1,
      TRIM(CTE_NOM_REFERENCIA2) AS NOM_REF2,
      SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL_REFERENCIA2 AS STRING)), -10) AS NUMERIC) AS TEL_REF2
    FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL`
    WHERE CTA_CVE IN (SELECT CTA_CVE FROM CTAS)
  )
  SELECT 
    A.*, B.* EXCEPT(CTA_CVE)
  FROM CLIE_FTES AS A
  LEFT JOIN SDO_AUX AS B
    USING (CTA_CVE)
);

SELECT *
FROM VPL_INFO
ORDER BY CTE_UNI, CTA_CVE, FCH_APERTURA;

-- ============================================================
-- SOLICITUD
-- ============================================================
WITH
CTA_SOL AS (
  SELECT DISTINCT 
    CTA_CVE, BR_SOLIC_CVE 
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA` 
  INNER JOIN CTAS USING (CTA_CVE)
)
SELECT
    BR_SOLIC_CVE AS SOLICITUD,
    B.CTA_CVE AS CUENTA,
    SAFE_CAST(BR_EMP_PRM AS NUMERIC) AS EMPLEADO1,
    BR_EMP_CVE AS EMPLEADO2,
    SAFE_CAST(BR_TDA_ADM AS NUMERIC) AS TDA_ADMIN,
    SAFE_CAST(BR_TDA_CAP AS NUMERIC) AS TDA_CAPTURA,
    CONCAT(
      TRIM(COALESCE(BR_NOM, "")), " ",
      TRIM(COALESCE(BR_APE_PAT, "")), " ",
      TRIM(COALESCE(BR_APE_MAT, ""))
    ) AS NOMBRE,
    TRIM(BR_EMBOSADO) AS NOM_EMBOSADO,
    TRIM(BR_RFC) AS RFC,
    TRIM(BR_CURP) AS CURP,
    TRIM(CAST(BR_EDAD AS STRING)) AS EDAD,
    TRIM(UPPER(BR_MAIL)) AS EMAIL,
    SAFE_CAST(
      SUBSTR(
        CONCAT(
          COALESCE(ZEROS_TO_NULL(CAST(BR_LADA AS STRING)), ""),
          COALESCE(ZEROS_TO_NULL(CAST(BR_TEL AS STRING)), "")
        ),
        -10
      ) AS NUMERIC
    ) AS TEL,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_CEL AS STRING)), -10) AS NUMERIC) AS CEL,
    CONCAT(
      TRIM(COALESCE(BR_DIR, "")), ", ",
      TRIM(COALESCE(BR_COL, "")), ", ",
      COALESCE(CAST(BR_CDP AS STRING), ""), ", ",
      TRIM(COALESCE(BR_CIU, "")), ", ",
      TRIM(COALESCE(BR_EDO, "")), ", ",
      TRIM(COALESCE(BR_PAIS, ""))
    ) AS DIRECCION,
    TRIM(BR_SEXO) AS SEXO,
    BR_FCH_APE AS FCH_APERTURA,
    TRIM(BR_NOM_CONY) AS NOM_CONYUG,
    BR_FCH_NAC_CONY AS FCH_NAC_CONYUG,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_CEL_CONY AS STRING)), -10) AS NUMERIC) AS CEL_CONYUG,
    TRIM(BR_EMPR_CONY) AS EMP_CONYUG,
    TRIM(BR_EMPR) AS EMPLEO,
    CONCAT(
      TRIM(COALESCE(BR_DIR_EMPR, "")), ", ",
      TRIM(COALESCE(BR_COL_EMPR, "")), ", ",
      TRIM(COALESCE(BR_CDP_EMPR, "")), ", ",
      TRIM(COALESCE(BR_EDO_EMPR, ""))
    ) AS DIR_EMPLEO,
    SAFE_CAST(
      SUBSTR(
        CONCAT(
          COALESCE(ZEROS_TO_NULL(CAST(BR_LADA_OFI AS STRING)), ""),
          COALESCE(ZEROS_TO_NULL(CAST(BR_TEL_OFI AS STRING)), "")
        ),
        -10
      ) AS NUMERIC
    ) AS TEL_OFI,
    TRIM(BR_REF1) AS NOM_REF1,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_TEL_REF1 AS STRING)), -10) AS NUMERIC) AS TEL_REF1,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_CEL_REF1 AS STRING)), -10) AS NUMERIC) AS CEL_REF1,
    TRIM(BR_REF2) AS NOM_REF2,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_TEL_REF2 AS STRING)), -10) AS NUMERIC) AS TEL_REF2,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_CEL_REF2 AS STRING)), -10) AS NUMERIC) AS CEL_REF2
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_APIA` AS A
  INNER JOIN CTA_SOL AS B
    USING(BR_SOLIC_CVE) 
  ORDER BY BR_FCH_APE DESC;

-- ============================================================
-- ASHI
-- ============================================================
SELECT * FROM `crp-pro-dwh-semanticagold.EIL_DP_VRAW.VFAC_NEGFIN_AJUSTES_MONETARIOS` AS A
INNER JOIN CTAS ON A.ACCOUNT = CTAS.CTA_CVE
ORDER BY FECHA_1, HORA_1;

-- ============================================================
-- PRTNCIA
-- ============================================================
SELECT
  PR.* EXCEPT(FCH_CARGA, ROW_UUID, EXISTENCIA_CORREO, ORG, LOGO, ID),
  VPL.ID_VPL,
  VPL.USR,
  VPL.EMP_NOM
FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_PRTNCIA_DATOS` AS PR
LEFT JOIN USR_VPL AS VPL
  ON PR.ID = VPL.ID_VPL
  AND VPL.FCH_ALT <= PR.FECHA
  AND (VPL.FCH_BAJ IS NULL OR VPL.FCH_BAJ > PR.FECHA)
WHERE NUMERO_CUENTA IN (SELECT CTA_CVE FROM CTAS)
ORDER BY DATETIME(FECHA, HORA)
;

-- ============================================================
-- ACLA
-- ============================================================
WITH CTA_TRJ AS (
  SELECT DISTINCT
    CTA_CVE, TRJ_NUM, CTE_CVE
  FROM CTA_TRJ_BASE
),
ACLA AS (
  SELECT DISTINCT 
    B.CTA_CVE, NUM_TARJETA, NOMBRE_CLIENTE, FOLIO AS FOLIO_ACLARACION, 
    DATE(FCH_HORA_ACLARACION) AS FCH_ACLA, TIME(FCH_HORA_ACLARACION) AS HRA_ACLA,
    TIPO_ACLARACION_INICIAL,
    DATE(FCH_HORA_DICTAMEN) AS FCH_DICTAMEN, TIME(FCH_HORA_DICTAMEN) AS HRA_DICTAMEN,
    TIPO_ACLARACION_FINAL,
    USUARIO_DICTAMEN,
    DOCUMENTO, OBSERVACION, HECHOS
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_FOLIO_ACLARACIONES` AS A
  INNER JOIN CTA_TRJ AS B ON SAFE_CAST(NUM_TARJETA AS NUMERIC) = TRJ_NUM
  WHERE DATE(FCH_HORA_ACLARACION) >= FE_INI
),
ACLA_TXN AS (
  SELECT 
    A.FOLIO_ACLARACION, SUM(MONTO) AS MONTO,
    STRING_AGG(
      CONCAT(
        'FolTxn: ', COALESCE(CAST(FOLIO_TRANSACCION AS STRING), ''),
        ' | Ref23: ', COALESCE(CAST(REFERENCIA23 AS STRING), ''),
        ' | Aut: ', COALESCE(CAST(AUTORIZACION AS STRING), ''),
        ' | FchTxn: ', COALESCE(CAST(DATE(FCH_HORA_TRANSACCION) AS STRING), ''),
        ' | HraTxn: ', COALESCE(CAST(TIME(FCH_HORA_TRANSACCION) AS STRING), ''),
        ' | Tda: ', COALESCE(CAST(TIENDA AS STRING), ''),
        ' | Imp: ', COALESCE(CAST(MONTO AS STRING), ''),
        ' | Term: ', COALESCE(CAST(TERMINAL AS STRING), ''),
        ' | Bol: ', COALESCE(CAST(BOLETA AS STRING), ''),
        ' | Plan: ', COALESCE(CAST(PLAN AS STRING), ''),
        ' | ModEnt: ', COALESCE(CAST(MODOENTRADA AS STRING), ''),
        ' | CVV2: ', COALESCE(CAST(PRESENCIACVV2 AS STRING), ''),
        ' | MetAut: ', COALESCE(CAST(METODO_AUTENTICACION AS STRING), ''),
        ' | NipOn: ', COALESCE(CAST(NIP_ON_US AS STRING), ''),
        ' | NipOff: ', COALESCE(CAST(NIP_OFF_US AS STRING), ''),
        ' | DicTxn: ', COALESCE(CAST(DICTAMEN_TRANSACCION AS STRING), ''),
        ' | FrauTrn: ', COALESCE(CAST(TIPO_FRAUDE_TRN AS STRING), ''),
        ' | ObsTrn: ', COALESCE(CAST(OBSERVACIONES_TRN AS STRING), ''),
        ' | ObsGen: ', COALESCE(CAST(OBSERVACIONES_GENERAL AS STRING), '')
      ),
      '\n' ORDER BY FOLIO_TRANSACCION
    ) AS TXN_AGRUPADAS
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_TRN_ACLARACIONES` AS A
  INNER JOIN ACLA AS B USING(FOLIO_ACLARACION)
  GROUP BY A.FOLIO_ACLARACION
)
SELECT 
  ACLA.*,
  ACLA_TXN.MONTO, 
  ACLA_TXN.TXN_AGRUPADAS
FROM ACLA
LEFT JOIN ACLA_TXN USING(FOLIO_ACLARACION)
ORDER BY FCH_ACLA;

-- ============================================================
-- BONIF
-- ============================================================
WITH BONIF AS (
  SELECT
    SAFE_CAST(ARU.CTA_CVE AS NUMERIC) AS CTA_CVE, TXN_IMP AS IMP, 
    ARU.TXN_USR AS ID_VPL, VPL.USR AS USR, VPL.EMP_NOM AS EMP_NOM, 
    ARU.TXN_DES AS DESCRIP, ARU.TXN_TDA, ARU.PLAN_CVE,
    ARU.TXN_FCH AS FECHA_TXN, TXN_TDA AS TDA
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_ARU080_DETALLE_TXN` AS ARU
  LEFT JOIN USR_VPL AS VPL
    ON ARU.TXN_USR = VPL.ID_VPL
    AND VPL.FCH_ALT <= ARU.TXN_FCH
    AND (VPL.FCH_BAJ IS NULL OR VPL.FCH_BAJ > ARU.TXN_FCH)
  WHERE TXN_CDO IN UNNEST(TXN_BON)
    AND SAFE_CAST(ARU.CTA_CVE AS NUMERIC) IN (SELECT CTA_CVE FROM CTAS)
    AND ARU.TXN_ANIO >= EXTRACT(YEAR FROM FE_INI)
)
SELECT *
FROM BONIF
ORDER BY FECHA_TXN;

-- ============================================================
-- PANTALLAS
-- ============================================================
WITH P01 AS (
  SELECT
    SAFE_CAST(CTA_CVE AS NUMERIC) AS CTA_CVE, FCH, HRA, P01.USR, VPL.ID_VPL AS ID, PTA
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_P01` AS P01
  LEFT JOIN USR_VPL AS VPL
    ON P01.USR = VPL.USR
    AND VPL.FCH_ALT <= P01.FCH
    AND (VPL.FCH_BAJ IS NULL OR VPL.FCH_BAJ > P01.FCH)
  WHERE SAFE_CAST(P01.CTA_CVE AS NUMERIC) IN (SELECT CTA_CVE FROM CTAS)
    AND P01.FCH >= FE_INI
    AND (PTA IS NOT NULL OR PTA <> "")
)
SELECT *
FROM P01
ORDER BY DATETIME(FCH, HRA)
;

-- ============================================================
-- R02
-- ============================================================
WITH R02_MATCH AS (
  SELECT DISTINCT
    CTE_CVE, CTA_CVE, TRJ_NUM, CTA_CVE AS MATCH_VAL, 'CTA_CVE' AS TYPE_MATCH
  FROM CTA_TRJ_BASE
  WHERE CTA_CVE IS NOT NULL

  UNION DISTINCT

  SELECT DISTINCT
    CTE_CVE, CTA_CVE, TRJ_NUM, TRJ_NUM AS MATCH_VAL, 'TRJ_NUM' AS TYPE_MATCH
  FROM CTA_TRJ_BASE
  WHERE TRJ_NUM IS NOT NULL

  UNION DISTINCT

  SELECT DISTINCT
    CTE_CVE, CTA_CVE, TRJ_NUM, CTE_CVE AS MATCH_VAL, 'CTE_CVE' AS TYPE_MATCH
  FROM CTA_TRJ_BASE
  WHERE CTE_CVE IS NOT NULL
),
R02 AS (
  SELECT DISTINCT
    M.CTE_CVE, M.CTA_CVE,
    CONCAT(M.TYPE_MATCH, " - ", CAST(M.MATCH_VAL AS STRING)) AS MATCH_KEY,
    R02.MANT_FCH, R02.MANT_HRA, R02.MANT_CDO, R02.MANT_DES,
    R02.DAT_A, R02.DAT_N, 
    R02.VPL_USR, VPL.ID_VPL AS ID, VPL.EMP_NOM AS EMP_NOM, VPL.NOM_PERF, VPL.TDA,
    VPL.FCH_ALT, VPL.FCH_BAJ
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_R02_MOVIMIENTOS_VPL` AS R02
  INNER JOIN R02_MATCH AS M
    ON SAFE_CAST(R02.CTA_CVE AS NUMERIC) = M.MATCH_VAL
  LEFT JOIN USR_VPL AS VPL
    ON R02.VPL_USR = VPL.USR
    AND VPL.FCH_ALT <= R02.MANT_FCH
    AND (VPL.FCH_BAJ IS NULL OR VPL.FCH_BAJ > R02.MANT_FCH)
  WHERE R02.MANT_FCH >= FE_INI
)
SELECT *
FROM R02
ORDER BY DATETIME(MANT_FCH, MANT_HRA)
;

-- ============================================================
-- R05
-- ============================================================
WITH
R05 AS (
  SELECT 
    A.CTA_CVE, TRJ, FCH_MOV, HRA_MOV, 
    COD_MANT, COD_DESC, MANT_DAT_A, MANT_DAT_N, 
    A.USR, VPL.ID_VPL, VPL.EMP_NOM
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_EMBOSSER_MD_R05` AS A
  INNER JOIN CTAS ON A.CTA_CVE = CTAS.CTA_CVE
  LEFT JOIN USR_VPL AS VPL
    ON A.USR = VPL.USR
    AND VPL.FCH_ALT <= A.FCH_MOV
    AND (VPL.FCH_BAJ IS NULL OR VPL.FCH_BAJ > A.FCH_MOV)
  WHERE A.FCH_MOV >= FE_INI
)
SELECT *
FROM R05
ORDER BY DATETIME(FCH_MOV, HRA_MOV)
;

-- ============================================================
-- R09
-- ============================================================
WITH R02_CATALOGO AS (
  SELECT DISTINCT
    SAFE_CAST(MANT_CDO AS NUMERIC) AS MANT_CDO, TRIM(MANT_DES) AS MANT_DES
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_R02_MOVIMIENTOS_VPL`
),
R09_MATCH AS (
  SELECT DISTINCT
    CTA_CVE AS MATCH_VAL, 'CTA_CVE' AS TYPE_MATCH
  FROM CTA_TRJ_BASE
  WHERE CTA_CVE IS NOT NULL

  UNION DISTINCT

  SELECT DISTINCT
   TRJ_NUM AS MATCH_VAL, 'TRJ_NUM' AS TYPE_MATCH
  FROM CTA_TRJ_BASE
  WHERE TRJ_NUM IS NOT NULL

  UNION DISTINCT

  SELECT DISTINCT
    CTE_CVE AS MATCH_VAL, 'CTE_CVE' AS TYPE_MATCH
  FROM CTA_TRJ_BASE
  WHERE CTE_CVE IS NOT NULL
),
R09 AS (
  SELECT DISTINCT
    M.MATCH_VAL,
    CONCAT(M.TYPE_MATCH, " - ", CAST(M.MATCH_VAL AS STRING)) AS MATCH_KEY,
    R09.FCH, R09.HRA, SAFE_CAST(R09.CDE_OCC AS NUMERIC) AS MANT_CDO, TRIM(R09.DES) AS MANT_DES,
    TRIM(R09.DAT_A) AS DAT_A, TRIM(R09.DAT_N) AS DAT_N, TRIM(R09.USR) AS USR,
    VPL.ID_VPL AS ID, VPL.NOM_PERF, VPL.TDA, VPL.TDA_NOM, VPL.FCH_ALT, VPL.FCH_BAJ
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_R09` AS R09
  INNER JOIN R09_MATCH AS M
    ON SAFE_CAST(CONCAT(SAFE_CAST(SAFE_CAST(R09.CTE_CVE AS NUMERIC) AS STRING), IFNULL(LPAD(SAFE_CAST(SAFE_CAST(FLG1 AS INT64) AS STRING), 2, '0'), "")) AS NUMERIC) = M.MATCH_VAL
  LEFT JOIN R02_CATALOGO AS R02X
    ON SAFE_CAST(R09.CDE_OCC AS NUMERIC) = R02X.MANT_CDO
    AND TRIM(R09.DES) = R02X.MANT_DES
  LEFT JOIN USR_VPL AS VPL
    ON TRIM(R09.USR) = VPL.USR
    AND VPL.FCH_ALT <= R09.FCH
    AND (VPL.FCH_BAJ IS NULL OR VPL.FCH_BAJ > R09.FCH)
  WHERE R09.FCH >= FE_INI
    AND R02X.MANT_CDO IS NULL
)
SELECT *
FROM R09
ORDER BY DATETIME(FCH, HRA)
;

-- ============================================================
-- ATM
-- ============================================================
WITH ATM AS (
  SELECT
    B.CTA_CVE, SAFE_CAST(A.NUMERO_DE_TARJETA AS NUMERIC) AS TRJ_NUM, TRIM(A.CAJERO) AS CAJERO,
    FECHA_TRANS AS FCH, HORA_TRANS AS HRA, MONTO / 100 AS IMP, COD_RESP, CIUDAD_DE_TERM AS CIUDAD
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_RETIROS_ATM` AS A
  LEFT JOIN CTA_TRJ_BASE AS B
    ON SAFE_CAST(A.NUMERO_DE_TARJETA AS NUMERIC) = B.TRJ_NUM
  INNER JOIN CTAS AS C
    USING (CTA_CVE)
)
SELECT *
FROM ATM
ORDER BY FCH, HRA
;

DROP TABLE IF EXISTS CTAS;
DROP TABLE IF EXISTS CTA_TRJ_BASE;
DROP TABLE IF EXISTS USR_VPL;
DROP TABLE IF EXISTS VPL_INFO;