-- ============================================================
-- INPUTS
-- ============================================================
DECLARE Q_NOMBRES ARRAY<STRING> DEFAULT [
  'JOEL LOPEZ MATA'
 ];
DECLARE Q_EMAILS ARRAY<STRING> DEFAULT [
  'MORENOMONSERRAT915@GMAIL.COM', 'MMORENOM03@LIVERPOOL.COM.MX', 'MMORENOM03@LIVERPOOL.COM'
];
DECLARE Q_CELS ARRAY<INT64> DEFAULT [
  2283149716,2281067843
];
DECLARE Q_DEVICE_IDS ARRAY<STRING> DEFAULT [
  '346c979e055b0ee8', 'b8b38d40c4f19265', 'b4cde273d8127ca4' 
];

-- ============================================================
-- HELPERS
-- ============================================================
CREATE TEMP FUNCTION ZEROS_TO_NULL(s STRING) AS (
  CASE
    WHEN s IS NULL THEN NULL
    WHEN TRIM(s) = "" THEN NULL
    WHEN REGEXP_CONTAINS(TRIM(s), r"^0+$") THEN NULL
    ELSE TRIM(s)
  END
);
CREATE TEMP FUNCTION NORM_NAME(s STRING) AS (
  NULLIF(TRIM(UPPER(s)), "")
);
CREATE TEMP FUNCTION NORM_EMAIL(s STRING) AS (
  NULLIF(TRIM(LOWER(s)), "")
);
CREATE TEMP FUNCTION NORM_DEVICE(s STRING) AS (
  NULLIF(TRIM(LOWER(s)), "")
);

-- ============================================================
-- INPUT TABLES
-- ============================================================
CREATE TEMP TABLE INPUT_NOMBRES AS
SELECT DISTINCT NORM_NAME(x) AS NOMBRE
FROM UNNEST(Q_NOMBRES) x
WHERE NORM_NAME(x) IS NOT NULL;

CREATE TEMP TABLE INPUT_EMAILS AS
SELECT DISTINCT NORM_EMAIL(x) AS EMAIL
FROM UNNEST(Q_EMAILS) x
WHERE NORM_EMAIL(x) IS NOT NULL;

CREATE TEMP TABLE INPUT_CELS AS
SELECT DISTINCT x AS CEL
FROM UNNEST(Q_CELS) x
WHERE x IS NOT NULL;

CREATE TEMP TABLE INPUT_DEVICE_IDS AS
SELECT DISTINCT NORM_DEVICE(x) AS DEVICE_ID
FROM UNNEST(Q_DEVICE_IDS) x
WHERE NORM_DEVICE(x) IS NOT NULL;


-- ============================================================
-- QUERY VISTA 1) VDIM_CLIE_FTES_VPL
-- ============================================================
WITH
BASE AS (
  SELECT
    CTA_CUSTOMER AS CTE_UNI,
    CTA_CVE AS CUENTA,
    CONCAT(
      TRIM(COALESCE(CTE_NOM, "")), " ",
      TRIM(COALESCE(CTE_APE_PAT, "")), " ",
      TRIM(COALESCE(CTE_APE_MAT, ""))
    ) AS NOMBRE,
    TRIM(CTE_CVE_RFC) AS RFC,
    TRIM(UPPER(CTE_EMA)) AS EMAIL,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL AS STRING)), -10) AS NUMERIC) AS TEL,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_CEL AS STRING)), -10) AS NUMERIC) AS CEL,
    CONCAT(
      TRIM(COALESCE(CTE_DES_DIR_UNO, "")), ", ",
      TRIM(COALESCE(CTE_DES_DIR_DOS, "")), ", ",
      COALESCE(CAST(CDP_CVE AS STRING), ""), ", ",
      TRIM(COALESCE(CTE_DES_CIU, ""))
    ) AS DIRECCION,
    SEX_CVE AS SEXO,
    CTE_FCH_NAC AS FCH_NAC,
    CTE_FCH_ALT AS FCH_APERTURA,
    TRIM(CTE_EMPR) AS EMPLEO,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL_OFI AS STRING)), -10) AS NUMERIC) AS TEL_OFI,
    TRIM(CTE_CONYUGE) AS NOM_CONYUGE,
    TRIM(CTE_NOM_REFERENCIA1) AS NOM_REF1,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL_REFERENCIA1 AS STRING)), -10) AS NUMERIC) AS TEL_REF1,
    TRIM(CTE_NOM_REFERENCIA2) AS NOM_REF2,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL_REFERENCIA2 AS STRING)), -10) AS NUMERIC) AS TEL_REF2
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL`
),
J AS (
  SELECT
    B.*,
    IF(C.CEL IS NOT NULL, 1, 0) AS __hit_cel,
    IF(E.EMAIL IS NOT NULL, 1, 0) AS __hit_email,
    IF(N.NOMBRE IS NOT NULL, 1, 0) AS __hit_nombre,
    CASE
      WHEN C.CEL IS NOT NULL THEN 1
      WHEN E.EMAIL IS NOT NULL THEN 2
      WHEN N.NOMBRE IS NOT NULL THEN 3
      ELSE 9
    END AS __match_pri
  FROM BASE B
  LEFT JOIN INPUT_CELS C
    ON SAFE_CAST(B.CEL AS INT64) = C.CEL
  LEFT JOIN INPUT_EMAILS E
    ON NORM_EMAIL(B.EMAIL) = E.EMAIL
  LEFT JOIN INPUT_NOMBRES N
    ON NORM_NAME(B.NOMBRE) LIKE CONCAT("%", N.NOMBRE, "%")
  WHERE C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL OR N.NOMBRE IS NOT NULL
)
SELECT
  CASE
    WHEN __hit_cel = 1 THEN "CELULAR"
    WHEN __hit_email = 1 THEN "EMAIL"
    WHEN __hit_nombre = 1 THEN "NOMBRE"
    ELSE NULL
  END AS MATCH_TYPE,
  CTE_UNI, CUENTA,
  NOMBRE, RFC,
  EMAIL, TEL, CEL, DIRECCION, SEXO, FCH_NAC,
  FCH_APERTURA,
  NOM_CONYUGE,
  EMPLEO, TEL_OFI,
  NOM_REF1, TEL_REF1,
  NOM_REF2, TEL_REF2
FROM J
QUALIFY
  ROW_NUMBER() OVER(
    PARTITION BY CAST(CTE_UNI AS STRING), CAST(CUENTA AS STRING)
    ORDER BY __match_pri
  ) = 1;

-- ============================================================
-- QUERY VISTA 2) VFAC_APIA
-- ============================================================
WITH
BASE AS (
  SELECT
    BR_SOLIC_CVE AS SOLICITUD,
    BR_CTA_CVE AS CUENTA,
    SAFE_CAST(BR_EMP_PRM AS NUMERIC) AS EMPLEADO1,
    BR_EMP_CVE AS EMPLEADO2,
    SAFE_CAST(BR_TDA_ADM AS NUMERIC) AS TDA_ADMIN,
    SAFE_CAST(BR_TDA_CAP AS NUMERIC) AS TDA_CAPTURA,
    CONCAT(
      TRIM(COALESCE(BR_NOM, "")), " ",
      TRIM(COALESCE(BR_APE_PAT, "")), " ",
      TRIM(COALESCE(BR_APE_MAT, ""))
    ) AS NOMBRE,
    TRIM(BR_EMBOSADO) AS NOM_EMBOSADO,
    TRIM(BR_RFC) AS RFC,
    TRIM(BR_CURP) AS CURP,
    TRIM(CAST(BR_EDAD AS STRING)) AS EDAD,
    TRIM(UPPER(BR_MAIL)) AS EMAIL,
    SAFE_CAST(
      SUBSTR(
        CONCAT(
          COALESCE(ZEROS_TO_NULL(CAST(BR_LADA AS STRING)), ""),
          COALESCE(ZEROS_TO_NULL(CAST(BR_TEL AS STRING)), "")
        ),
        -10
      ) AS NUMERIC
    ) AS TEL,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_CEL AS STRING)), -10) AS NUMERIC) AS CEL,
    CONCAT(
      TRIM(COALESCE(BR_DIR, "")), ", ",
      TRIM(COALESCE(BR_COL, "")), ", ",
      COALESCE(CAST(BR_CDP AS STRING), ""), ", ",
      TRIM(COALESCE(BR_CIU, "")), ", ",
      TRIM(COALESCE(BR_EDO, "")), ", ",
      TRIM(COALESCE(BR_PAIS, ""))
    ) AS DIRECCION,
    TRIM(BR_SEXO) AS SEXO,
    BR_FCH_APE AS FCH_APERTURA,
    TRIM(BR_NOM_CONY) AS NOM_CONYUG,
    BR_FCH_NAC_CONY AS FCH_NAC_CONYUG,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_CEL_CONY AS STRING)), -10) AS NUMERIC) AS CEL_CONYUG,
    TRIM(BR_EMPR_CONY) AS EMP_CONYUG,
    TRIM(BR_EMPR) AS EMPLEO,
    CONCAT(
      TRIM(COALESCE(BR_DIR_EMPR, "")), ", ",
      TRIM(COALESCE(BR_COL_EMPR, "")), ", ",
      TRIM(COALESCE(BR_CDP_EMPR, "")), ", ",
      TRIM(COALESCE(BR_EDO_EMPR, ""))
    ) AS DIR_EMPLEO,
    SAFE_CAST(
      SUBSTR(
        CONCAT(
          COALESCE(ZEROS_TO_NULL(CAST(BR_LADA_OFI AS STRING)), ""),
          COALESCE(ZEROS_TO_NULL(CAST(BR_TEL_OFI AS STRING)), "")
        ),
        -10
      ) AS NUMERIC
    ) AS TEL_OFI,
    TRIM(BR_REF1) AS NOM_REF1,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_TEL_REF1 AS STRING)), -10) AS NUMERIC) AS TEL_REF1,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_CEL_REF1 AS STRING)), -10) AS NUMERIC) AS CEL_REF1,
    TRIM(BR_REF2) AS NOM_REF2,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_TEL_REF2 AS STRING)), -10) AS NUMERIC) AS TEL_REF2,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(BR_CEL_REF2 AS STRING)), -10) AS NUMERIC) AS CEL_REF2
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_APIA`
),
J AS (
  SELECT
    B.*,
    IF(C.CEL IS NOT NULL, 1, 0) AS __hit_cel,
    IF(E.EMAIL IS NOT NULL, 1, 0) AS __hit_email,
    IF(N.NOMBRE IS NOT NULL, 1, 0) AS __hit_nombre,
    CASE
      WHEN C.CEL IS NOT NULL THEN 1
      WHEN E.EMAIL IS NOT NULL THEN 2
      WHEN N.NOMBRE IS NOT NULL THEN 3
      ELSE 9
    END AS __match_pri
  FROM BASE B
  LEFT JOIN INPUT_CELS C
    ON SAFE_CAST(B.CEL AS INT64) = C.CEL
  LEFT JOIN INPUT_EMAILS E
    ON NORM_EMAIL(B.EMAIL) = E.EMAIL
  LEFT JOIN INPUT_NOMBRES N
    ON NORM_NAME(B.NOMBRE) LIKE CONCAT("%", N.NOMBRE, "%")
  WHERE C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL OR N.NOMBRE IS NOT NULL
)
SELECT
  CASE
    WHEN __hit_cel = 1 THEN "CELULAR"
    WHEN __hit_email = 1 THEN "EMAIL"
    WHEN __hit_nombre = 1 THEN "NOMBRE"
    ELSE NULL
  END AS MATCH_TYPE,
  SOLICITUD, CUENTA, EMPLEADO1, EMPLEADO2,
  TDA_ADMIN, TDA_CAPTURA,
  NOMBRE, NOM_EMBOSADO,
  RFC, CURP, EDAD,
  EMAIL, TEL, CEL, DIRECCION, SEXO,
  FCH_APERTURA,
  NOM_CONYUG, FCH_NAC_CONYUG, CEL_CONYUG, EMP_CONYUG,
  EMPLEO, DIR_EMPLEO, TEL_OFI,
  NOM_REF1, TEL_REF1, CEL_REF1,
  NOM_REF2, TEL_REF2, CEL_REF2
FROM J
QUALIFY
  ROW_NUMBER() OVER(
    PARTITION BY CAST(SOLICITUD AS STRING), CAST(CUENTA AS STRING)
    ORDER BY __match_pri
  ) = 1;

-- ============================================================
-- QUERY VISTA 3) VFAC_PREVFRAU_CARDS_APPLY_ONLINE_MC2
-- ============================================================
WITH
BASE AS (
  SELECT
    ID_MC AS ID_MICREDITO,
    ID_CUST AS ID_CUSTOMER,
    CL AS CANAL,
    SAFE_CAST(BR_SOLIC_CVE AS NUMERIC) AS SOLICITUD,
    PROD,
    SYS_FTE AS FUENTE,
    SAFE_CAST(NUM_EMP AS NUMERIC) AS EMPLEADO1,
    SAFE_CAST(NUM_EMP_REF AS NUMERIC) AS EMPLEADO2,
    SAFE_CAST(TDA_APE AS NUMERIC) AS TDA_APERT,
    CONCAT(
      TRIM(COALESCE(CTE_NOM, "")), " ",
      TRIM(COALESCE(CTE_SEG_NOM, "")), " ",
      TRIM(COALESCE(CTE_AP, "")), " ",
      TRIM(COALESCE(CTE_AM, ""))
    ) AS NOMBRE,
    BR_CURP AS CURP,
    BR_RFC AS RFC,
    BR_FCH_NAC AS FCH_NAC,
    USR_EMAIL AS EMAIL,
    BR_CEL AS CEL,
    BR_TEL AS TEL,
    CONCAT(
      TRIM(COALESCE(BR_CALLE, "")), ", ",
      TRIM(COALESCE(BR_NUM_EXT, "")), ", ",
      TRIM(COALESCE(BR_NUM_INT, "")), ", ",
      TRIM(COALESCE(BR_COL, "")), ", ",
      TRIM(COALESCE(BR_DEL, "")), ", ",
      TRIM(COALESCE(BR_CIU, "")), ", ",
      COALESCE(CAST(BR_CDP AS STRING), ""), ", ",
      TRIM(COALESCE(BR_EDO, "")), ", ",
      TRIM(COALESCE(BR_PAIS, ""))
    ) AS DIRECCION,
    BR_SEXO AS SEXO,
    FCH_CAP,
    HRA_CAP,
    FCH_SOLIC,
    SD_ID_VAL AS ID_INCODE,
    CTA_IMP_LIM_CRD AS LIM_CRED,
    TRJ,
    CTA_CVE AS CUENTA
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_CARDS_APPLY_ONLINE_MC2`
),
KEYS AS (
  SELECT
    B.*,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(B.CEL AS STRING)), -10) AS NUMERIC) AS __cel_norm
  FROM BASE B
),
J AS (
  SELECT
    K.*,
    IF(C.CEL IS NOT NULL, 1, 0) AS __hit_cel,
    IF(E.EMAIL IS NOT NULL, 1, 0) AS __hit_email,
    IF(N.NOMBRE IS NOT NULL, 1, 0) AS __hit_nombre,
    CASE
      WHEN C.CEL IS NOT NULL THEN 1
      WHEN E.EMAIL IS NOT NULL THEN 2
      WHEN N.NOMBRE IS NOT NULL THEN 3
      ELSE 9
    END AS __match_pri
  FROM KEYS K
  LEFT JOIN INPUT_CELS C
    ON SAFE_CAST(K.__cel_norm AS INT64) = C.CEL
  LEFT JOIN INPUT_EMAILS E
    ON NORM_EMAIL(K.EMAIL) = E.EMAIL
  LEFT JOIN INPUT_NOMBRES N
    ON NORM_NAME(K.NOMBRE) LIKE CONCAT("%", N.NOMBRE, "%")
  WHERE C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL OR N.NOMBRE IS NOT NULL
)
SELECT
  CASE
    WHEN __hit_cel = 1 THEN "CELULAR"
    WHEN __hit_email = 1 THEN "EMAIL"
    WHEN __hit_nombre = 1 THEN "NOMBRE"
    ELSE NULL
  END AS MATCH_TYPE,
  ID_MICREDITO, ID_CUSTOMER, CANAL, SOLICITUD, CUENTA, PROD, FUENTE,
  EMPLEADO1, EMPLEADO2, TDA_APERT,
  NOMBRE, CURP, RFC, FCH_NAC,
  EMAIL, CEL, TEL, DIRECCION, SEXO,
  FCH_CAP, HRA_CAP, FCH_SOLIC,
  ID_INCODE, LIM_CRED, TRJ
FROM J
QUALIFY
  ROW_NUMBER() OVER(
    PARTITION BY CAST(ID_MICREDITO AS STRING)
    ORDER BY __match_pri
  ) = 1;

-- ============================================================
-- QUERY VISTA 4) VFAC_PREVFRAU_VAL_INCODE
-- ============================================================
WITH
BASE AS (
  SELECT
    UPPER(SD_ID_VAL) AS ID_INCODE,
    SD_FCH_VAL AS FCH_VALIDACION,
    SD_HRA_VAL AS HORA_VALIDACION,
    SD_FCH_ACT_VAL AS FCH_ACT,
    SD_HRA_ACT_VAL AS HORA_ACT,
    TRIM(UPPER(IDC_NAME)) AS NOMBRE,
    CURP_ID AS CURP,
    IDC_FCH_NAC AS FCH_NAC,
    IDC_LUGAR_NAC AS DIR_NAC,
    UPPER(TRIM(EMAIL_CTE)) AS EMAIL,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CEL AS STRING)), -10) AS NUMERIC) AS CEL,
    IDC_DIR AS DIRECCION,
    SD_CONFIG_NOM,
    SD_SCORE_VAL_STT,
    SD_SCORE_VAL,
    IDC_REF_CROPPED_BACK,
    IDC_REF_CROPPED_FRONT,
    IDC_REF_CROPPED_FACE,
    IDC_REF_ORI_BACK,
    IDC_REF_ORI_FRONT,
    IDC_REF_CAP_BACK,
    IDC_REF_CAP_FRONT,
    FC_REF,
    FC_REF_CAP,
    SIGNATURE,
    PID_READABILITY_CHK,
    PID_INC_SCORE_STT,
    PID_IDVALIDATION_OVERAL_STT,
    FR_STT,
    FC_ATTEMPTS,
    FC_OVERALL_STT,
    FC_LIV_SCORE_STT,
    CWL_SCORE,
    RK_ORIG_STT,
    GOV_STT,
    GOV_OVERALL_STT,
    DF_ID,
    DF_TYPE -- <--- NUEVO CAMPO AGREGADO
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VMASTER.VFAC_PREVFRAU_VAL_INCODE`
),
AUX AS (
  SELECT
    B.*,
    CASE
      WHEN B.SD_CONFIG_NOM IN (
        'SBB_SEL', 'LIVERPOOL_INE', 'SBB_SEL_MIN', 'LIV_SEL_JUSTME_TV_INE'
      )
      THEN 'SEL'
      WHEN B.SD_CONFIG_NOM IN (
        'LIV_TAB_INE', 'LIV_TAB_PAS', 'SBB_TAB_INE', 'SBB_TAB_PAS',
        'SBB_TAB_MIN_INE', 'SBB_TAB_MIN_PAS', 'LIV_TAB_BYD_INE', 'LIV_TAB_BYD_PAS'
      ) THEN 'TAB'
      ELSE 'DESCONOCIDO'
    END AS FLUJO_SESION,
    CASE
      WHEN B.CWL_SCORE < 0 THEN 'FAILED'
      WHEN B.CWL_SCORE IS NULL THEN B.RK_ORIG_STT
      WHEN B.CWL_SCORE > 0 THEN 'PASSED'
      ELSE NULL
    END AS STT_WL_RISK,
    CASE
      WHEN (
        B.IDC_REF_CROPPED_BACK IS NULL
        AND B.FC_REF IS NULL
        AND B.IDC_REF_CROPPED_FRONT IS NULL
        AND B.IDC_REF_CROPPED_FACE IS NULL
        AND B.IDC_REF_ORI_BACK IS NULL
        AND B.IDC_REF_ORI_FRONT IS NULL
        AND B.IDC_REF_CAP_BACK IS NULL
        AND B.IDC_REF_CAP_FRONT IS NULL
        AND B.FC_REF_CAP IS NULL
        AND B.SIGNATURE IS NULL
      ) THEN 'DESERTION'
      ELSE B.SD_SCORE_VAL_STT
    END AS CATEGO_TAB
  FROM BASE B
),
SCORING AS (
  SELECT
    A.*,
    -- [Aquí se conserva exactamente igual toda tu lógica extensa de CASE para FLUJO_SESION 'SEL' y 'TAB']
    CASE
      WHEN A.FLUJO_SESION = 'SEL' THEN
        CASE
          WHEN (
            A.IDC_REF_CROPPED_BACK IS NULL
            AND A.FC_REF IS NULL
            AND A.IDC_REF_CROPPED_FRONT IS NULL
            AND A.IDC_REF_CROPPED_FACE IS NULL
            AND A.IDC_REF_ORI_BACK IS NULL
            AND A.IDC_REF_ORI_FRONT IS NULL
            AND A.IDC_REF_CAP_BACK IS NULL
            AND A.IDC_REF_CAP_FRONT IS NULL
            AND A.FC_REF_CAP IS NULL
            AND A.SIGNATURE IS NULL
          )
          OR (
            A.IDC_REF_CROPPED_BACK IS NULL
            AND A.FC_REF IS NULL
            AND A.IDC_REF_CROPPED_FRONT IS NULL
            AND A.IDC_REF_CROPPED_FACE IS NULL
            AND A.IDC_REF_ORI_BACK IS NULL
            AND A.IDC_REF_ORI_FRONT IS NULL
            AND A.IDC_REF_CAP_BACK IS NOT NULL
            AND A.SIGNATURE IS NULL
            AND A.PID_READABILITY_CHK IS NULL
          ) THEN 'DESERTION'
          WHEN A.SD_CONFIG_NOM IN (
            'SBB_SEL', 'LIVERPOOL_INE', 'SBB_SEL_MIN', 'LIV_SEL_JUSTME_TV_INE'
          )
          AND A.FCH_VALIDACION < DATE '2024-05-24'
          AND A.SD_SCORE_VAL_STT IN ('MANUAL_FAIL', 'UNKNOWN', 'FAIL') THEN 'FAIL'
          WHEN A.SD_CONFIG_NOM IN (
            'SBB_SEL', 'LIVERPOOL_INE', 'SBB_SEL_MIN', 'LIV_SEL_JUSTME_TV_INE'
          )
          AND A.FCH_VALIDACION < DATE '2024-05-24'
          AND A.SD_SCORE_VAL_STT IN ('MANUAL_OK', 'MANUAL', 'OK') THEN 'OK'
          WHEN A.SD_CONFIG_NOM IN (
            'SBB_SEL', 'LIVERPOOL_INE', 'SBB_SEL_MIN', 'LIV_SEL_JUSTME_TV_INE'
          )
          AND A.FCH_VALIDACION < DATE '2024-05-24'
          AND A.SD_SCORE_VAL_STT IN ('WARN') THEN 'WARN'
          WHEN A.SD_CONFIG_NOM IN (
            'SBB_SEL', 'LIVERPOOL_INE', 'SBB_SEL_MIN', 'LIV_SEL_JUSTME_TV_INE'
          )
          AND A.FCH_VALIDACION >= DATE '2024-05-24'
          AND A.SD_SCORE_VAL_STT IN ('MANUAL_OK', 'MANUAL', 'OK') THEN 'OK'
          WHEN A.SD_CONFIG_NOM IN (
            'SBB_SEL', 'LIVERPOOL_INE', 'SBB_SEL_MIN', 'LIV_SEL_JUSTME_TV_INE'
          )
          AND A.FCH_VALIDACION >= DATE '2024-05-24'
          AND A.SD_SCORE_VAL_STT IN ('WARN') THEN 'WARN'
          WHEN A.SD_CONFIG_NOM IN (
            'SBB_SEL', 'LIVERPOOL_INE', 'SBB_SEL_MIN', 'LIV_SEL_JUSTME_TV_INE'
          )
          AND A.FCH_VALIDACION >= DATE '2024-05-24'
          AND A.SD_SCORE_VAL_STT NOT IN ('MANUAL_OK', 'MANUAL', 'OK', 'WARN')
          AND (
            A.PID_INC_SCORE_STT IN ('FAIL')
            OR A.PID_IDVALIDATION_OVERAL_STT IN ('FAIL')
            OR A.FR_STT IN ('FAIL')
            OR A.FC_OVERALL_STT IN ('FAIL')
            OR A.FC_LIV_SCORE_STT IN ('FAIL')
            OR A.CWL_SCORE < 0
            OR (
              A.RK_ORIG_STT IN ('FAILED')
              AND (A.CWL_SCORE IS NULL OR A.CWL_SCORE < 0)
            )
          ) THEN 'FAIL'
          WHEN A.SD_CONFIG_NOM IN (
            'SBB_SEL', 'LIVERPOOL_INE', 'SBB_SEL_MIN', 'LIV_SEL_JUSTME_TV_INE'
          )
          AND A.FCH_VALIDACION >= DATE '2024-05-24'
          AND A.SD_SCORE_VAL_STT NOT IN ('MANUAL_OK', 'MANUAL', 'OK', 'WARN')
          AND (
            A.PID_INC_SCORE_STT NOT IN ('FAIL')
            AND A.PID_IDVALIDATION_OVERAL_STT NOT IN ('FAIL')
            AND A.FR_STT NOT IN ('FAIL')
            AND A.FC_OVERALL_STT NOT IN ('FAIL')
            AND A.FC_LIV_SCORE_STT NOT IN ('FAIL')
            AND (
              A.RK_ORIG_STT NOT IN ('FAILED')
              OR (A.RK_ORIG_STT IN ('FAILED') AND A.CWL_SCORE >= 0)
            )
          ) THEN 'OK'
          ELSE 'REVISAR'
        END
      WHEN A.FLUJO_SESION = 'TAB' THEN
        CASE
          WHEN A.CATEGO_TAB IN ('DESERTION') THEN 'DESERTION'
          WHEN A.CATEGO_TAB IN ('OK', 'WARN') THEN 'OK'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NULL
            AND A.PID_INC_SCORE_STT = 'FAIL' THEN 'MODULO ID'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN') THEN 'OK SIN SELFIE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM NOT IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED' THEN 'OK PASS'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT IS NULL
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'OK SIN INE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK IS NULL
            AND A.GOV_STT IS NULL
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'OK SIN INE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = ''
            AND A.GOV_STT IS NULL
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'OK SIN INE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'OK'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO INE - DATOS'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'VALIDATION_ERROR'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO INE - FACIAL'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK IN ('PASSED', '', NULL)
            AND A.GOV_STT = 'INE_NOT_CURRENT'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO INE - NO VIGENTE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'INE_REPORTED_LOST'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO INE - INE PERDIDA'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'MISSING_SELFIE'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO INE - SIN SELFIE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK IN ('PASSED', '')
            AND A.GOV_STT = 'NOT_ENOUGH_DATA'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO INE - DATOS NO ENCONTRADOS'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'PROCESSING_INE'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO INE - PROCESANDO'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK IN ('PASSED', '')
            AND A.GOV_STT = 'USER_NOT_FOUND_IN_INE_DB'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO INE - NO ENCONTRADO'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'INE_CONNECTION_ERROR'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO INE - ERROR CONEXION'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('FAIL')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'OK'
            AND A.GOV_OVERALL_STT = 'OK' THEN 'MODULO FR - LV'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK IS NULL
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'OK SIN RISK Y INE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = ''
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'OK SIN RISK Y INE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK IS NULL
            AND A.GOV_STT = 'VALIDATION_ERROR'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'OK SIN RISK Y FACIAL'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = ''
            AND A.GOV_STT = 'VALIDATION_ERROR'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'OK SIN RISK Y FACIAL'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'OK'
            AND A.GOV_OVERALL_STT = 'OK' THEN 'MODULO RISK'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'OK'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO RISK - INE DATOS'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'VALIDATION_ERROR'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO RISK - INE FACIAL'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'INE_NOT_CURRENT'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO RISK - INE NO VIGENTE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'NOT_ENOUGH_DATA'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO RISK - INE DATOS NO ENCONTRADOS'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'PROCESSING_INE'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO RISK - INE PROCESANDO'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT IN ('INE_CONNECTION_ERROR', 'USER_NOT_FOUND_IN_INE_DB')
            AND A.GOV_OVERALL_STT IN ('UNKNOWN', 'FAIL') THEN 'MODULO RISK - INE NO ENCONTRADO'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT IS NULL
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO RISK - SIN INE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM NOT IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT IS NULL
            AND A.GOV_OVERALL_STT IS NULL THEN 'MODULO RISK'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'OK'
            AND A.FC_LIV_SCORE_STT IN ('FAIL')
            AND A.STT_WL_RISK = '' 
            AND A.GOV_STT IS NULL
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO PV - SIN RISK'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'OK'
            AND A.GOV_OVERALL_STT = 'OK' THEN 'MODULO FR'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'OK'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - INE DATOS'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'VALIDATION_ERROR'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - INE FACIAL'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'INE_NOT_CURRENT'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - INE NO VIGENTE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'NOT_ENOUGH_DATA'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - INE DATOS NO ENCONTRADOS'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'PROCESSING_INE'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - INE PROCESANDO'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT = 'USER_NOT_FOUND_IN_INE_DB'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - INE NO ENCONTRADO'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM NOT IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'PASSED'
            AND A.GOV_STT IS NULL
            AND A.GOV_OVERALL_STT IS NULL THEN 'MODULO FR'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'OK'
            AND A.GOV_OVERALL_STT = 'OK' THEN 'MODULO FR - RISK'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'OK'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - RISK - INE DATOS'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'VALIDATION_ERROR'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - RISK - INE FACIAL'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'PROCESSING_INE'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - RISK - INE PROCESANDO'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT = 'USER_NOT_FOUND_IN_INE_DB'
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - RISK - INE NO ENCONTRADO'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM NOT IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = 'FAILED'
            AND A.GOV_STT IS NULL
            AND A.GOV_OVERALL_STT IS NULL THEN 'MODULO FR - RISK'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('OK', 'WARN')
            AND A.STT_WL_RISK = ''
            AND A.GOV_STT IS NULL
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - SIN RISK - SIN INE'
          WHEN A.CATEGO_TAB NOT IN ('DESERTION', 'OK', 'WARN')
            AND A.FC_ATTEMPTS IS NOT NULL
            AND A.PID_INC_SCORE_STT IN ('OK', 'WARN')
            AND A.SD_CONFIG_NOM IN ('LIV_TAB_INE', 'SBB_TAB_INE', 'SBB_TAB_MIN_INE', 'LIV_TAB_BYD_INE')
            AND A.FR_STT = 'FAIL'
            AND A.FC_LIV_SCORE_STT IN ('FAIL')
            AND A.STT_WL_RISK = ''
            AND A.GOV_STT IS NULL
            AND A.GOV_OVERALL_STT = 'FAIL' THEN 'MODULO FR - PV - SIN RISK - INE DATOS'
          ELSE 'REVISAR'
        END
      ELSE 'DESCONOCIDO'
    END AS ESTATUS
  FROM AUX A
),
J AS (
  SELECT
    B.*,
    IF(D.DEVICE_ID IS NOT NULL, 1, 0) AS __hit_device, -- <--- NUEVO HIT
    IF(C.CEL IS NOT NULL, 1, 0) AS __hit_cel,
    IF(E.EMAIL IS NOT NULL, 1, 0) AS __hit_email,
    IF(N.NOMBRE IS NOT NULL, 1, 0) AS __hit_nombre,
    CASE
      WHEN D.DEVICE_ID IS NOT NULL THEN 1  -- <--- DEVICE_ID PRIORIDAD 1
      WHEN C.CEL IS NOT NULL THEN 2
      WHEN E.EMAIL IS NOT NULL THEN 3
      WHEN N.NOMBRE IS NOT NULL THEN 4
      ELSE 9
    END AS __match_pri
  FROM SCORING B
  LEFT JOIN INPUT_DEVICE_IDS D
    ON TRIM(LOWER(B.DF_ID)) = D.DEVICE_ID
  LEFT JOIN INPUT_CELS C
    ON SAFE_CAST(B.CEL AS INT64) = C.CEL
  LEFT JOIN INPUT_EMAILS E
    ON NORM_EMAIL(B.EMAIL) = E.EMAIL
  LEFT JOIN INPUT_NOMBRES N
    ON NORM_NAME(B.NOMBRE) LIKE CONCAT('%', N.NOMBRE, '%')
  WHERE D.DEVICE_ID IS NOT NULL OR C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL OR N.NOMBRE IS NOT NULL
)
SELECT
  CASE
    WHEN __hit_device = 1 THEN 'DEVICE_ID'
    WHEN __hit_cel = 1 THEN 'CELULAR'
    WHEN __hit_email = 1 THEN 'EMAIL'
    WHEN __hit_nombre = 1 THEN 'NOMBRE'
    ELSE NULL
  END AS MATCH_TYPE,
  FLUJO_SESION,
  ESTATUS,
  ID_INCODE,
  DF_ID,    -- <--- NUEVO CAMPO
  DF_TYPE,  -- <--- NUEVO CAMPO
  FCH_VALIDACION,
  HORA_VALIDACION,
  FCH_ACT,
  HORA_ACT,
  SD_CONFIG_NOM,
  NOMBRE,
  CURP,
  FCH_NAC,
  DIR_NAC,
  EMAIL,
  CEL,
  DIRECCION
FROM J
QUALIFY
  ROW_NUMBER() OVER(
    PARTITION BY CAST(ID_INCODE AS STRING), CAST(FCH_VALIDACION AS STRING), CAST(HORA_VALIDACION AS STRING)
    ORDER BY __match_pri
  ) = 1;


-- ============================================================
-- QUERY VISTA 5) VFAC_PREVFRAU_CUSTOMERS
-- ============================================================
WITH
BASE AS (
  SELECT
    ID_CUSTOMERS,
    CTE_CVE_ATG AS ID_ATG,
    MED AS MON_DIG,
    FCH AS FCH_ALTA,
    HRA AS HORA_ALTA,
    CONCAT(
      TRIM(COALESCE(CTE_NOM, "")), " ",
      TRIM(COALESCE(CTE_AP, "")), " ",
      TRIM(COALESCE(CTE_AM, ""))
    ) AS NOMBRE,
    TRIM(UPPER(USR)) AS EMAIL1,
    TRIM(UPPER(EMAIL)) AS EMAIL2,
    TRIM(UPPER(EMAIL_AUTH0)) AS EMAIL3,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(CTE_TEL_AUTH0 AS STRING)), -10) AS NUMERIC) AS CEL,
    CTE_FCH_NAC AS FCH_NAC,
    BR_SEXO AS SEXO
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_CUSTOMERS`
),
J AS (
  SELECT
    B.*,
    IF(C.CEL IS NOT NULL, 1, 0) AS __hit_cel,
    IF(E.EMAIL IS NOT NULL, 1, 0) AS __hit_email,
    IF(N.NOMBRE IS NOT NULL, 1, 0) AS __hit_nombre,
    CASE
      WHEN C.CEL IS NOT NULL THEN 1
      WHEN E.EMAIL IS NOT NULL THEN 2
      WHEN N.NOMBRE IS NOT NULL THEN 3
      ELSE 9
    END AS __match_pri
  FROM BASE B
  LEFT JOIN INPUT_CELS C
    ON SAFE_CAST(B.CEL AS INT64) = C.CEL
  LEFT JOIN INPUT_EMAILS E
    ON NORM_EMAIL(B.EMAIL1) = E.EMAIL
  LEFT JOIN INPUT_NOMBRES N
    ON NORM_NAME(B.NOMBRE) LIKE CONCAT("%", N.NOMBRE, "%")
  WHERE C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL OR N.NOMBRE IS NOT NULL
)
SELECT
  CASE
    WHEN __hit_cel = 1 THEN "CELULAR"
    WHEN __hit_email = 1 THEN "EMAIL"
    WHEN __hit_nombre = 1 THEN "NOMBRE"
    ELSE NULL
  END AS MATCH_TYPE,
  ID_CUSTOMERS, ID_ATG, MON_DIG,
  FCH_ALTA, HORA_ALTA,
  NOMBRE,
  EMAIL1, EMAIL2, EMAIL3, CEL, FCH_NAC, SEXO
FROM J
QUALIFY
  ROW_NUMBER() OVER(
    PARTITION BY CAST(ID_CUSTOMERS AS STRING)
    ORDER BY __match_pri
  ) = 1;

-- ============================================================
-- QUERY VISTA 6) VFAC_PREVFRAU_REP_OCDT
-- LEFT JOINs de enriquecimiento solo sobre universo filtrado
-- ============================================================
WITH
A_BASE AS (
  SELECT
    CONCAT(A.ANIO, '-', FORMAT('%02d', A.MES)) AS AMES,
    A.ANIO,
    A.MES,
    A.FCH_CAP,
    A.HRA_CAP,
    A.CL,
    A.BRAND,
    A.PROD,
    A.TIP_INF_OCDT,
    SAFE_CAST(A.TDA AS NUMERIC) AS TDA,
    A.ID_OCDT,
    SAFE_CAST(A.BR_SOLIC_CVE AS NUMERIC) AS SOLICITUD,
    SAFE_CAST(A.NUM_EMP AS NUMERIC) AS EMPLEADO1,
    SAFE_CAST(A.NUM_EMP_REF AS NUMERIC) AS EMPLEADO2,
    A.STT_SOL,
    A.STT_SOL_DESC,
    A.PTA,
    NORM_EMAIL(A.USR_EMAIL) AS EMAIL,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(A.CEL AS STRING)), -10) AS NUMERIC) AS CEL,
    NULLIF(TRIM(UPPER(A.BR_CURP)), "") AS CURP,
    NULLIF(TRIM(UPPER(A.BR_RFC)), "") AS RFC,
    A.BR_ING AS INGRESO,

    A.FLG_SW_OTP,
    A.FLG_OTP_EMAIL,
    A.FLG_OTP_SMS,
    CASE
      WHEN A.FLG_OTP_EMAIL = 1 OR A.FLG_OTP_SMS = 1 THEN 1
      WHEN A.FLG_OTP_EMAIL IS NULL AND A.FLG_OTP_SMS IS NULL THEN 1
      ELSE 0
    END AS FLG_AUTH_OTP,
    A.TIP_AUTH_OTP,

    A.TIP_ID,
    IF(
      JSON_EXTRACT_SCALAR(A.INCD_RESP_ID, '$.overall.status') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.INCD_RESP_ID, '$.overall.status'),
      A.INCD_RESP_ID
    ) AS INCD_RESP_ID,
    A.INCD_RESP_CURP,
    A.IDC_TYPE,
    A.CHCKID_SCR,
    A.CHCKID_RES,

    A.SEPOMEX_RESP,
    DATE(A.FCH_REQ_FICO) AS FCH_REQ_FICO,
    A.STT_FICO,
    A.STT_FICO_COD,
    A.STT_FICO_DESC,
    A.FLG_NHIT,

    A.VPL_RESP,
    DATE(SAFE_CAST(JSON_EXTRACT_SCALAR(A.VPL_RESP, '$.data.card.updated') AS DATETIME)) AS FECHA_10,
    TIME(SAFE_CAST(JSON_EXTRACT_SCALAR(A.VPL_RESP, '$.data.card.updated') AS DATETIME)) AS HORA_10,
    A.STT_SOL_VPL,
    NULLIF(TRIM(A.TRJ), "") AS TRJ,
    A.CTA_CVE AS CTA_CVE_RAW,

    A.FC_ATTEMPTS,

    NULLIF(TRIM(UPPER(A.SD_ID_VAL)), "") AS ID_INCODE,
    A.SD_CONFIG_ID,
    A.STT_SOL_INCD,
    A.STT_SOL_INE,
    IF(
      JSON_EXTRACT_SCALAR(A.INCD_FR_RESP, '$.overall.status') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.INCD_FR_RESP, '$.overall.status'),
      A.INCD_FR_RESP
    ) AS INCD_FR_RESP,
    A.N_EXISTING_USER_FLG,
    IF(
      JSON_EXTRACT_SCALAR(A.N_NAMEMATCH_FLG, '$.status') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.N_NAMEMATCH_FLG, '$.status'),
      A.N_NAMEMATCH_FLG
    ) AS N_NAMEMATCH_FLG,
    IF(
      JSON_EXTRACT_SCALAR(A.INCD_LIV_RESP, '$.overall.status') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.INCD_LIV_RESP, '$.overall.status'),
      A.INCD_LIV_RESP
    ) AS INCD_LIV_RESP,
    IF(
      JSON_EXTRACT_SCALAR(A.INCD_CURP_RESP, '$.success') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.INCD_CURP_RESP, '$.success'),
      A.INCD_CURP_RESP
    ) AS INCD_CURP_RESP,
    CASE
      WHEN JSON_EXTRACT_SCALAR(A.INCD_WL_RESP, '$.watchlistScore.value') IS NOT NULL THEN
        CASE
          WHEN SAFE_CAST(JSON_EXTRACT_SCALAR(A.INCD_WL_RESP, '$.watchlistScore.value') AS FLOAT64) < 0 THEN 'FAIL'
          ELSE 'OK'
        END
      ELSE A.INCD_WL_RESP
    END AS INCD_WL_RESP,
    IF(
      JSON_EXTRACT_SCALAR(A.INCD_RISK_RESP, '$.overall.status') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.INCD_RISK_RESP, '$.overall.status'),
      A.INCD_RISK_RESP
    ) AS INCD_RISK_RESP,
    IF(
      JSON_EXTRACT_SCALAR(A.INCD_GOV_RESP, '$.overall.status') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.INCD_GOV_RESP, '$.overall.status'),
      A.INCD_GOV_RESP
    ) AS INCD_GOV_RESP,

    A.ID_PERSON,
    A.REF_ENR,
    A.STT_SOL_FMP,
    IF(
      JSON_EXTRACT_SCALAR(A.FMP_FIND_RESP, '$.registros') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.FMP_FIND_RESP, '$.registros'),
      A.FMP_FIND_RESP
    ) AS FMP_FIND_RESP,
    IF(
      JSON_EXTRACT_SCALAR(A.FMP_AUTH_RESP, '$.result') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.FMP_AUTH_RESP, '$.result'),
      A.FMP_AUTH_RESP
    ) AS FMP_AUTH_RESP,
    IF(
      JSON_EXTRACT_SCALAR(A.FMP_REG_RESP, '$.descripcionRespuesta') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.FMP_REG_RESP, '$.descripcionRespuesta'),
      A.FMP_REG_RESP
    ) AS FMP_REG_RESP,
    IF(
      JSON_EXTRACT_SCALAR(A.FMP_ENR_RESP, '$.responseCode') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.FMP_ENR_RESP, '$.responseCode'),
      A.FMP_ENR_RESP
    ) AS FMP_ENR_RESP,
    IF(
      JSON_EXTRACT_SCALAR(A.FMP_REN_RESP, '$.responseCode') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.FMP_REN_RESP, '$.responseCode'),
      A.FMP_REN_RESP
    ) AS FMP_REN_RESP,
    IF(
      JSON_EXTRACT_SCALAR(A.FMP_INE_RESP, '$.responseCode') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.FMP_INE_RESP, '$.responseCode'),
      A.FMP_INE_RESP
    ) AS FMP_INE_RESP,
    IF(
      JSON_EXTRACT_SCALAR(A.FMP_COM_RESP, '$.estatus') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.FMP_COM_RESP, '$.estatus'),
      A.FMP_COM_RESP
    ) AS FMP_COM_RESP,
    IF(
      JSON_EXTRACT_SCALAR(A.FMP_PER_RESP, '$.resultado') IS NOT NULL,
      JSON_EXTRACT_SCALAR(A.FMP_PER_RESP, '$.resultado'),
      A.FMP_PER_RESP
    ) AS FMP_PER_RESP,

    A.BLQ_TIP,
    A.BLQ_RZN,
    A.STT_SOL_BLQ,

    A.FLG_SES_EXP,
    A.FLG_SES_EXT,
    A.FLG_ERR,
    A.ERR_DESC,
    A.ERR_SERV
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_REP_OCDT` A
  WHERE TRUE
    AND A.SYS_FTE = 'ORI_DIG'
),

KEYS AS (
  SELECT
    B.*,
    SAFE_CAST(SUBSTR(ZEROS_TO_NULL(CAST(B.CEL AS STRING)), -10) AS NUMERIC) AS __cel_norm
  FROM A_BASE B
),

J AS (
  SELECT
    K.*,
    IF(C.CEL IS NOT NULL, 1, 0) AS __hit_cel,
    IF(E.EMAIL IS NOT NULL, 1, 0) AS __hit_email,
    0 AS __hit_nombre,
    CASE
      WHEN C.CEL IS NOT NULL THEN 1
      WHEN E.EMAIL IS NOT NULL THEN 2
      ELSE 9
    END AS __match_pri
  FROM KEYS K
  LEFT JOIN INPUT_CELS C
    ON SAFE_CAST(K.__cel_norm AS INT64) = C.CEL
  LEFT JOIN INPUT_EMAILS E
    ON NORM_EMAIL(K.EMAIL) = E.EMAIL
  WHERE C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL
),

UNIV AS (
  SELECT *
  FROM J
),

SOLICS AS (
  SELECT DISTINCT SOLICITUD
  FROM UNIV
  WHERE SOLICITUD IS NOT NULL
),

C_SRC AS (
  SELECT
    SAFE_CAST(BR_SOLIC_CVE AS NUMERIC) AS SOLICITUD,
    CTA_CVE,
    ANIO,
    MES,
    IF(
      LENGTH(CONCAT(SAFE_CAST(CCR_CVE_BLQ_UNO AS STRING), SAFE_CAST(RAZON_BLQ_UNO_CVE AS STRING))) = 2,
      CONCAT(
        SUBSTR(SAFE_CAST(CCR_CVE_BLQ_UNO AS STRING), 1, 1),
        '/',
        SUBSTR(SAFE_CAST(RAZON_BLQ_UNO_CVE AS STRING), 1, 1)
      ),
      '0/0'
    ) AS BLK1,
    IF(
      LENGTH(CONCAT(SAFE_CAST(CCR_CVE_BLQ_DOS AS STRING), SAFE_CAST(RAZON_BLQ_DOS_CVE AS STRING))) = 2,
      CONCAT(
        SUBSTR(SAFE_CAST(CCR_CVE_BLQ_DOS AS STRING), 1, 1),
        '/',
        SUBSTR(SAFE_CAST(RAZON_BLQ_DOS_CVE AS STRING), 1, 1)
      ),
      '0/0'
    ) AS BLK2
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_SDO_CTA_MES`
  INNER JOIN SOLICS S
    ON SAFE_CAST(BR_SOLIC_CVE AS NUMERIC) = S.SOLICITUD
  WHERE ANIO > 2024
    AND CTA_FCH_SOL >= '2025-01-01'
),

C_DIM AS (
  SELECT
    SOLICITUD,
    CTA_CVE,
    BLK1,
    BLK2
  FROM C_SRC
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CTA_CVE
    ORDER BY ANIO DESC, MES DESC
  ) = 1
),

ENRICHED AS (
  SELECT
    U.ID_OCDT,
    U.SOLICITUD,
    U.EMPLEADO1,
    U.EMPLEADO2,
    CASE
      WHEN U.CTA_CVE_RAW IS NULL AND U.SOLICITUD IS NOT NULL THEN LPAD(SAFE_CAST(C.CTA_CVE AS STRING), 19, '0')
      ELSE LPAD(CAST(U.CTA_CVE_RAW AS STRING), 19, '0')
    END AS CUENTA,
    U.TRJ,
    U.ID_INCODE,
    U.ID_PERSON,
    U.REF_ENR,

    U.AMES,
    U.ANIO,
    U.MES,
    U.FCH_CAP,
    U.HRA_CAP,
    U.FECHA_10,
    U.HORA_10,
    U.FCH_REQ_FICO,

    U.CL,
    U.BRAND,
    U.PROD,
    U.TIP_INF_OCDT,
    U.TDA,
    U.STT_SOL,
    U.STT_SOL_DESC,
    U.PTA,

    U.EMAIL,
    U.CEL,
    U.CURP,
    U.RFC,
    U.INGRESO,

    U.FLG_SW_OTP,
    U.FLG_OTP_EMAIL,
    U.FLG_OTP_SMS,
    U.FLG_AUTH_OTP,
    U.TIP_AUTH_OTP,

    U.TIP_ID,
    U.INCD_RESP_ID,
    U.INCD_RESP_CURP,
    U.IDC_TYPE,
    U.CHCKID_SCR,
    U.CHCKID_RES,

    U.SEPOMEX_RESP,
    U.STT_FICO,
    U.STT_FICO_COD,
    U.STT_FICO_DESC,
    U.FLG_NHIT,

    U.VPL_RESP,
    U.STT_SOL_VPL,
    U.FC_ATTEMPTS,

    U.SD_CONFIG_ID,
    U.STT_SOL_INCD,
    U.STT_SOL_INE,
    U.INCD_FR_RESP,
    U.N_EXISTING_USER_FLG,
    U.N_NAMEMATCH_FLG,
    U.INCD_LIV_RESP,
    U.INCD_CURP_RESP,
    U.INCD_WL_RESP,
    U.INCD_RISK_RESP,
    U.INCD_GOV_RESP,

    U.STT_SOL_FMP,
    U.FMP_FIND_RESP,
    U.FMP_AUTH_RESP,
    U.FMP_REG_RESP,
    U.FMP_ENR_RESP,
    U.FMP_REN_RESP,
    U.FMP_INE_RESP,
    U.FMP_COM_RESP,
    U.FMP_PER_RESP,

    CONCAT(CAST(C.BLK1 AS STRING), '-', CAST(C.BLK2 AS STRING)) AS BLK_ACT,
    CASE
      WHEN C.BLK2 IN ('F/2', 'F/4', 'F/5') THEN 'Bloqueada PF'
      WHEN C.BLK1 IN ('0/0') AND C.BLK2 IN ('0/0') THEN 'Activa'
      WHEN C.BLK1 IS NULL AND C.BLK2 IS NULL THEN NULL
      ELSE 'Bloqueada Otros'
    END AS STT_CTA_ACT,
    U.BLQ_TIP,
    U.BLQ_RZN,
    U.STT_SOL_BLQ,

    U.FLG_SES_EXP,
    U.FLG_SES_EXT,
    U.FLG_ERR,
    U.ERR_DESC,
    U.ERR_SERV,

    U.__hit_cel,
    U.__hit_email,
    U.__hit_nombre,
    U.__match_pri
  FROM UNIV U
  LEFT JOIN C_DIM C
    ON U.SOLICITUD = C.SOLICITUD
)

SELECT
  CASE
    WHEN __hit_cel = 1 THEN 'CELULAR'
    WHEN __hit_email = 1 THEN 'EMAIL'
    WHEN __hit_nombre = 1 THEN 'NOMBRE'
    ELSE NULL
  END AS MATCH_TYPE,

  ID_OCDT,
  SOLICITUD,
  EMPLEADO1,
  EMPLEADO2,
  CUENTA,
  TRJ,
  ID_INCODE,
  ID_PERSON,
  REF_ENR,

  AMES,
  ANIO,
  MES,
  FCH_CAP,
  HRA_CAP,
  FECHA_10,
  HORA_10,
  FCH_REQ_FICO,

  CL,
  BRAND,
  PROD,
  TIP_INF_OCDT,
  TDA,
  STT_SOL,
  STT_SOL_DESC,
  PTA,

  EMAIL,
  CEL,
  CURP,
  RFC,
  INGRESO,

  FLG_SW_OTP,
  FLG_OTP_EMAIL,
  FLG_OTP_SMS,
  FLG_AUTH_OTP,
  TIP_AUTH_OTP,

  TIP_ID,
  INCD_RESP_ID,
  INCD_RESP_CURP,
  IDC_TYPE,
  CHCKID_SCR,
  CHCKID_RES,

  SEPOMEX_RESP,
  STT_FICO,
  STT_FICO_COD,
  STT_FICO_DESC,
  FLG_NHIT,

  VPL_RESP,
  STT_SOL_VPL,
  FC_ATTEMPTS,

  SD_CONFIG_ID,
  STT_SOL_INCD,
  STT_SOL_INE,
  INCD_FR_RESP,
  N_EXISTING_USER_FLG,
  N_NAMEMATCH_FLG,
  INCD_LIV_RESP,
  INCD_CURP_RESP,
  INCD_WL_RESP,
  INCD_RISK_RESP,
  INCD_GOV_RESP,

  STT_SOL_FMP,
  FMP_FIND_RESP,
  FMP_AUTH_RESP,
  FMP_REG_RESP,
  FMP_ENR_RESP,
  FMP_REN_RESP,
  FMP_INE_RESP,
  FMP_COM_RESP,
  FMP_PER_RESP,

  BLK_ACT,
  STT_CTA_ACT,
  BLQ_TIP,
  BLQ_RZN,
  STT_SOL_BLQ,

  FLG_SES_EXP,
  FLG_SES_EXT,
  FLG_ERR,
  ERR_DESC,
  ERR_SERV

FROM ENRICHED
QUALIFY
  ROW_NUMBER() OVER (
    PARTITION BY
      CAST(ID_OCDT AS STRING),
      CAST(SOLICITUD AS STRING),
      CAST(CUENTA AS STRING)
    ORDER BY __match_pri
  ) = 1;


-- -- ============================================================
-- -- INPUTS
-- -- ============================================================
-- DECLARE Q_NOMBRES ARRAY<STRING> DEFAULT [
--   "DALIA STEFANY CRUZ SANCHEZ",
--   "MARIZOL ARELLANO OJEDA"
-- ];
-- DECLARE Q_EMAILS ARRAY<STRING> DEFAULT [
--   "marlenrodriguez.34@gmail.com"
-- ];
-- DECLARE Q_CELS ARRAY<INT64> DEFAULT [
--   5532625424,
--   5525181811,
--   5532980319
-- ];

-- -- ============================================================
-- -- HELPERS
-- -- ============================================================
-- CREATE TEMP FUNCTION ZEROS_TO_NULL_STR(s STRING) AS (
--   CASE
--     WHEN s IS NULL THEN NULL
--     WHEN TRIM(s) = "" THEN NULL
--     WHEN REGEXP_CONTAINS(TRIM(s), r"^0+$") THEN NULL
--     ELSE TRIM(s)
--   END
-- );
-- CREATE TEMP FUNCTION NORM_NAME(s STRING) AS (
--   NULLIF(TRIM(UPPER(s)), "")
-- );
-- CREATE TEMP FUNCTION NORM_EMAIL(s STRING) AS (
--   NULLIF(TRIM(LOWER(s)), "")
-- );

-- -- ============================================================
-- -- INPUT TABLES
-- -- ============================================================
-- WITH
-- INPUT_NOMBRES AS (
--   SELECT DISTINCT NORM_NAME(x) AS NOMBRE
--   FROM UNNEST(Q_NOMBRES) x
--   WHERE NORM_NAME(x) IS NOT NULL
-- ),
-- INPUT_EMAILS AS (
--   SELECT DISTINCT NORM_EMAIL(x) AS EMAIL
--   FROM UNNEST(Q_EMAILS) x
--   WHERE NORM_EMAIL(x) IS NOT NULL
-- ),
-- INPUT_CELS AS (
--   SELECT DISTINCT x AS CEL
--   FROM UNNEST(Q_CELS) x
--   WHERE x IS NOT NULL
-- ),

-- -- ============================================================
-- -- 1) VDIM_CLIE_FTES_VPL
-- -- ============================================================
-- CLIE_BASE AS (
--   SELECT
--     CTA_CUSTOMER AS CTE_UNI,
--     CTA_CVE AS CUENTA,

--     CONCAT(
--       TRIM(COALESCE(CTE_NOM, "")), " ",
--       TRIM(COALESCE(CTE_APE_PAT, "")), " ",
--       TRIM(COALESCE(CTE_APE_MAT, ""))
--     ) AS NOMBRE,

--     TRIM(CTE_CVE_RFC) AS RFC,
--     TRIM(UPPER(CTE_EMA)) AS EMAIL,

--     SAFE_CAST(SUBSTR(ZEROS_TO_NULL_STR(CTE_TEL), -10) AS INT64) AS TEL,
--     SAFE_CAST(SUBSTR(ZEROS_TO_NULL_STR(CTE_CEL), -10) AS INT64) AS CEL,

--     CONCAT(
--       TRIM(COALESCE(CTE_DES_DIR_UNO, "")), ", ",
--       TRIM(COALESCE(CTE_DES_DIR_DOS, "")), ", ",
--       COALESCE(CAST(CDP_CVE AS STRING), ""), ", ",
--       TRIM(COALESCE(CTE_DES_CIU, ""))
--     ) AS DIRECCION,

--     SEX_CVE AS SEXO,
--     CTE_FCH_NAC AS FCH_NAC,
--     CTE_FCH_ALT AS FCH_APERTURA,

--     TRIM(CTE_EMPR) AS EMPLEO,
--     SAFE_CAST(SUBSTR(ZEROS_TO_NULL_STR(CTE_TEL_OFI), -10) AS INT64) AS TEL_OFI,
--     TRIM(CTE_CONYUGE) AS NOM_CONYUGE,

--     TRIM(CTE_NOM_REFERENCIA1) AS NOM_REF1,
--     SAFE_CAST(SUBSTR(ZEROS_TO_NULL_STR(CTE_TEL_REFERENCIA1), -10) AS INT64) AS TEL_REF1,

--     TRIM(CTE_NOM_REFERENCIA2) AS NOM_REF2,
--     SAFE_CAST(SUBSTR(ZEROS_TO_NULL_STR(CTE_TEL_REFERENCIA2), -10) AS INT64) AS TEL_REF2,

--     NORM_NAME(
--       CONCAT(
--         TRIM(COALESCE(CTE_NOM, "")), " ",
--         TRIM(COALESCE(CTE_APE_PAT, "")), " ",
--         TRIM(COALESCE(CTE_APE_MAT, ""))
--       )
--     ) AS NOMBRE_KEY,
--     NORM_EMAIL(CTE_EMA) AS EMAIL_KEY
--   FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL`
-- ),
-- CLIE_HIT AS (
--   SELECT
--     "VDIM_CLIE_FTES_VPL" AS SRC,
--     B.*,

--     MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)) AS FLG_MATCH_CEL,
--     MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)) AS FLG_MATCH_EMAIL,
--     MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)) AS FLG_MATCH_NOMBRE,

--     CASE
--       WHEN MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)) THEN "CELULAR"
--       WHEN MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)) THEN "EMAIL"
--       WHEN MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)) THEN "NOMBRE"
--       ELSE NULL
--     END AS MATCH_TYPE,

--     CASE
--       WHEN MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)) THEN 1
--       WHEN MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)) THEN 2
--       WHEN MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)) THEN 3
--       ELSE NULL
--     END AS MATCH_PRIORITY,

--     ARRAY_TO_STRING(
--       ARRAY_CONCAT(
--         IF(MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)), ["CELULAR"], []),
--         IF(MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)), ["EMAIL"], []),
--         IF(MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)), ["NOMBRE"], [])
--       ),
--       "|"
--     ) AS MATCH_TYPES_ALL
--   FROM CLIE_BASE B
--   LEFT JOIN INPUT_CELS C
--     ON B.CEL = C.CEL
--   LEFT JOIN INPUT_EMAILS E
--     ON B.EMAIL_KEY = E.EMAIL
--   LEFT JOIN INPUT_NOMBRES N
--     ON B.NOMBRE_KEY LIKE CONCAT("%", N.NOMBRE, "%")
--   WHERE C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL OR N.NOMBRE IS NOT NULL
--   QUALIFY
--     ROW_NUMBER() OVER(
--       PARTITION BY CAST(B.CTE_UNI AS STRING), CAST(B.CUENTA AS STRING)
--       ORDER BY
--         CASE
--           WHEN C.CEL IS NOT NULL THEN 1
--           WHEN E.EMAIL IS NOT NULL THEN 2
--           WHEN N.NOMBRE IS NOT NULL THEN 3
--           ELSE 9
--         END
--     ) = 1
-- ),

-- -- ============================================================
-- -- 2) VFAC_APIA (tipos según diccionario; COALESCE solo dentro de CONCAT)
-- -- ============================================================
-- APIA_BASE AS (
--   SELECT
--     BR_SOLIC_CVE AS SOLICITUD,   -- NUMERIC
--     BR_CTA_CVE AS CUENTA,        -- NUMERIC

--     SAFE_CAST(BR_EMP_PRM AS NUMERIC) AS EMPLEADO1,     -- BR_EMP_PRM STRING
--     BR_EMP_CVE AS EMPLEADO2,                           -- NUMERIC
--     SAFE_CAST(BR_TDA_ADM AS NUMERIC) AS TDA_ADMIN,     -- BR_TDA_ADM STRING
--     SAFE_CAST(BR_TDA_CAP AS NUMERIC) AS TDA_CAPTURA,   -- BR_TDA_CAP STRING

--     CONCAT(
--       TRIM(COALESCE(BR_NOM, "")), " ",
--       TRIM(COALESCE(BR_APE_PAT, "")), " ",
--       TRIM(COALESCE(BR_APE_MAT, ""))
--     ) AS NOMBRE,

--     TRIM(BR_EMBOSADO) AS NOM_EMBOSADO,
--     TRIM(BR_RFC) AS RFC,
--     TRIM(BR_CURP) AS CURP,
--     BR_EDAD AS EDAD,                                   -- INT64 (sin TRIM)

--     TRIM(UPPER(BR_MAIL)) AS EMAIL,

--     SAFE_CAST(
--       SUBSTR(
--         CONCAT(
--           COALESCE(ZEROS_TO_NULL_STR(BR_LADA), ""),
--           COALESCE(ZEROS_TO_NULL_STR(BR_TEL), "")
--         ),
--         -10
--       ) AS INT64
--     ) AS TEL,

--     SAFE_CAST(SUBSTR(ZEROS_TO_NULL_STR(BR_CEL), -10) AS INT64) AS CEL,

--     CONCAT(
--       TRIM(COALESCE(BR_DIR, "")), ", ",
--       TRIM(COALESCE(BR_COL, "")), ", ",
--       COALESCE(BR_CDP, ""), ", ",
--       TRIM(COALESCE(BR_CIU, "")), ", ",
--       TRIM(COALESCE(BR_EDO, "")), ", ",
--       TRIM(COALESCE(BR_PAIS, ""))
--     ) AS DIRECCION,

--     TRIM(BR_SEXO) AS SEXO,
--     BR_FCH_APE AS FCH_APERTURA,                         -- DATE

--     TRIM(BR_NOM_CONY) AS NOM_CONYUG,
--     BR_FCH_NAC_CONY AS FCH_NAC_CONYUG,                  -- DATE
--     SAFE_CAST(SUBSTR(CAST(NULLIF(BR_CEL_CONY, 0) AS STRING), -10) AS INT64) AS CEL_CONYUG, -- BR_CEL_CONY NUMERIC
--     TRIM(BR_EMPR_CONY) AS EMP_CONYUG,

--     TRIM(BR_EMPR) AS EMPLEO,
--     CONCAT(
--       TRIM(COALESCE(BR_DIR_EMPR, "")), ", ",
--       TRIM(COALESCE(BR_COL_EMPR, "")), ", ",
--       TRIM(COALESCE(BR_CDP_EMPR, "")), ", ",
--       TRIM(COALESCE(BR_EDO_EMPR, ""))
--     ) AS DIR_EMPLEO,

--     SAFE_CAST(
--       SUBSTR(
--         CONCAT(
--           COALESCE(ZEROS_TO_NULL_STR(BR_LADA_OFI), ""),
--           COALESCE(ZEROS_TO_NULL_STR(BR_TEL_OFI), "")
--         ),
--         -10
--       ) AS INT64
--     ) AS TEL_OFI,

--     TRIM(BR_REF1) AS NOM_REF1,
--     SAFE_CAST(SUBSTR(ZEROS_TO_NULL_STR(BR_TEL_REF1), -10) AS INT64) AS TEL_REF1,          -- BR_TEL_REF1 STRING
--     SAFE_CAST(SUBSTR(CAST(NULLIF(BR_CEL_REF1, 0) AS STRING), -10) AS INT64) AS CEL_REF1,  -- BR_CEL_REF1 NUMERIC

--     TRIM(BR_REF2) AS NOM_REF2,
--     SAFE_CAST(SUBSTR(ZEROS_TO_NULL_STR(BR_TEL_REF2), -10) AS INT64) AS TEL_REF2,          -- BR_TEL_REF2 STRING
--     SAFE_CAST(SUBSTR(CAST(NULLIF(BR_CEL_REF2, 0) AS STRING), -10) AS INT64) AS CEL_REF2,  -- BR_CEL_REF2 NUMERIC

--     NORM_NAME(
--       CONCAT(
--         TRIM(COALESCE(BR_NOM, "")), " ",
--         TRIM(COALESCE(BR_APE_PAT, "")), " ",
--         TRIM(COALESCE(BR_APE_MAT, ""))
--       )
--     ) AS NOMBRE_KEY,
--     NORM_EMAIL(BR_MAIL) AS EMAIL_KEY
--   FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_APIA`
-- ),
-- APIA_HIT AS (
--   SELECT
--     "VFAC_APIA" AS SRC,
--     B.*,

--     MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)) AS FLG_MATCH_CEL,
--     MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)) AS FLG_MATCH_EMAIL,
--     MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)) AS FLG_MATCH_NOMBRE,

--     CASE
--       WHEN MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)) THEN "CELULAR"
--       WHEN MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)) THEN "EMAIL"
--       WHEN MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)) THEN "NOMBRE"
--       ELSE NULL
--     END AS MATCH_TYPE,

--     CASE
--       WHEN MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)) THEN 1
--       WHEN MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)) THEN 2
--       WHEN MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)) THEN 3
--       ELSE NULL
--     END AS MATCH_PRIORITY,

--     ARRAY_TO_STRING(
--       ARRAY_CONCAT(
--         IF(MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)), ["CELULAR"], []),
--         IF(MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)), ["EMAIL"], []),
--         IF(MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)), ["NOMBRE"], [])
--       ),
--       "|"
--     ) AS MATCH_TYPES_ALL
--   FROM APIA_BASE B
--   LEFT JOIN INPUT_CELS C
--     ON B.CEL = C.CEL
--   LEFT JOIN INPUT_EMAILS E
--     ON B.EMAIL_KEY = E.EMAIL
--   LEFT JOIN INPUT_NOMBRES N
--     ON B.NOMBRE_KEY LIKE CONCAT("%", N.NOMBRE, "%")
--   WHERE C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL OR N.NOMBRE IS NOT NULL
--   QUALIFY
--     ROW_NUMBER() OVER(
--       PARTITION BY CAST(B.SOLICITUD AS STRING), CAST(B.CUENTA AS STRING)
--       ORDER BY
--         CASE
--           WHEN C.CEL IS NOT NULL THEN 1
--           WHEN E.EMAIL IS NOT NULL THEN 2
--           WHEN N.NOMBRE IS NOT NULL THEN 3
--           ELSE 9
--         END
--     ) = 1
-- ),

-- -- ============================================================
-- -- 3) CARDS_APPLY_ONLINE_MC2 (tipos según diccionario; sin “higiene extra”)
-- -- ============================================================
-- CARDS_BASE AS (
--   SELECT
--     ID_MC AS ID_MICREDITO,      -- INT64
--     ID_CUST AS ID_CUSTOMER,     -- NUMERIC
--     CL AS CANAL,
--     BR_SOLIC_CVE AS SOLICITUD,  -- STRING según diccionario (sin SAFE_CAST)
--     CTA_CVE AS CUENTA,          -- STRING

--     CONCAT(
--       TRIM(COALESCE(CTE_NOM, "")), " ",
--       TRIM(COALESCE(CTE_SEG_NOM, "")), " ",
--       TRIM(COALESCE(CTE_AP, "")), " ",
--       TRIM(COALESCE(CTE_AM, ""))
--     ) AS NOMBRE,

--     BR_CURP AS CURP,
--     BR_RFC AS RFC,
--     BR_FCH_NAC AS FCH_NAC,      -- DATE

--     USR_EMAIL AS EMAIL,
--     BR_CEL AS CEL_RAW,
--     BR_TEL AS TEL_RAW,

--     CONCAT(
--       TRIM(COALESCE(BR_CALLE, "")), ", ",
--       TRIM(COALESCE(BR_NUM_EXT, "")), ", ",
--       TRIM(COALESCE(BR_NUM_INT, "")), ", ",
--       TRIM(COALESCE(BR_COL, "")), ", ",
--       TRIM(COALESCE(BR_DEL, "")), ", ",
--       TRIM(COALESCE(BR_CIU, "")), ", ",
--       COALESCE(BR_CDP, ""), ", ",
--       TRIM(COALESCE(BR_EDO, "")), ", ",
--       TRIM(COALESCE(BR_PAIS, ""))
--     ) AS DIRECCION,

--     BR_SEXO AS SEXO,
--     FCH_CAP,
--     HRA_CAP,
--     FCH_SOLIC,
--     SD_ID_VAL AS ID_INCODE,

--     SAFE_CAST(SUBSTR(ZEROS_TO_NULL_STR(BR_CEL), -10) AS INT64) AS CEL,
--     NORM_EMAIL(USR_EMAIL) AS EMAIL_KEY,
--     NORM_NAME(
--       CONCAT(
--         TRIM(COALESCE(CTE_NOM, "")), " ",
--         TRIM(COALESCE(CTE_SEG_NOM, "")), " ",
--         TRIM(COALESCE(CTE_AP, "")), " ",
--         TRIM(COALESCE(CTE_AM, ""))
--       )
--     ) AS NOMBRE_KEY
--   FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_CARDS_APPLY_ONLINE_MC2`
-- ),
-- CARDS_HIT AS (
--   SELECT
--     "VFAC_PREVFRAU_CARDS_APPLY_ONLINE_MC2" AS SRC,
--     B.*,

--     MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)) AS FLG_MATCH_CEL,
--     MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)) AS FLG_MATCH_EMAIL,
--     MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)) AS FLG_MATCH_NOMBRE,

--     CASE
--       WHEN MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)) THEN "CELULAR"
--       WHEN MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)) THEN "EMAIL"
--       WHEN MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)) THEN "NOMBRE"
--       ELSE NULL
--     END AS MATCH_TYPE,

--     CASE
--       WHEN MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)) THEN 1
--       WHEN MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)) THEN 2
--       WHEN MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)) THEN 3
--       ELSE NULL
--     END AS MATCH_PRIORITY,

--     ARRAY_TO_STRING(
--       ARRAY_CONCAT(
--         IF(MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)), ["CELULAR"], []),
--         IF(MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)), ["EMAIL"], []),
--         IF(MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_MICREDITO AS STRING)), ["NOMBRE"], [])
--       ),
--       "|"
--     ) AS MATCH_TYPES_ALL
--   FROM CARDS_BASE B
--   LEFT JOIN INPUT_CELS C
--     ON B.CEL = C.CEL
--   LEFT JOIN INPUT_EMAILS E
--     ON B.EMAIL_KEY = E.EMAIL
--   LEFT JOIN INPUT_NOMBRES N
--     ON B.NOMBRE_KEY LIKE CONCAT("%", N.NOMBRE, "%")
--   WHERE C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL OR N.NOMBRE IS NOT NULL
--   QUALIFY
--     ROW_NUMBER() OVER(
--       PARTITION BY CAST(B.ID_MICREDITO AS STRING)
--       ORDER BY
--         CASE
--           WHEN C.CEL IS NOT NULL THEN 1
--           WHEN E.EMAIL IS NOT NULL THEN 2
--           WHEN N.NOMBRE IS NOT NULL THEN 3
--           ELSE 9
--         END
--     ) = 1
-- ),

-- -- ============================================================
-- -- 4) INCODE (VAL_INCODE lo manejas tú; lo dejo intacto aquí)
-- -- ============================================================
-- INCODE_BASE AS (
--   SELECT
--     UPPER(SD_ID_VAL) AS ID_INCODE,
--     SD_FCH_VAL AS FCH_VALIDACION,
--     SD_HRA_VAL AS HORA_VALIDACION,
--     SD_FCH_ACT_VAL AS FCH_ACT,
--     SD_HRA_ACT_VAL AS HORA_ACT,

--     TRIM(UPPER(IDC_NAME)) AS NOMBRE,
--     CURP_ID AS CURP,
--     IDC_FCH_NAC AS FCH_NAC,
--     IDC_LUGAR_NAC AS DIR_NAC,

--     UPPER(TRIM(EMAIL_CTE)) AS EMAIL,
--     SAFE_CAST(SUBSTR(TRIM(CEL), -10) AS INT64) AS CEL,
--     IDC_DIR AS DIRECCION,

--     NORM_NAME(IDC_NAME) AS NOMBRE_KEY,
--     NORM_EMAIL(EMAIL_CTE) AS EMAIL_KEY
--   FROM `crp-pro-dwh-semanticagold.EIL_DP_VMASTER.VFAC_PREVFRAU_VAL_INCODE`
-- ),
-- INCODE_HIT AS (
--   SELECT
--     "VFAC_PREVFRAU_VAL_INCODE" AS SRC,
--     B.*,

--     MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)) AS FLG_MATCH_CEL,
--     MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)) AS FLG_MATCH_EMAIL,
--     MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)) AS FLG_MATCH_NOMBRE,

--     CASE
--       WHEN MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)) THEN "CELULAR"
--       WHEN MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)) THEN "EMAIL"
--       WHEN MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)) THEN "NOMBRE"
--       ELSE NULL
--     END AS MATCH_TYPE,

--     CASE
--       WHEN MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)) THEN 1
--       WHEN MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)) THEN 2
--       WHEN MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)) THEN 3
--       ELSE NULL
--     END AS MATCH_PRIORITY,

--     ARRAY_TO_STRING(
--       ARRAY_CONCAT(
--         IF(MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)), ["CELULAR"], []),
--         IF(MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)), ["EMAIL"], []),
--         IF(MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)), ["NOMBRE"], [])
--       ),
--       "|"
--     ) AS MATCH_TYPES_ALL
--   FROM INCODE_BASE B
--   LEFT JOIN INPUT_CELS C
--     ON B.CEL = C.CEL
--   LEFT JOIN INPUT_EMAILS E
--     ON B.EMAIL_KEY = E.EMAIL
--   LEFT JOIN INPUT_NOMBRES N
--     ON B.NOMBRE_KEY LIKE CONCAT("%", N.NOMBRE, "%")
--   WHERE C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL OR N.NOMBRE IS NOT NULL
--   QUALIFY
--     ROW_NUMBER() OVER(
--       PARTITION BY CAST(B.ID_INCODE AS STRING), CAST(B.FCH_VALIDACION AS STRING), CAST(B.HORA_VALIDACION AS STRING)
--       ORDER BY
--         CASE
--           WHEN C.CEL IS NOT NULL THEN 1
--           WHEN E.EMAIL IS NOT NULL THEN 2
--           WHEN N.NOMBRE IS NOT NULL THEN 3
--           ELSE 9
--         END
--     ) = 1
-- ),

-- -- ============================================================
-- -- 5) VFAC_PREVFRAU_CUSTOMERS (tipos según diccionario; COALESCE solo dentro de CONCAT)
-- -- ============================================================
-- CUST_BASE AS (
--   SELECT
--     ID_CUSTOMERS,               -- INT64
--     CTE_CVE_ATG AS ID_ATG,       -- INT64
--     MED AS MON_DIG,

--     FCH AS FCH_ALTA,
--     HRA AS HORA_ALTA,

--     CONCAT(
--       TRIM(COALESCE(CTE_NOM, "")), " ",
--       TRIM(COALESCE(CTE_AP, "")), " ",
--       TRIM(COALESCE(CTE_AM, ""))
--     ) AS NOMBRE,

--     TRIM(UPPER(USR)) AS EMAIL1,
--     TRIM(UPPER(EMAIL)) AS EMAIL2,
--     TRIM(UPPER(EMAIL_AUTH0)) AS EMAIL3,

--     SAFE_CAST(SUBSTR(ZEROS_TO_NULL_STR(CTE_TEL_AUTH0), -10) AS INT64) AS CEL,  -- CTE_TEL_AUTH0 STRING
--     CTE_FCH_NAC AS FCH_NAC,                                            -- DATE
--     BR_SEXO AS SEXO,

--     NORM_EMAIL(USR) AS EMAIL_KEY,
--     NORM_NAME(
--       CONCAT(
--         TRIM(COALESCE(CTE_NOM, "")), " ",
--         TRIM(COALESCE(CTE_AP, "")), " ",
--         TRIM(COALESCE(CTE_AM, ""))
--       )
--     ) AS NOMBRE_KEY
--   FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_CUSTOMERS`
-- ),
-- CUST_HIT AS (
--   SELECT
--     "VFAC_PREVFRAU_CUSTOMERS" AS SRC,
--     B.*,

--     MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)) AS FLG_MATCH_CEL,
--     MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)) AS FLG_MATCH_EMAIL,
--     MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)) AS FLG_MATCH_NOMBRE,

--     CASE
--       WHEN MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)) THEN "CELULAR"
--       WHEN MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)) THEN "EMAIL"
--       WHEN MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)) THEN "NOMBRE"
--       ELSE NULL
--     END AS MATCH_TYPE,

--     CASE
--       WHEN MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)) THEN 1
--       WHEN MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)) THEN 2
--       WHEN MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)) THEN 3
--       ELSE NULL
--     END AS MATCH_PRIORITY,

--     ARRAY_TO_STRING(
--       ARRAY_CONCAT(
--         IF(MAX(C.CEL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)), ["CELULAR"], []),
--         IF(MAX(E.EMAIL IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)), ["EMAIL"], []),
--         IF(MAX(N.NOMBRE IS NOT NULL) OVER(PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)), ["NOMBRE"], [])
--       ),
--       "|"
--     ) AS MATCH_TYPES_ALL
--   FROM CUST_BASE B
--   LEFT JOIN INPUT_CELS C
--     ON B.CEL = C.CEL
--   LEFT JOIN INPUT_EMAILS E
--     ON B.EMAIL_KEY = E.EMAIL
--   LEFT JOIN INPUT_NOMBRES N
--     ON B.NOMBRE_KEY LIKE CONCAT("%", N.NOMBRE, "%")
--   WHERE C.CEL IS NOT NULL OR E.EMAIL IS NOT NULL OR N.NOMBRE IS NOT NULL
--   QUALIFY
--     ROW_NUMBER() OVER(
--       PARTITION BY CAST(B.ID_CUSTOMERS AS STRING)
--       ORDER BY
--         CASE
--           WHEN C.CEL IS NOT NULL THEN 1
--           WHEN E.EMAIL IS NOT NULL THEN 2
--           WHEN N.NOMBRE IS NOT NULL THEN 3
--           ELSE 9
--         END
--     ) = 1
-- ),

-- -- ============================================================
-- -- OUTPUT UNIFICADO (tipos consistentes en UNION)
-- --  - FCH_NAC => STRING
-- --  - FCH_APERTURA => STRING
-- -- ============================================================
-- OUT_CLIE AS (
--   SELECT
--     SRC, MATCH_TYPE, MATCH_PRIORITY, MATCH_TYPES_ALL,
--     FLG_MATCH_CEL, FLG_MATCH_EMAIL, FLG_MATCH_NOMBRE,

--     CAST(NULL AS STRING) AS ID_MICREDITO,
--     CAST(CTE_UNI AS STRING) AS ID_CUSTOMER,
--     CAST(NULL AS STRING) AS ID_INCODE,
--     CAST(NULL AS STRING) AS ID_ATG,
--     CAST(NULL AS STRING) AS MON_DIG,
--     CAST(NULL AS STRING) AS CANAL,
--     CAST(NULL AS STRING) AS SOLICITUD,
--     CAST(CUENTA AS STRING) AS CUENTA,

--     NOMBRE, RFC, CAST(NULL AS STRING) AS CURP, EMAIL,
--     TEL, CEL,
--     DIRECCION, SEXO,
--     CAST(FCH_NAC AS STRING) AS FCH_NAC,
--     CAST(FCH_APERTURA AS STRING) AS FCH_APERTURA,

--     TO_JSON_STRING(STRUCT(
--       CTE_UNI, CUENTA, NOMBRE, RFC, EMAIL, TEL, CEL, DIRECCION, SEXO, FCH_NAC, FCH_APERTURA,
--       EMPLEO, TEL_OFI, NOM_CONYUGE, NOM_REF1, TEL_REF1, NOM_REF2, TEL_REF2
--     )) AS ROW_JSON
--   FROM CLIE_HIT
-- ),
-- OUT_APIA AS (
--   SELECT
--     SRC, MATCH_TYPE, MATCH_PRIORITY, MATCH_TYPES_ALL,
--     FLG_MATCH_CEL, FLG_MATCH_EMAIL, FLG_MATCH_NOMBRE,

--     CAST(NULL AS STRING) AS ID_MICREDITO,
--     CAST(NULL AS STRING) AS ID_CUSTOMER,
--     CAST(NULL AS STRING) AS ID_INCODE,
--     CAST(NULL AS STRING) AS ID_ATG,
--     CAST(NULL AS STRING) AS MON_DIG,
--     CAST(NULL AS STRING) AS CANAL,
--     CAST(SOLICITUD AS STRING) AS SOLICITUD,
--     CAST(CUENTA AS STRING) AS CUENTA,

--     NOMBRE, RFC, CURP, EMAIL,
--     TEL, CEL,
--     DIRECCION, SEXO,
--     CAST(NULL AS STRING) AS FCH_NAC,
--     CAST(FCH_APERTURA AS STRING) AS FCH_APERTURA,

--     TO_JSON_STRING(STRUCT(
--       SOLICITUD, CUENTA, EMPLEADO1, EMPLEADO2, TDA_ADMIN, TDA_CAPTURA,
--       NOMBRE, NOM_EMBOSADO, RFC, CURP, EDAD,
--       EMAIL, TEL, CEL, DIRECCION, SEXO, FCH_APERTURA,
--       NOM_CONYUG, FCH_NAC_CONYUG, CEL_CONYUG, EMP_CONYUG,
--       EMPLEO, DIR_EMPLEO, TEL_OFI,
--       NOM_REF1, TEL_REF1, CEL_REF1,
--       NOM_REF2, TEL_REF2, CEL_REF2
--     )) AS ROW_JSON
--   FROM APIA_HIT
-- ),
-- OUT_CARDS AS (
--   SELECT
--     SRC, MATCH_TYPE, MATCH_PRIORITY, MATCH_TYPES_ALL,
--     FLG_MATCH_CEL, FLG_MATCH_EMAIL, FLG_MATCH_NOMBRE,

--     CAST(ID_MICREDITO AS STRING) AS ID_MICREDITO,
--     CAST(ID_CUSTOMER AS STRING) AS ID_CUSTOMER,
--     CAST(ID_INCODE AS STRING) AS ID_INCODE,
--     CAST(NULL AS STRING) AS ID_ATG,
--     CAST(NULL AS STRING) AS MON_DIG,
--     CAST(CANAL AS STRING) AS CANAL,
--     CAST(SOLICITUD AS STRING) AS SOLICITUD,
--     CAST(CUENTA AS STRING) AS CUENTA,

--     NOMBRE, RFC, CURP, CAST(EMAIL AS STRING) AS EMAIL,
--     CAST(NULL AS INT64) AS TEL, CEL,
--     DIRECCION, CAST(SEXO AS STRING) AS SEXO,
--     CAST(FCH_NAC AS STRING) AS FCH_NAC,
--     CAST(NULL AS STRING) AS FCH_APERTURA,

--     TO_JSON_STRING(STRUCT(
--       ID_MICREDITO, ID_CUSTOMER, CANAL, SOLICITUD, CUENTA,
--       NOMBRE, CURP, RFC, FCH_NAC, EMAIL, CEL_RAW, TEL_RAW, DIRECCION, SEXO,
--       FCH_CAP, HRA_CAP, FCH_SOLIC, ID_INCODE
--     )) AS ROW_JSON
--   FROM CARDS_HIT
-- ),
-- OUT_INCODE AS (
--   SELECT
--     SRC, MATCH_TYPE, MATCH_PRIORITY, MATCH_TYPES_ALL,
--     FLG_MATCH_CEL, FLG_MATCH_EMAIL, FLG_MATCH_NOMBRE,

--     CAST(NULL AS STRING) AS ID_MICREDITO,
--     CAST(NULL AS STRING) AS ID_CUSTOMER,
--     CAST(ID_INCODE AS STRING) AS ID_INCODE,
--     CAST(NULL AS STRING) AS ID_ATG,
--     CAST(NULL AS STRING) AS MON_DIG,
--     CAST(NULL AS STRING) AS CANAL,
--     CAST(NULL AS STRING) AS SOLICITUD,
--     CAST(NULL AS STRING) AS CUENTA,

--     NOMBRE, CAST(NULL AS STRING) AS RFC, CURP, EMAIL,
--     CAST(NULL AS INT64) AS TEL, CEL,
--     DIRECCION, CAST(NULL AS STRING) AS SEXO,
--     CAST(FCH_NAC AS STRING) AS FCH_NAC,
--     CAST(NULL AS STRING) AS FCH_APERTURA,

--     TO_JSON_STRING(STRUCT(
--       ID_INCODE, FCH_VALIDACION, HORA_VALIDACION, FCH_ACT, HORA_ACT,
--       NOMBRE, CURP, FCH_NAC, DIR_NAC, EMAIL, CEL, DIRECCION
--     )) AS ROW_JSON
--   FROM INCODE_HIT
-- ),
-- OUT_CUSTOMERS AS (
--   SELECT
--     SRC, MATCH_TYPE, MATCH_PRIORITY, MATCH_TYPES_ALL,
--     FLG_MATCH_CEL, FLG_MATCH_EMAIL, FLG_MATCH_NOMBRE,

--     CAST(NULL AS STRING) AS ID_MICREDITO,
--     CAST(ID_CUSTOMERS AS STRING) AS ID_CUSTOMER,
--     CAST(NULL AS STRING) AS ID_INCODE,
--     CAST(ID_ATG AS STRING) AS ID_ATG,
--     CAST(MON_DIG AS STRING) AS MON_DIG,
--     CAST(NULL AS STRING) AS CANAL,
--     CAST(NULL AS STRING) AS SOLICITUD,
--     CAST(NULL AS STRING) AS CUENTA,

--     NOMBRE, CAST(NULL AS STRING) AS RFC, CAST(NULL AS STRING) AS CURP, EMAIL1 AS EMAIL,
--     CAST(NULL AS INT64) AS TEL, CEL,
--     CAST(NULL AS STRING) AS DIRECCION, CAST(SEXO AS STRING) AS SEXO,
--     CAST(FCH_NAC AS STRING) AS FCH_NAC,
--     CAST(NULL AS STRING) AS FCH_APERTURA,

--     TO_JSON_STRING(STRUCT(
--       ID_CUSTOMERS, ID_ATG, MON_DIG, FCH_ALTA, HORA_ALTA,
--       NOMBRE, EMAIL1, EMAIL2, EMAIL3, CEL, FCH_NAC, SEXO
--     )) AS ROW_JSON
--   FROM CUST_HIT
-- )

-- SELECT *
-- FROM (
--   SELECT * FROM OUT_CLIE
--   UNION ALL
--   SELECT * FROM OUT_APIA
--   UNION ALL
--   SELECT * FROM OUT_CARDS
--   UNION ALL
--   SELECT * FROM OUT_INCODE
--   UNION ALL
--   SELECT * FROM OUT_CUSTOMERS
-- )
-- ORDER BY
--   SRC,
--   MATCH_PRIORITY,
--   SOLICITUD,
--   CUENTA,
--   ID_MICREDITO,
--   ID_INCODE,
--   ID_CUSTOMER;