CREATE TEMP TABLE FMS AS (
  WITH BASE AS (
    SELECT
      SAFE_CAST(FMS.NUM_TARJETA AS NUMERIC) AS TRJ,
      FMS_TX_ID, ATG_TX_ID, ATG_ORDER_ID, ATG_SG_ID, BC_TX_ID, FECHA_CREACION, FECHA_PROCESAMIENTO, TOTAL_ORDEN,
      TOTAL_COBRADO, TOTAL_ENVIADO, PEDIDO, REMISION, TIENDA, NOMBRE_TIENDA, TIPO_USUARIO,
      CORREO_ELECTRONICO, NOMBRE_CLIENTE, CANAL_VENTA, TIPO_PAGO, TIPO_TARJETA, USO_MED, NUMERO_MED_PAGO, NUMERO_MED_ABONO,
      MKP, PROVEEDOR_MKP, TIPO_PRODUCTO, SECCION, GRUPO_ART, SKU, CANTIDAD, MONTO_ENVIADO_TARJETA,
      MONTO_COBRADO_TARJETA, MONTO_ENVIADO_MED, MONTO_COBRADO_MED, MOTO_ABONO_MED, ESTATUS_CYB, FECHA_VALIDACION_CYB, ESTATUS_ATG,
      AUTORIZACION_PAYPAL, AUT_BANCARIA_FOLIO_PAYPAL, AUTORIZACION_MED, INSTANCIA, SITE
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_FMS_REPORT_CAMBIO` AS FMS
    WHERE TRUE
      AND (
        LOWER(TRIM(FMS.CORREO_ELECTRONICO)) IN ("gegonzalezc@liverpool.com.mx")
        OR SAFE_CAST(FMS.NUM_TARJETA AS NUMERIC) IN (4178490095775889,4178490086745560,4178490081025067,5300000090850502,1300001876576305,1300001343645104,4178490039824256,1300007830225901,4178498067876718,1300000925318304,5300000090850502,1300007952622901)
      )
  )

  SELECT
    STRING_AGG(DISTINCT SAFE_CAST(TRJ AS STRING), '\n' ORDER BY SAFE_CAST(TRJ AS STRING)) AS TRJ,
    FMS_TX_ID, 
    STRING_AGG(
      CONCAT(
            'SKU= ', SAFE_CAST(SKU AS STRING),
            ' | SEC=', IFNULL(SAFE_CAST(SECCION AS STRING), ''),
            ' | GRP=', IFNULL(SAFE_CAST(GRUPO_ART AS STRING), ''),
            ' | COB=', IFNULL(SAFE_CAST(TOTAL_COBRADO AS STRING), ''),
            ' | ENV=', IFNULL(SAFE_CAST(TOTAL_ENVIADO AS STRING), ''),
            ' | QTY=', IFNULL(SAFE_CAST(CANTIDAD AS STRING), '')
          ) 
      , '\n' ORDER BY SKU) AS PRODUCTS,
    STRING_AGG(DISTINCT SAFE_CAST(ATG_TX_ID AS STRING), '\n' ORDER BY SAFE_CAST(ATG_TX_ID AS STRING)) AS ATG_TX_ID,
    STRING_AGG(DISTINCT SAFE_CAST(ATG_ORDER_ID AS STRING), '\n' ORDER BY SAFE_CAST(ATG_ORDER_ID AS STRING)) AS ATG_ORDER_ID,
    STRING_AGG(DISTINCT SAFE_CAST(ATG_SG_ID AS STRING), '\n' ORDER BY SAFE_CAST(ATG_SG_ID AS STRING)) AS ATG_SG_ID,
    STRING_AGG(DISTINCT SAFE_CAST(BC_TX_ID AS STRING), '\n' ORDER BY SAFE_CAST(BC_TX_ID AS STRING)) AS BC_TX_ID,
    STRING_AGG(DISTINCT SAFE_CAST(FECHA_CREACION AS STRING), '\n' ORDER BY SAFE_CAST(FECHA_CREACION AS STRING)) AS FECHA_CREACION,
    STRING_AGG(DISTINCT SAFE_CAST(FECHA_PROCESAMIENTO AS STRING), '\n' ORDER BY SAFE_CAST(FECHA_PROCESAMIENTO AS STRING)) AS FECHA_PROCESAMIENTO,
    STRING_AGG(DISTINCT SAFE_CAST(TOTAL_ORDEN AS STRING), '\n' ORDER BY SAFE_CAST(TOTAL_ORDEN AS STRING)) AS TOTAL_ORDEN,
    STRING_AGG(DISTINCT SAFE_CAST(PEDIDO AS STRING), '\n' ORDER BY SAFE_CAST(PEDIDO AS STRING)) AS PEDIDO,
    STRING_AGG(DISTINCT SAFE_CAST(REMISION AS STRING), '\n' ORDER BY SAFE_CAST(REMISION AS STRING)) AS REMISION,
    STRING_AGG(DISTINCT SAFE_CAST(TIENDA AS STRING), '\n' ORDER BY SAFE_CAST(TIENDA AS STRING)) AS TIENDA,
    STRING_AGG(DISTINCT SAFE_CAST(NOMBRE_TIENDA AS STRING), '\n' ORDER BY SAFE_CAST(NOMBRE_TIENDA AS STRING)) AS NOMBRE_TIENDA,
    STRING_AGG(DISTINCT SAFE_CAST(CORREO_ELECTRONICO AS STRING), '\n' ORDER BY SAFE_CAST(CORREO_ELECTRONICO AS STRING)) AS CORREO_ELECTRONICO,
    STRING_AGG(DISTINCT SAFE_CAST(NOMBRE_CLIENTE AS STRING), '\n' ORDER BY SAFE_CAST(NOMBRE_CLIENTE AS STRING)) AS NOMBRE_CLIENTE,
    STRING_AGG(DISTINCT SAFE_CAST(CANAL_VENTA AS STRING), '\n' ORDER BY SAFE_CAST(CANAL_VENTA AS STRING)) AS CANAL_VENTA,
    STRING_AGG(DISTINCT SAFE_CAST(TIPO_PAGO AS STRING), '\n' ORDER BY SAFE_CAST(TIPO_PAGO AS STRING)) AS TIPO_PAGO,
    STRING_AGG(DISTINCT SAFE_CAST(TIPO_TARJETA AS STRING), '\n' ORDER BY SAFE_CAST(TIPO_TARJETA AS STRING)) AS TIPO_TARJETA,
    STRING_AGG(DISTINCT SAFE_CAST(USO_MED AS STRING), '\n' ORDER BY SAFE_CAST(USO_MED AS STRING)) AS USO_MED,
    STRING_AGG(DISTINCT SAFE_CAST(NUMERO_MED_PAGO AS STRING), '\n' ORDER BY SAFE_CAST(NUMERO_MED_PAGO AS STRING)) AS NUMERO_MED_PAGO,
    STRING_AGG(DISTINCT SAFE_CAST(NUMERO_MED_ABONO AS STRING), '\n' ORDER BY SAFE_CAST(NUMERO_MED_ABONO AS STRING)) AS NUMERO_MED_ABONO,
    STRING_AGG(DISTINCT SAFE_CAST(MONTO_ENVIADO_TARJETA AS STRING), '\n' ORDER BY SAFE_CAST(MONTO_ENVIADO_TARJETA AS STRING)) AS MONTO_ENVIADO_TARJETA,
    STRING_AGG(DISTINCT SAFE_CAST(MONTO_COBRADO_TARJETA AS STRING), '\n' ORDER BY SAFE_CAST(MONTO_COBRADO_TARJETA AS STRING)) AS MONTO_COBRADO_TARJETA,
    STRING_AGG(DISTINCT SAFE_CAST(MONTO_ENVIADO_MED AS STRING), '\n' ORDER BY SAFE_CAST(MONTO_ENVIADO_MED AS STRING)) AS MONTO_ENVIADO_MED,
    STRING_AGG(DISTINCT SAFE_CAST(MONTO_COBRADO_MED AS STRING), '\n' ORDER BY SAFE_CAST(MONTO_COBRADO_MED AS STRING)) AS MONTO_COBRADO_MED,
    STRING_AGG(DISTINCT SAFE_CAST(MOTO_ABONO_MED AS STRING), '\n' ORDER BY SAFE_CAST(MOTO_ABONO_MED AS STRING)) AS MOTO_ABONO_MED,
    STRING_AGG(DISTINCT SAFE_CAST(ESTATUS_CYB AS STRING), '\n' ORDER BY SAFE_CAST(ESTATUS_CYB AS STRING)) AS ESTATUS_CYB,
    STRING_AGG(DISTINCT SAFE_CAST(FECHA_VALIDACION_CYB AS STRING), '\n' ORDER BY SAFE_CAST(FECHA_VALIDACION_CYB AS STRING)) AS FECHA_VALIDACION_CYB,
    STRING_AGG(DISTINCT SAFE_CAST(ESTATUS_ATG AS STRING), '\n' ORDER BY SAFE_CAST(ESTATUS_ATG AS STRING)) AS ESTATUS_ATG,
    STRING_AGG(DISTINCT SAFE_CAST(AUTORIZACION_PAYPAL AS STRING), '\n' ORDER BY SAFE_CAST(AUTORIZACION_PAYPAL AS STRING)) AS AUTORIZACION_PAYPAL,
    STRING_AGG(DISTINCT SAFE_CAST(AUT_BANCARIA_FOLIO_PAYPAL AS STRING), '\n' ORDER BY SAFE_CAST(AUT_BANCARIA_FOLIO_PAYPAL AS STRING)) AS AUT_BANCARIA_FOLIO_PAYPAL,
    STRING_AGG(DISTINCT SAFE_CAST(AUTORIZACION_MED AS STRING), '\n' ORDER BY SAFE_CAST(AUTORIZACION_MED AS STRING)) AS AUTORIZACION_MED,
  FROM BASE
  GROUP BY FMS_TX_ID
  ORDER BY FECHA_CREACION
);
CREATE TEMP TABLE DMDR AS (
  WITH AUX AS (
    SELECT
      t.MERCHANT_ID, t.REQUEST_ID, t.REQUEST_ID_TXT, t.TRANSACTION_DATE, t.MERCHANT_REFERENCE_NUMBER, t.REASON_CODE, t.REPLY_FLAG, t.ORDER_AMOUNT, t.CUSTOMER_ID, t.ACCOUNT_SUFFIX, t.CARD_BIN_NUMBER, t.CONNECTION_METHOD, t.SHIPPING_METHOD, t.BILL_TO_FIRST_NAME, t.BILL_TO_LAST_NAME, t.BILL_TO_EMAIL, t.BILLING_PHONE, t.BILL_ADDRESS1, t.BILL_ADDRESS2, t.BILL_CITY, t.BILL_STATE, t.BILL_POSTAL_CODE, t.IP_ADDRESS, t.IP_ROUTING_METHOD, t.IP_COUNTRY, t.IP_STATE, t.IP_CITY, t.DEVICE_FINGERPRINT_DEVICE_FIRST_ENCOUNTER, t.DEVICE_FINGERPRINT_DATE_DEVICE_FIRST_SEEN, t.DEVICE_FINGERPRINT_TRUE_IPADDRESS, t.DEVICE_FINGERPRINT_TRUE_IPADDRESS_CITY, t.DEVICE_FINGERPRINT_TRUE_IP_ADDRESS_STATE, t.EMAILAGE_DOMAIN_COMPANY, t.EMAILAGE_IP_REGION, t.EMAILAGE_IP_CITY, t.EMAILAGE_IP_POSTAL, t.MERCHANT_DEFINED_DATA1, t.MERCHANT_DEFINED_DATA2, t.MERCHANT_DEFINED_DATA3, t.MERCHANT_DEFINED_DATA4, t.MERCHANT_DEFINED_DATA5, t.MERCHANT_DEFINED_DATA6, t.MERCHANT_DEFINED_DATA11, t.MERCHANT_DEFINED_DATA12, t.MERCHANT_DEFINED_DATA14, t.MERCHANT_DEFINED_DATA19, t.MERCHANT_DEFINED_DATA20, t.MERCHANT_DEFINED_DATA21, t.MERCHANT_DEFINED_DATA50, t.MERCHANT_DEFINED_DATA51, t.MERCHANT_DEFINED_DATA52, t.MERCHANT_DEFINED_DATA53, t.MERCHANT_DEFINED_DATA54, t.MERCHANT_DEFINED_DATA55,
      SAFE_CAST(PRODUCT_SKU_1 AS STRING) AS PRODUCT_SKU_1, SAFE_CAST(PRODUCT_SKU_2 AS STRING) AS PRODUCT_SKU_2, SAFE_CAST(PRODUCT_SKU_3 AS STRING) AS PRODUCT_SKU_3, SAFE_CAST(PRODUCT_SKU_4 AS STRING) AS PRODUCT_SKU_4, SAFE_CAST(PRODUCT_SKU_5 AS STRING) AS PRODUCT_SKU_5, SAFE_CAST(PRODUCT_SKU_6 AS STRING) AS PRODUCT_SKU_6, SAFE_CAST(PRODUCT_SKU_7 AS STRING) AS PRODUCT_SKU_7, SAFE_CAST(PRODUCT_SKU_8 AS STRING) AS PRODUCT_SKU_8, SAFE_CAST(PRODUCT_SKU_9 AS STRING) AS PRODUCT_SKU_9, SAFE_CAST(PRODUCT_SKU_10 AS STRING) AS PRODUCT_SKU_10, SAFE_CAST(PRODUCT_NAME_1 AS STRING) AS PRODUCT_NAME_1, SAFE_CAST(PRODUCT_NAME_2 AS STRING) AS PRODUCT_NAME_2, SAFE_CAST(PRODUCT_NAME_3 AS STRING) AS PRODUCT_NAME_3, SAFE_CAST(PRODUCT_NAME_4 AS STRING) AS PRODUCT_NAME_4, SAFE_CAST(PRODUCT_NAME_5 AS STRING) AS PRODUCT_NAME_5, SAFE_CAST(PRODUCT_NAME_6 AS STRING) AS PRODUCT_NAME_6, SAFE_CAST(PRODUCT_NAME_7 AS STRING) AS PRODUCT_NAME_7, SAFE_CAST(PRODUCT_NAME_8 AS STRING) AS PRODUCT_NAME_8, SAFE_CAST(PRODUCT_NAME_9 AS STRING) AS PRODUCT_NAME_9, SAFE_CAST(PRODUCT_NAME_10 AS STRING) AS PRODUCT_NAME_10, SAFE_CAST(PRODUCT_CODE_1 AS STRING) AS PRODUCT_CODE_1, SAFE_CAST(PRODUCT_CODE_2 AS STRING) AS PRODUCT_CODE_2, SAFE_CAST(PRODUCT_CODE_3 AS STRING) AS PRODUCT_CODE_3, SAFE_CAST(PRODUCT_CODE_4 AS STRING) AS PRODUCT_CODE_4, SAFE_CAST(PRODUCT_CODE_5 AS STRING) AS PRODUCT_CODE_5, SAFE_CAST(PRODUCT_CODE_6 AS STRING) AS PRODUCT_CODE_6, SAFE_CAST(PRODUCT_CODE_7 AS STRING) AS PRODUCT_CODE_7, SAFE_CAST(PRODUCT_CODE_8 AS STRING) AS PRODUCT_CODE_8, SAFE_CAST(PRODUCT_CODE_9 AS STRING) AS PRODUCT_CODE_9, SAFE_CAST(PRODUCT_CODE_10 AS STRING) AS PRODUCT_CODE_10, SAFE_CAST(PRICE_1 AS STRING) AS PRICE_1, SAFE_CAST(PRICE_2 AS STRING) AS PRICE_2, SAFE_CAST(PRICE_3 AS STRING) AS PRICE_3, SAFE_CAST(PRICE_4 AS STRING) AS PRICE_4, SAFE_CAST(PRICE_5 AS STRING) AS PRICE_5, SAFE_CAST(PRICE_6 AS STRING) AS PRICE_6, SAFE_CAST(PRICE_7 AS STRING) AS PRICE_7, SAFE_CAST(PRICE_8 AS STRING) AS PRICE_8, SAFE_CAST(PRICE_9 AS STRING) AS PRICE_9, SAFE_CAST(PRICE_10 AS STRING) AS PRICE_10, SAFE_CAST(QUANTITY_1 AS STRING) AS QUANTITY_1, SAFE_CAST(QUANTITY_2 AS STRING) AS QUANTITY_2, SAFE_CAST(QUANTITY_3 AS STRING) AS QUANTITY_3, SAFE_CAST(QUANTITY_4 AS STRING) AS QUANTITY_4, SAFE_CAST(QUANTITY_5 AS STRING) AS QUANTITY_5, SAFE_CAST(QUANTITY_6 AS STRING) AS QUANTITY_6, SAFE_CAST(QUANTITY_7 AS STRING) AS QUANTITY_7, SAFE_CAST(QUANTITY_8 AS STRING) AS QUANTITY_8, SAFE_CAST(QUANTITY_9 AS STRING) AS QUANTITY_9, SAFE_CAST(QUANTITY_10 AS STRING) AS QUANTITY_10, t.DEVICE_FINGERPRINT
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_PREVFRAU_DMDR_LIV` AS t
    WHERE TRUE
      --OR DEVICE_FINGERPRINT IN ('e818679e1c7042deb6ad8b75a5e22cee', '9a42fddc77d341d9bf2ae0a56b30d6ed')
  ),
  AUX_AGG AS (
    SELECT 
      t.*, p.prod_idx, p.sku, p.name, p.code, p.price, p.qty
    FROM AUX AS t
    CROSS JOIN UNNEST([
      STRUCT(1 AS prod_idx, t.PRODUCT_SKU_1 AS sku, t.PRODUCT_NAME_1 AS name, t.PRODUCT_CODE_1 AS code, t.PRICE_1 AS price, t.QUANTITY_1 AS qty),
      STRUCT(2 AS prod_idx, t.PRODUCT_SKU_2 AS sku, t.PRODUCT_NAME_2 AS name, t.PRODUCT_CODE_2 AS code, t.PRICE_2 AS price, t.QUANTITY_2 AS qty),
      STRUCT(3 AS prod_idx, t.PRODUCT_SKU_3 AS sku, t.PRODUCT_NAME_3 AS name, t.PRODUCT_CODE_3 AS code, t.PRICE_3 AS price, t.QUANTITY_3 AS qty),
      STRUCT(4 AS prod_idx, t.PRODUCT_SKU_4 AS sku, t.PRODUCT_NAME_4 AS name, t.PRODUCT_CODE_4 AS code, t.PRICE_4 AS price, t.QUANTITY_4 AS qty),
      STRUCT(5 AS prod_idx, t.PRODUCT_SKU_5 AS sku, t.PRODUCT_NAME_5 AS name, t.PRODUCT_CODE_5 AS code, t.PRICE_5 AS price, t.QUANTITY_5 AS qty),
      STRUCT(6 AS prod_idx, t.PRODUCT_SKU_6 AS sku, t.PRODUCT_NAME_6 AS name, t.PRODUCT_CODE_6 AS code, t.PRICE_6 AS price, t.QUANTITY_6 AS qty),
      STRUCT(7 AS prod_idx, t.PRODUCT_SKU_7 AS sku, t.PRODUCT_NAME_7 AS name, t.PRODUCT_CODE_7 AS code, t.PRICE_7 AS price, t.QUANTITY_7 AS qty),
      STRUCT(8 AS prod_idx, t.PRODUCT_SKU_8 AS sku, t.PRODUCT_NAME_8 AS name, t.PRODUCT_CODE_8 AS code, t.PRICE_8 AS price, t.QUANTITY_8 AS qty),
      STRUCT(9 AS prod_idx, t.PRODUCT_SKU_9 AS sku, t.PRODUCT_NAME_9 AS name, t.PRODUCT_CODE_9 AS code, t.PRICE_9 AS price, t.QUANTITY_9 AS qty),
      STRUCT(10 AS prod_idx, t.PRODUCT_SKU_10 AS sku, t.PRODUCT_NAME_10 AS name, t.PRODUCT_CODE_10 AS code, t.PRICE_10 AS price, t.QUANTITY_10 AS qty)
      ]) AS p
    WHERE COALESCE(p.sku, p.name, p.code, p.price, p.qty) IS NOT NULL
  ),
  FINAL AS (
    SELECT
      * EXCEPT(prod_idx, sku, name, code, price, qty),
      ARRAY_TO_STRING(
        ARRAY_AGG(
          CONCAT(
            SAFE_CAST(prod_idx AS STRING), ') ',
            'SKU=', IFNULL(SAFE_CAST(sku AS STRING), ''),
            ' | NAME=', IFNULL(name, ''),
            ' | CODE=', IFNULL(code, ''),
            ' | PRICE=', IFNULL(SAFE_CAST(price AS STRING), ''),
            ' | QTY=', IFNULL(SAFE_CAST(qty AS STRING), '')
          )
        ) OVER (PARTITION BY MERCHANT_ID, REQUEST_ID, REQUEST_ID_TXT, TRANSACTION_DATE ORDER BY prod_idx),
        '\n'
      ) AS PRODUCTS,
    FROM AUX_AGG
    QUALIFY ROW_NUMBER() OVER (PARTITION BY MERCHANT_ID, REQUEST_ID, REQUEST_ID_TXT, TRANSACTION_DATE ORDER BY prod_idx) = 1
  )
  SELECT
    MERCHANT_REFERENCE_NUMBER, MERCHANT_ID, REQUEST_ID, REQUEST_ID_TXT, TRANSACTION_DATE, ORDER_AMOUNT, REASON_CODE, REPLY_FLAG, REPLACE(CUSTOMER_ID, "[at]", "@") AS CUSTOMER_ID, CARD_BIN_NUMBER, ACCOUNT_SUFFIX,
    PRODUCTS, CONNECTION_METHOD, SHIPPING_METHOD, BILL_TO_FIRST_NAME, BILL_TO_LAST_NAME, BILL_TO_EMAIL, BILLING_PHONE, BILL_ADDRESS1, BILL_ADDRESS2, BILL_CITY, BILL_STATE, BILL_POSTAL_CODE, 
    IP_ADDRESS,IP_ROUTING_METHOD, IP_COUNTRY, IP_STATE, IP_CITY,
    DEVICE_FINGERPRINT, DEVICE_FINGERPRINT_DEVICE_FIRST_ENCOUNTER, DEVICE_FINGERPRINT_DATE_DEVICE_FIRST_SEEN, DEVICE_FINGERPRINT_TRUE_IPADDRESS, DEVICE_FINGERPRINT_TRUE_IPADDRESS_CITY, DEVICE_FINGERPRINT_TRUE_IP_ADDRESS_STATE, 
    EMAILAGE_DOMAIN_COMPANY EMAILAGE_IP_REGION, EMAILAGE_IP_CITY, EMAILAGE_IP_POSTAL,
    MERCHANT_DEFINED_DATA1, MERCHANT_DEFINED_DATA2, MERCHANT_DEFINED_DATA3, MERCHANT_DEFINED_DATA4, MERCHANT_DEFINED_DATA5, MERCHANT_DEFINED_DATA6, MERCHANT_DEFINED_DATA11, MERCHANT_DEFINED_DATA12, MERCHANT_DEFINED_DATA14,
    MERCHANT_DEFINED_DATA19, MERCHANT_DEFINED_DATA20, MERCHANT_DEFINED_DATA21, MERCHANT_DEFINED_DATA50, MERCHANT_DEFINED_DATA51, MERCHANT_DEFINED_DATA52, MERCHANT_DEFINED_DATA53, MERCHANT_DEFINED_DATA54, MERCHANT_DEFINED_DATA55,
  FROM FINAL
  ORDER BY TRANSACTION_DATE
);

(--JOIN
  SELECT 
    FMS.TRJ, FMS.NOMBRE_CLIENTE, 
    FMS.FMS_TX_ID, FMS.ATG_TX_ID, FMS.ATG_ORDER_ID, FMS.ATG_SG_ID, FMS.BC_TX_ID, FMS.FECHA_CREACION, FMS.FECHA_PROCESAMIENTO, DMDR.MERCHANT_DEFINED_DATA12, DMDR.TRANSACTION_DATE,
    FMS.TOTAL_ORDEN, FMS.TIENDA, DMDR.MERCHANT_DEFINED_DATA6 AS PLAN_CVE, DMDR.MERCHANT_DEFINED_DATA11 AS CEL_NUM, FMS.CORREO_ELECTRONICO, DMDR.BILL_TO_EMAIL, 
    COALESCE(NULLIF(FMS.PRODUCTS, ""), NULLIF(DMDR.PRODUCTS, "")) AS PRODUCTS,
    FMS.TIPO_PAGO, FMS.TIPO_TARJETA, DMDR.MERCHANT_DEFINED_DATA54, DMDR.MERCHANT_DEFINED_DATA55, 
    FMS.NOMBRE_TIENDA, DMDR.MERCHANT_ID, DMDR.CONNECTION_METHOD, FMS.CANAL_VENTA,
    FMS.ESTATUS_ATG, DMDR.SHIPPING_METHOD, FMS.PEDIDO, FMS.REMISION, DMDR.BILL_TO_FIRST_NAME, DMDR.BILL_TO_LAST_NAME, DMDR.BILLING_PHONE, DMDR.BILL_ADDRESS1, DMDR.BILL_ADDRESS2, DMDR.BILL_CITY, DMDR.BILL_STATE, DMDR.BILL_POSTAL_CODE,
    DMDR.IP_ADDRESS, DMDR.IP_ROUTING_METHOD, DMDR.IP_COUNTRY, DMDR.IP_STATE, DMDR.IP_CITY, 
    DMDR.DEVICE_FINGERPRINT, DMDR.DEVICE_FINGERPRINT_DEVICE_FIRST_ENCOUNTER, DMDR.DEVICE_FINGERPRINT_DATE_DEVICE_FIRST_SEEN, DMDR.DEVICE_FINGERPRINT_TRUE_IPADDRESS, 
    DMDR.DEVICE_FINGERPRINT_TRUE_IPADDRESS_CITY, DMDR.DEVICE_FINGERPRINT_TRUE_IP_ADDRESS_STATE, DMDR.EMAILAGE_IP_REGION, DMDR.EMAILAGE_IP_CITY, DMDR.EMAILAGE_IP_POSTAL,
    FMS.USO_MED, FMS.NUMERO_MED_PAGO, FMS.NUMERO_MED_ABONO, FMS.MONTO_ENVIADO_TARJETA, FMS.MONTO_COBRADO_TARJETA, FMS.MONTO_ENVIADO_MED, FMS.MONTO_COBRADO_MED, FMS.MOTO_ABONO_MED,
    DMDR.MERCHANT_DEFINED_DATA1, DMDR.MERCHANT_DEFINED_DATA19, DMDR.MERCHANT_DEFINED_DATA20,
    FMS.ESTATUS_CYB, FMS.AUTORIZACION_PAYPAL, FMS.AUT_BANCARIA_FOLIO_PAYPAL, FMS.AUTORIZACION_MED,
    DMDR.REASON_CODE, DMDR.REPLY_FLAG
  FROM FMS
  LEFT JOIN DMDR
    ON SAFE_CAST(FMS.FMS_TX_ID AS NUMERIC) = SAFE_CAST(DMDR.MERCHANT_REFERENCE_NUMBER AS NUMERIC)
  ORDER BY FMS.FECHA_CREACION
);

DROP TABLE IF EXISTS FMS;
DROP TABLE IF EXISTS DMDR;
