DECLARE UNICO STRING DEFAULT "ŠŽšžŸÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïðñòóôõöùúûüýÿ";
DECLARE ASCI  STRING DEFAULT "SZszYAAAAAACEEEEIIIIDNOOOOOUUUUYaaaaaaceeeeiiiidnooooouuuuyy";

WITH RH_LAST AS (
  SELECT
    LLAVE,
    ARRAY_AGG(SAFE_CAST(ID_NUMERO_PERSONAL AS NUMERIC) IGNORE NULLS ORDER BY FCH_MEDIDA DESC LIMIT 1)[OFFSET(0)] AS ID_NUMERO_PERSONAL,
    ARRAY_AGG(ID_USER IGNORE NULLS ORDER BY FCH_MEDIDA DESC LIMIT 1)[OFFSET(0)] AS ID_USER,
    ARRAY_AGG(SAFE_CAST(NUM_JEFE AS NUMERIC) IGNORE NULLS ORDER BY FCH_MEDIDA DESC LIMIT 1)[OFFSET(0)] AS NUM_JEFE,
    ARRAY_AGG(DES_UNI_ORG IGNORE NULLS ORDER BY FCH_MEDIDA DESC LIMIT 1)[OFFSET(0)] AS DES_UNI_ORG,
    ARRAY_AGG(DES_FUNCION IGNORE NULLS ORDER BY FCH_MEDIDA DESC LIMIT 1)[OFFSET(0)] AS DES_FUNCION,
    ARRAY_AGG(FCH_ALTA_TECNICA IGNORE NULLS ORDER BY FCH_MEDIDA DESC LIMIT 1)[OFFSET(0)] AS FCH_ALTA_TECNICA,
    ARRAY_AGG(ESTATUS_OCUPACIONAL IGNORE NULLS ORDER BY FCH_MEDIDA DESC LIMIT 1)[OFFSET(0)] AS ESTATUS_OCUPACIONAL,
    ARRAY_AGG(MEDIDA IGNORE NULLS ORDER BY FCH_MEDIDA DESC LIMIT 1)[OFFSET(0)] AS MEDIDA,
    ARRAY_AGG(FCH_MEDIDA ORDER BY FCH_MEDIDA DESC LIMIT 1)[OFFSET(0)] AS FCH_MEDIDA,
    ARRAY_AGG(
      TRANSLATE(CONCAT(TRIM(NOMBRE), " ", TRIM(APELLIDO_PAT), " ", TRIM(APELLIDO_MAT)), UNICO, ASCI)
      ORDER BY FCH_MEDIDA DESC LIMIT 1
    )[OFFSET(0)] AS NOMBRE_NORM
  FROM `crp-pro-rh-modelodatos.mus_pro_modelo_colaborador_shared_views.VFAC_RH_AUDITORIA_PREV_FRAUDE`
  GROUP BY LLAVE
),

VND AS (
  SELECT DISTINCT
    A.VND_CVE, 
    NULLIF(A.CTA_CVE, 0) AS CTA_CVE, 
    NULLIF(TRIM(UPPER(A.VND_DES_NOM)), "-1") AS VND_DES_NOM,
    NULLIF(TRIM(UPPER(A.VND_DES_APE)), "-1") AS VND_DES_APE,
    NULLIF(TRIM(UPPER(A.VND_DES_APM)), "-1") AS VND_DES_APM,
    NULLIF(TRIM(UPPER(A.VND_DES_CIU)), "-1") AS VND_DES_CIU,
    A.EDO_CVE,
    NULLIF(A.VND_FCH_NAC, DATE(1900,1,1)) AS VND_FCH_NAC,
    A.VND_EDAD, 
    NULLIF(TRIM(UPPER(A.VND_LUG_NAC)), "-1") AS VND_LUG_NAC,
    CASE WHEN A.VND_FCH_ALT = DATE(1900,1,1) OR A.VND_FCH_ALT = DATE(9999,12,30) THEN NULL ELSE A.VND_FCH_ALT END AS VND_FCH_ALT,
    CASE WHEN A.VND_FCH_TER = DATE(1900,1,1) OR A.VND_FCH_TER = DATE(9999,12,30) THEN NULL ELSE A.VND_FCH_TER END AS VND_FCH_TER,
    IF(NULLIF(A.VND_FCH_TER, DATE(1900,1,1)) IS NULL, "ACTIVO", "BAJA") AS VND_STT,
    A.VND_SEXO, 
    NULLIF(TRIM(UPPER(A.VND_EDO_CIV)), "-1") AS VND_EDO_CIV, 
    A.VND_PLN_HOR,
    SAFE_CAST(A.TDA_CVE AS NUMERIC) AS TDA_CVE,
    TRIM(B_CON.CON_DES) AS CON_DES, 
    TRIM(C_TRB.TRB_DES) AS TRB_DES, 
    TRIM(D_SEC.SEC_DES) AS SEC_DES, 
    UPPER(TRIM(D_SEC.DIR_DES)) AS DIR_DES,
    V.USR AS USR_VPL, 
    V.ID_USER AS ID_USER_VPL, 
    V.TIP_PERF,
    A.VND_CDP, 
    A.VND_NUM_HIJ,
    TRANSLATE(CONCAT(TRIM(A.VND_DES_NOM), " ", TRIM(A.VND_DES_APE), " ", TRIM(A.VND_DES_APM)), UNICO, ASCI) AS NOMBRE_NORM
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_VND` AS A
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VCIS_VND_CON` AS B_CON
    ON REGEXP_REPLACE(TRIM(A.CON_CVE), r"^0*", "") = REGEXP_REPLACE(TRIM(B_CON.CON_CVE), r"^0*", "")
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_SNFIN.VSDIM_TRB_VND` AS C_TRB
    ON A.TRB_CVE = C_TRB.TRB_CVE
  LEFT JOIN  `crp-pro-dwh-semanticagold.EIL_DP_SNFIN.VCIS_SEC_CRD_SCR` AS D_SEC
    ON REGEXP_REPLACE(TRIM(A.SEC_CVE), r"^0*", "") = REGEXP_REPLACE(TRIM(D_SEC.SEC_CVE), r"^0*", "") AND A.EMPRESA_ID = D_SEC.EMPRESA_ID
  LEFT JOIN `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VDIM_PREVFRAU_USR_VPL_HIST` AS V
    ON A.VND_CVE = V.CVE_EMP
  WHERE TRUE
    AND A.VND_CVE IS NOT NULL
    AND A.VND_DES_NOM IS NOT NULL AND A.VND_DES_APE IS NOT NULL AND A.VND_DES_APM IS NOT NULL
    AND A.VND_DES_NOM <> "-1" AND A.VND_DES_APE <> "-1" AND A.VND_DES_APM <> "-1"
    AND A.TDA_CVE  ='0660'
),

USR AS (
  SELECT DISTINCT
    USR, CVE_EMP, ID_USER, NOM_PERF, FCH_BAJ,
    SAFE_CAST(TDA AS NUMERIC) AS TDA, TDA_NOM,
    TRANSLATE(TRIM(UPPER(EMP_NOM)), UNICO, ASCI) AS EMP_NOM
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VDIM_PREVFRAU_USR_VPL_HIST`
),

VPL_RH AS (
  SELECT
    -- Llave Principal
    COALESCE(B.VND_CVE, R.ID_NUMERO_PERSONAL) AS CVE_EMP,
    
    -- IDs de Usuario
    COALESCE(B.USR_VPL, U1.USR, U2.USR, R.ID_USER) AS USR,
    COALESCE(B.ID_USER_VPL, U1.ID_USER, U2.ID_USER) AS ID_USER,
    
    -- Nombres
    COALESCE(B.NOMBRE_NORM, R.NOMBRE_NORM) AS EMP_NOM,
    B.VND_DES_NOM,
    B.VND_DES_APE,
    B.VND_DES_APM,
    
    -- Datos demográficos y ubicación de VND
    B.VND_EDAD,
    B.VND_FCH_NAC,
    B.VND_LUG_NAC,
    B.VND_SEXO,
    B.VND_EDO_CIV,
    B.VND_DES_CIU,
    B.EDO_CVE,
    B.VND_CDP,
    B.VND_NUM_HIJ,
    
    -- Homologación de Catálogos (Prioridad: VND -> RH)
    COALESCE(B.CON_DES, R.DES_UNI_ORG) AS CON_DES,
    COALESCE(B.TRB_DES, R.DES_FUNCION) AS TRB_DES,
    
    -- Otros catálogos y perfiles
    B.CTA_CVE,
    B.SEC_DES,
    B.DIR_DES,
    B.VND_PLN_HOR,
    B.TIP_PERF,
    COALESCE(U1.NOM_PERF, U2.NOM_PERF) AS NOM_PERF,
    
    -- Datos Tienda
    COALESCE(B.TDA_CVE, U1.TDA, U2.TDA) AS TDA_CVE,
    COALESCE(U1.TDA_NOM, U2.TDA_NOM) AS TDA_NOM,
    
    -- Estatus
    CASE
      WHEN B.VND_FCH_TER IS NOT NULL
        OR U1.FCH_BAJ IS NOT NULL 
        OR U2.FCH_BAJ IS NOT NULL
        OR R.ESTATUS_OCUPACIONAL = "Dado de baja"
        OR (R.MEDIDA LIKE "%Baja%" AND R.FCH_MEDIDA IS NOT NULL)
      THEN "BAJA"
      ELSE "ACTIVO"
    END AS EMP_STT,
    
    -- Dato Exclusivo RH (Jefe)
    R.NUM_JEFE AS EMP_JEF,
    
    -- Homologación de Fechas
    COALESCE(B.VND_FCH_ALT, R.FCH_ALTA_TECNICA) AS FCH_ALT,
    COALESCE(
      B.VND_FCH_TER, 
      U1.FCH_BAJ, 
      U2.FCH_BAJ, 
      CASE WHEN R.MEDIDA LIKE "%Baja%" THEN R.FCH_MEDIDA ELSE NULL END
    ) AS FCH_BAJ

  FROM VND AS B
  FULL OUTER JOIN RH_LAST AS R
    ON B.VND_CVE = R.ID_NUMERO_PERSONAL 
  
  LEFT JOIN USR AS U1
    ON R.ID_USER IS NOT NULL AND R.ID_USER = U1.USR
  LEFT JOIN USR AS U2
    ON R.ID_USER IS NULL AND COALESCE(B.VND_CVE, R.ID_NUMERO_PERSONAL) = U2.CVE_EMP
    
  QUALIFY ROW_NUMBER() OVER(
    PARTITION BY COALESCE(B.VND_CVE, R.ID_NUMERO_PERSONAL)
    ORDER BY
      CASE WHEN R.ID_USER IS NOT NULL AND R.ID_USER = U1.USR THEN 0 ELSE 1 END,
      R.FCH_MEDIDA DESC
  ) = 1
)

SELECT * FROM VPL_RH;
